const GeoLayout peach_eye_open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, peach_eye_opt1_eye_dl1_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_eye_mid_close[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, peach_eye_opt2_eye_dl2_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_eye_fully_close[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, peach_eye_opt3_eye_dl3_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_lip_a[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, peach_lip_opt2_lip_dl2_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_lip_e[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, peach_lip_opt1_lip_dl1_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_lip_o[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, peach_lip_opt3_lip_dl3_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_left_hand_close[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 348, 0, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, peach_left_hand_opt1_left_hand_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_right_hand_close[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 348, 0, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, peach_right_hand_switch_right_hand_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_peach_invis_opt1_eye_openinvis[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, peach_peach_invis_opt1_eye_opt1_eye_dl1nvis_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_peach_invis_opt1_eye_mid_closeinvis[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, peach_peach_invis_opt1_eye_opt2_eye_dl2invis_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_peach_invis_opt1_eye_fully_closeinvis[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, peach_peach_invis_opt1_eye_opt3_eye_dl3nvis_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_peach_invis_opt1_lip_ainvis[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, peach_peach_invis_opt1_lip_opt2_lip_dl2nvis_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_peach_invis_opt1_lip_einvis[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, peach_peach_invis_opt1_lip_opt1_lip_dl1nvis_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_peach_invis_opt1_lip_oinvis[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, peach_peach_invis_opt1_lip_opt3_lip_dl3nvis_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_peach_invis_opt1_left_hand_closeinvis[] = {
	GEO_TRANSLATE_ROTATE(LAYER_TRANSPARENT, 348, 0, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, peach_peach_invis_opt1_left_hand_opt1_left_hand_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_peach_invis_opt1_right_hand_closeinvis[] = {
	GEO_TRANSLATE_ROTATE(LAYER_TRANSPARENT, 348, 0, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, peach_peach_invis_opt1_right_hand_switch_right_hand_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_001_switch_opt1_eye_switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, peach_peach_invis_opt1_eye_dl_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_peach_invis[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_TRANSPARENT, 16384),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, peach_peach_invis_opt1_000_offset_001_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 312, 0, 0, peach_peach_invis_opt1_000_offset_002_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 528, 0, 0, peach_peach_invis_opt1_000_offset_003_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_SWITCH_CASE(8, geo_switch_peach_eyes),
							GEO_OPEN_NODE(),
								GEO_NODE_START(),
								GEO_OPEN_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, peach_peach_invis_opt1_000_offset_004_skinned_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 152, -312, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, peach_peach_invis_opt1_000_offset_004_mesh_layer_1),
							GEO_CLOSE_NODE(),
							GEO_SWITCH_CASE(8, geo_switch_peach_eyes),
							GEO_OPEN_NODE(),
								GEO_NODE_START(),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, peach_peach_invis_opt1_eye_dl_mesh_layer_1),
								GEO_CLOSE_NODE(),
								GEO_BRANCH(1, peach_peach_invis_opt1_eye_openinvis),
								GEO_BRANCH(1, peach_peach_invis_opt1_eye_mid_closeinvis),
								GEO_BRANCH(1, peach_peach_invis_opt1_eye_fully_closeinvis),
								GEO_BRANCH(1, peach_001_switch_opt1_eye_switch_opt4),
								GEO_BRANCH(1, peach_peach_invis_opt1_eye_openinvis),
								GEO_BRANCH(1, peach_peach_invis_opt1_eye_mid_closeinvis),
								GEO_BRANCH(1, peach_peach_invis_opt1_eye_fully_closeinvis),
							GEO_CLOSE_NODE(),
							GEO_SWITCH_CASE(3, geo_switch_peach_lip),
							GEO_OPEN_NODE(),
								GEO_NODE_START(),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, peach_peach_invis_opt1_lip_dl_mesh_layer_1),
								GEO_CLOSE_NODE(),
								GEO_BRANCH(1, peach_peach_invis_opt1_lip_ainvis),
								GEO_BRANCH(1, peach_peach_invis_opt1_lip_einvis),
								GEO_BRANCH(1, peach_peach_invis_opt1_lip_oinvis),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 528, 0, 0, peach_peach_invis_opt1_002_offset_001_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 528, 0, 0, peach_peach_invis_opt1_003_offset_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 252, 0, 336, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, peach_peach_invis_opt1_000_offset_005_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 416, 0, 11, peach_peach_invis_opt1_000_offset_006_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(1, geo_switch_peach_left_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_TRANSPARENT, 348, 0, 0, peach_peach_invis_opt1_000_offset_007_mesh_layer_1),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, peach_peach_invis_opt1_left_hand_closeinvis),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, peach_peach_invis_opt1_002_offset_002_mesh_layer_1),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 252, 0, -336, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, peach_peach_invis_opt1_000_offset_008_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 416, 0, -7, peach_peach_invis_opt1_000_offset_009_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(1, geo_switch_peach_right_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_TRANSPARENT, 348, 0, 0, peach_peach_invis_opt1_000_offset_010_mesh_layer_1),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, peach_peach_invis_opt1_right_hand_closeinvis),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, peach_peach_invis_opt1_002_offset_003_mesh_layer_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 312, 0, 0, peach_peach_invis_opt1_002_offset_004_mesh_layer_1),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, -92, -4, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, peach_peach_invis_opt1_000_offset_011_mesh_layer_1),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_001_switch_opt0_eye_switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, peach_eye_dl_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 150, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_ASM(10, geo_update_layer_transparency),
				GEO_SWITCH_CASE(2, geo_switch_anim_state),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_NODE_START(),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_SCALE(LAYER_OPAQUE, 16384),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, peach_000_offset_001_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 312, 0, 0, peach_000_offset_002_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 528, 0, 0, peach_000_offset_003_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, peach_000_offset_003_mesh_layer_5),
												GEO_SWITCH_CASE(8, geo_switch_peach_eyes),
												GEO_OPEN_NODE(),
													GEO_NODE_START(),
													GEO_OPEN_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, peach_000_offset_004_skinned_mesh_layer_1),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, peach_000_offset_004_skinned_mesh_layer_5),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 152, -312, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, peach_000_offset_004_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, peach_000_offset_004_mesh_layer_5),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_SWITCH_CASE(8, geo_switch_peach_eyes),
												GEO_OPEN_NODE(),
													GEO_NODE_START(),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_OPAQUE, peach_eye_dl_mesh_layer_1),
													GEO_CLOSE_NODE(),
													GEO_BRANCH(1, peach_eye_open),
													GEO_BRANCH(1, peach_eye_mid_close),
													GEO_BRANCH(1, peach_eye_fully_close),
													GEO_BRANCH(1, peach_001_switch_opt0_eye_switch_opt4),
													GEO_BRANCH(1, peach_eye_open),
													GEO_BRANCH(1, peach_eye_mid_close),
													GEO_BRANCH(1, peach_eye_fully_close),
												GEO_CLOSE_NODE(),
												GEO_SWITCH_CASE(3, geo_switch_peach_lip),
												GEO_OPEN_NODE(),
													GEO_NODE_START(),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_OPAQUE, peach_lip_dl_mesh_layer_1),
													GEO_CLOSE_NODE(),
													GEO_BRANCH(1, peach_lip_a),
													GEO_BRANCH(1, peach_lip_e),
													GEO_BRANCH(1, peach_lip_o),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 528, 0, 0, peach_002_offset_001_mesh_layer_1),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 528, 0, 0, peach_003_offset_mesh_layer_1),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 252, 0, 336, NULL),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, peach_000_offset_005_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 416, 0, 11, peach_000_offset_006_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_SWITCH_CASE(1, geo_switch_peach_left_hand),
														GEO_OPEN_NODE(),
															GEO_NODE_START(),
															GEO_OPEN_NODE(),
																GEO_ANIMATED_PART(LAYER_OPAQUE, 348, 0, 0, peach_000_offset_007_mesh_layer_1),
															GEO_CLOSE_NODE(),
															GEO_BRANCH(1, peach_left_hand_close),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, peach_002_offset_002_mesh_layer_1),
											GEO_CLOSE_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 252, 0, -336, NULL),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, peach_000_offset_008_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 416, 0, -7, peach_000_offset_009_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_SWITCH_CASE(1, geo_switch_peach_right_hand),
														GEO_OPEN_NODE(),
															GEO_NODE_START(),
															GEO_OPEN_NODE(),
																GEO_ANIMATED_PART(LAYER_OPAQUE, 348, 0, 0, peach_000_offset_010_mesh_layer_1),
															GEO_CLOSE_NODE(),
															GEO_BRANCH(1, peach_right_hand_close),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, peach_002_offset_003_mesh_layer_1),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 312, 0, 0, peach_002_offset_004_mesh_layer_1),
										GEO_ANIMATED_PART(LAYER_OPAQUE, -92, -4, 0, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, peach_000_offset_011_mesh_layer_1),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_BRANCH(1, peach_peach_invis),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
