extern const GeoLayout mario_head_capless[];
extern const GeoLayout mario_eyes_half_closed[];
extern const GeoLayout mario_eyes_closed[];
extern const GeoLayout mario_eyes_tiptoe[];
extern const GeoLayout mario_eyes_angry[];
extern const GeoLayout mario_eyes_happy[];
extern const GeoLayout mario_eyes_exhausted[];
extern const GeoLayout mario_eyes_dead[];
extern const GeoLayout mario_eyes_hurt[];
extern const GeoLayout mario_face_happy[];
extern const GeoLayout mario_face_angry[];
extern const GeoLayout mario_face_O[];
extern const GeoLayout mario_face_E[];
extern const GeoLayout mario_left_hand_open[];
extern const GeoLayout mario_right_hand_open[];
extern const GeoLayout mario_right_hand_peace[];
extern const GeoLayout mario_right_hand_cap[];
extern const GeoLayout mario_right_hand_wing_cap[];
extern const GeoLayout mario_geo_opt_1[];
extern const GeoLayout mario_geo_opt_2[];
extern const GeoLayout mario_head_capless_opt_1[];
extern const GeoLayout mario_eyes_half_closed_opt_1[];
extern const GeoLayout mario_eyes_closed_opt_1[];
extern const GeoLayout mario_eyes_tiptoe_opt_1[];
extern const GeoLayout mario_eyes_angry_opt_1[];
extern const GeoLayout mario_eyes_happy_opt_1[];
extern const GeoLayout mario_eyes_exhausted_opt_1[];
extern const GeoLayout mario_eyes_dead_opt_1[];
extern const GeoLayout mario_eyes_hurt_opt_1[];
extern const GeoLayout mario_geo_opt_1_1_opt_1_opt_1[];
extern const GeoLayout mario_geo_opt_1_1_opt_1_opt_2[];
extern const GeoLayout mario_face_happy_opt_1[];
extern const GeoLayout mario_face_angry_opt_1[];
extern const GeoLayout mario_face_O_opt_1[];
extern const GeoLayout mario_face_E_opt_1[];
extern const GeoLayout mario_left_hand_open_opt_1[];
extern const GeoLayout mario_right_hand_open_opt_1[];
extern const GeoLayout mario_right_hand_peace_opt_1[];
extern const GeoLayout mario_right_hand_cap_opt_1[];
extern const GeoLayout mario_right_hand_wing_cap_opt_1[];
extern const GeoLayout mario_geo_opt_1_1[];
extern const GeoLayout mario_head_capless_opt_2[];
extern const GeoLayout mario_eyes_half_closed_opt_2[];
extern const GeoLayout mario_eyes_closed_opt_2[];
extern const GeoLayout mario_eyes_tiptoe_opt_2[];
extern const GeoLayout mario_eyes_angry_opt_2[];
extern const GeoLayout mario_eyes_happy_opt_2[];
extern const GeoLayout mario_eyes_exhausted_opt_2[];
extern const GeoLayout mario_eyes_dead_opt_2[];
extern const GeoLayout mario_eyes_hurt_opt_2[];
extern const GeoLayout mario_geo_opt_2_1_opt_2_opt_1[];
extern const GeoLayout mario_geo_opt_2_1_opt_2_opt_2[];
extern const GeoLayout mario_face_happy_opt_2[];
extern const GeoLayout mario_face_angry_opt_2[];
extern const GeoLayout mario_face_O_opt_2[];
extern const GeoLayout mario_face_E_opt_2[];
extern const GeoLayout mario_left_hand_open_opt_2[];
extern const GeoLayout mario_right_hand_open_opt_2[];
extern const GeoLayout mario_right_hand_peace_opt_2[];
extern const GeoLayout mario_right_hand_cap_opt_2[];
extern const GeoLayout mario_right_hand_wing_cap_opt_2[];
extern const GeoLayout mario_geo_opt_2_1[];
extern const GeoLayout mario_head_capless_opt_3[];
extern const GeoLayout mario_eyes_half_closed_opt_3[];
extern const GeoLayout mario_eyes_closed_opt_3[];
extern const GeoLayout mario_eyes_tiptoe_opt_3[];
extern const GeoLayout mario_eyes_angry_opt_3[];
extern const GeoLayout mario_eyes_happy_opt_3[];
extern const GeoLayout mario_eyes_exhausted_opt_3[];
extern const GeoLayout mario_eyes_dead_opt_3[];
extern const GeoLayout mario_eyes_hurt_opt_3[];
extern const GeoLayout mario_geo_opt_3_opt_3_opt_1[];
extern const GeoLayout mario_geo_opt_3_opt_3_opt_2[];
extern const GeoLayout mario_face_happy_opt_3[];
extern const GeoLayout mario_face_angry_opt_3[];
extern const GeoLayout mario_face_O_opt_3[];
extern const GeoLayout mario_face_E_opt_3[];
extern const GeoLayout mario_left_hand_open_opt_3[];
extern const GeoLayout mario_right_hand_open_opt_3[];
extern const GeoLayout mario_right_hand_peace_opt_3[];
extern const GeoLayout mario_right_hand_cap_opt_3[];
extern const GeoLayout mario_right_hand_wing_cap_opt_3[];
extern const GeoLayout mario_geo_opt_3[];
extern const GeoLayout mario_geo[];
extern Lights1 mario_mario_overalls_lights;
extern Lights1 mario_mario_buttons_lights;
extern Lights1 mario_mario_shirt_lights;
extern Lights1 mario_mario_teeth_lights;
extern Lights1 mario_mario_hair_lights;
extern Lights1 mario_mario_mustache_lights;
extern Lights1 mario_mario_eye_lights;
extern Lights1 mario_mario_skin_lights;
extern Lights1 mario_mario_mouth_lights;
extern Lights1 mario_mario_tongue_lights;
extern Lights1 mario_mario_wings_lights;
extern Lights1 mario_mario_gloves_lights;
extern Lights1 mario_mario_cap_inside_lights;
extern Lights1 mario_mario_shoes_lights;
extern Lights1 mario_mario_soles_lights;
extern Lights1 mario_newmetal_lights;
extern u8 mario_shine_dull_rgba32[];
extern u8 mario_mario_eyes_blue_rgba32[];
extern u8 mario_mario_metal_new_rgba16[];
extern Vtx mario_Torso_mesh_layer_1_vtx_0[2109];
extern Gfx mario_Torso_mesh_layer_1_tri_0[];
extern Vtx mario_Torso_mesh_layer_1_vtx_1[223];
extern Gfx mario_Torso_mesh_layer_1_tri_1[];
extern Vtx mario_Torso_mesh_layer_1_vtx_2[675];
extern Gfx mario_Torso_mesh_layer_1_tri_2[];
extern Vtx mario_Cap_DL_mesh_layer_1_vtx_0[1105];
extern Gfx mario_Cap_DL_mesh_layer_1_tri_0[];
extern Vtx mario_Cap_DL_mesh_layer_1_vtx_1[60];
extern Gfx mario_Cap_DL_mesh_layer_1_tri_1[];
extern Vtx mario_Cap_DL_mesh_layer_1_vtx_2[567];
extern Gfx mario_Cap_DL_mesh_layer_1_tri_2[];
extern Vtx mario_002_switch_option_head_hair_mesh_layer_1_vtx_0[1404];
extern Gfx mario_002_switch_option_head_hair_mesh_layer_1_tri_0[];
extern Vtx mario_Eyes_DL_mesh_layer_1_vtx_0[114];
extern Gfx mario_Eyes_DL_mesh_layer_1_tri_0[];
extern Vtx mario_Eyes_DL_mesh_layer_1_vtx_1[234];
extern Gfx mario_Eyes_DL_mesh_layer_1_tri_1[];
extern Vtx mario_002_switch_option_eyes_half_closed_mesh_layer_1_vtx_0[313];
extern Gfx mario_002_switch_option_eyes_half_closed_mesh_layer_1_tri_0[];
extern Vtx mario_002_switch_option_eyes_half_closed_mesh_layer_1_vtx_1[114];
extern Gfx mario_002_switch_option_eyes_half_closed_mesh_layer_1_tri_1[];
extern Vtx mario_002_switch_option_eyes_half_closed_mesh_layer_1_vtx_2[234];
extern Gfx mario_002_switch_option_eyes_half_closed_mesh_layer_1_tri_2[];
extern Vtx mario_002_switch_option_eyes_closed_mesh_layer_1_vtx_0[313];
extern Gfx mario_002_switch_option_eyes_closed_mesh_layer_1_tri_0[];
extern Vtx mario_002_switch_option_eyes_closed_mesh_layer_1_vtx_1[114];
extern Gfx mario_002_switch_option_eyes_closed_mesh_layer_1_tri_1[];
extern Vtx mario_002_switch_option_eyes_half_open_mesh_layer_1_vtx_0[114];
extern Gfx mario_002_switch_option_eyes_half_open_mesh_layer_1_tri_0[];
extern Vtx mario_002_switch_option_eyes_half_open_mesh_layer_1_vtx_1[234];
extern Gfx mario_002_switch_option_eyes_half_open_mesh_layer_1_tri_1[];
extern Vtx mario_002_switch_option_eyes_angry_mesh_layer_1_vtx_0[114];
extern Gfx mario_002_switch_option_eyes_angry_mesh_layer_1_tri_0[];
extern Vtx mario_002_switch_option_eyes_angry_mesh_layer_1_vtx_1[234];
extern Gfx mario_002_switch_option_eyes_angry_mesh_layer_1_tri_1[];
extern Vtx mario_002_switch_option_eyes_happy_mesh_layer_1_vtx_0[114];
extern Gfx mario_002_switch_option_eyes_happy_mesh_layer_1_tri_0[];
extern Vtx mario_002_switch_option_eyes_happy_mesh_layer_1_vtx_1[234];
extern Gfx mario_002_switch_option_eyes_happy_mesh_layer_1_tri_1[];
extern Vtx mario_002_switch_option_eyes_exhausted_mesh_layer_1_vtx_0[154];
extern Gfx mario_002_switch_option_eyes_exhausted_mesh_layer_1_tri_0[];
extern Vtx mario_002_switch_option_eyes_exhausted_mesh_layer_1_vtx_1[114];
extern Gfx mario_002_switch_option_eyes_exhausted_mesh_layer_1_tri_1[];
extern Vtx mario_002_switch_option_eyes_exhausted_mesh_layer_1_vtx_2[234];
extern Gfx mario_002_switch_option_eyes_exhausted_mesh_layer_1_tri_2[];
extern Vtx mario_002_switch_option_eyes_dead_mesh_layer_1_vtx_0[114];
extern Gfx mario_002_switch_option_eyes_dead_mesh_layer_1_tri_0[];
extern Vtx mario_002_switch_option_eyes_dead_mesh_layer_1_vtx_1[234];
extern Gfx mario_002_switch_option_eyes_dead_mesh_layer_1_tri_1[];
extern Vtx mario_002_switch_option_eyes_hurt_mesh_layer_1_vtx_0[114];
extern Gfx mario_002_switch_option_eyes_hurt_mesh_layer_1_tri_0[];
extern Vtx mario_002_switch_option_eyes_hurt_mesh_layer_1_vtx_1[313];
extern Gfx mario_002_switch_option_eyes_hurt_mesh_layer_1_tri_1[];
extern Vtx mario_Face_DL_mesh_layer_1_vtx_0[1786];
extern Gfx mario_Face_DL_mesh_layer_1_tri_0[];
extern Vtx mario_Face_DL_mesh_layer_1_vtx_1[62];
extern Gfx mario_Face_DL_mesh_layer_1_tri_1[];
extern Vtx mario_Face_DL_mesh_layer_1_vtx_2[350];
extern Gfx mario_Face_DL_mesh_layer_1_tri_2[];
extern Vtx mario_002_switch_option_face_happy_mesh_layer_1_vtx_0[1786];
extern Gfx mario_002_switch_option_face_happy_mesh_layer_1_tri_0[];
extern Vtx mario_002_switch_option_face_happy_mesh_layer_1_vtx_1[64];
extern Gfx mario_002_switch_option_face_happy_mesh_layer_1_tri_1[];
extern Vtx mario_002_switch_option_face_happy_mesh_layer_1_vtx_2[116];
extern Gfx mario_002_switch_option_face_happy_mesh_layer_1_tri_2[];
extern Vtx mario_002_switch_option_face_happy_mesh_layer_1_vtx_3[76];
extern Gfx mario_002_switch_option_face_happy_mesh_layer_1_tri_3[];
extern Vtx mario_002_switch_option_face_happy_mesh_layer_1_vtx_4[350];
extern Gfx mario_002_switch_option_face_happy_mesh_layer_1_tri_4[];
extern Vtx mario_002_switch_option_face_angry_mesh_layer_1_vtx_0[1786];
extern Gfx mario_002_switch_option_face_angry_mesh_layer_1_tri_0[];
extern Vtx mario_002_switch_option_face_angry_mesh_layer_1_vtx_1[62];
extern Gfx mario_002_switch_option_face_angry_mesh_layer_1_tri_1[];
extern Vtx mario_002_switch_option_face_angry_mesh_layer_1_vtx_2[350];
extern Gfx mario_002_switch_option_face_angry_mesh_layer_1_tri_2[];
extern Vtx mario_002_switch_option_face_o_mesh_layer_1_vtx_0[1786];
extern Gfx mario_002_switch_option_face_o_mesh_layer_1_tri_0[];
extern Vtx mario_002_switch_option_face_o_mesh_layer_1_vtx_1[64];
extern Gfx mario_002_switch_option_face_o_mesh_layer_1_tri_1[];
extern Vtx mario_002_switch_option_face_o_mesh_layer_1_vtx_2[116];
extern Gfx mario_002_switch_option_face_o_mesh_layer_1_tri_2[];
extern Vtx mario_002_switch_option_face_o_mesh_layer_1_vtx_3[76];
extern Gfx mario_002_switch_option_face_o_mesh_layer_1_tri_3[];
extern Vtx mario_002_switch_option_face_o_mesh_layer_1_vtx_4[350];
extern Gfx mario_002_switch_option_face_o_mesh_layer_1_tri_4[];
extern Vtx mario_002_switch_option_face_e_mesh_layer_1_vtx_0[1786];
extern Gfx mario_002_switch_option_face_e_mesh_layer_1_tri_0[];
extern Vtx mario_002_switch_option_face_e_mesh_layer_1_vtx_1[64];
extern Gfx mario_002_switch_option_face_e_mesh_layer_1_tri_1[];
extern Vtx mario_002_switch_option_face_e_mesh_layer_1_vtx_2[116];
extern Gfx mario_002_switch_option_face_e_mesh_layer_1_tri_2[];
extern Vtx mario_002_switch_option_face_e_mesh_layer_1_vtx_3[76];
extern Gfx mario_002_switch_option_face_e_mesh_layer_1_tri_3[];
extern Vtx mario_002_switch_option_face_e_mesh_layer_1_vtx_4[350];
extern Gfx mario_002_switch_option_face_e_mesh_layer_1_tri_4[];
extern Vtx mario_Left_Wing_DL_mesh_layer_1_vtx_0[457];
extern Gfx mario_Left_Wing_DL_mesh_layer_1_tri_0[];
extern Vtx mario_Right_Wing_DL_mesh_layer_1_vtx_0[456];
extern Gfx mario_Right_Wing_DL_mesh_layer_1_tri_0[];
extern Vtx mario_Left_Arm_Color_mesh_layer_1_vtx_0[1010];
extern Gfx mario_Left_Arm_Color_mesh_layer_1_tri_0[];
extern Vtx mario_Left_Forearm_mesh_layer_1_vtx_0[547];
extern Gfx mario_Left_Forearm_mesh_layer_1_tri_0[];
extern Vtx mario_Left_Forearm_mesh_layer_1_vtx_1[508];
extern Gfx mario_Left_Forearm_mesh_layer_1_tri_1[];
extern Vtx mario_Left_Hand_DL_mesh_layer_1_vtx_0[1371];
extern Gfx mario_Left_Hand_DL_mesh_layer_1_tri_0[];
extern Vtx mario_002_switch_option_left_hand_open_mesh_layer_1_vtx_0[1318];
extern Gfx mario_002_switch_option_left_hand_open_mesh_layer_1_tri_0[];
extern Vtx mario_Right_Arm_Color_mesh_layer_1_vtx_0[1010];
extern Gfx mario_Right_Arm_Color_mesh_layer_1_tri_0[];
extern Vtx mario_Right_Forearm_mesh_layer_1_vtx_0[547];
extern Gfx mario_Right_Forearm_mesh_layer_1_tri_0[];
extern Vtx mario_Right_Forearm_mesh_layer_1_vtx_1[504];
extern Gfx mario_Right_Forearm_mesh_layer_1_tri_1[];
extern Vtx mario_Right_Hand_DL_mesh_layer_1_vtx_0[1385];
extern Gfx mario_Right_Hand_DL_mesh_layer_1_tri_0[];
extern Vtx mario_002_switch_option_right_hand_open_mesh_layer_1_vtx_0[1305];
extern Gfx mario_002_switch_option_right_hand_open_mesh_layer_1_tri_0[];
extern Vtx mario_004_switch_option_right_hand_peace_mesh_layer_1_vtx_0[1329];
extern Gfx mario_004_switch_option_right_hand_peace_mesh_layer_1_tri_0[];
extern Vtx mario_005_switch_option_right_hand_cap_mesh_layer_1_vtx_0[1367];
extern Gfx mario_005_switch_option_right_hand_cap_mesh_layer_1_tri_0[];
extern Vtx mario_005_switch_option_right_hand_cap_mesh_layer_1_vtx_1[3706];
extern Gfx mario_005_switch_option_right_hand_cap_mesh_layer_1_tri_1[];
extern Vtx mario_005_switch_option_right_hand_cap_mesh_layer_1_vtx_2[1029];
extern Gfx mario_005_switch_option_right_hand_cap_mesh_layer_1_tri_2[];
extern Vtx mario_005_switch_option_right_hand_cap_mesh_layer_1_vtx_3[287];
extern Gfx mario_005_switch_option_right_hand_cap_mesh_layer_1_tri_3[];
extern Vtx mario_006_switch_option_right_hand_wing_cap_mesh_layer_1_vtx_0[1367];
extern Gfx mario_006_switch_option_right_hand_wing_cap_mesh_layer_1_tri_0[];
extern Vtx mario_006_switch_option_right_hand_wing_cap_mesh_layer_1_vtx_1[3706];
extern Gfx mario_006_switch_option_right_hand_wing_cap_mesh_layer_1_tri_1[];
extern Vtx mario_006_switch_option_right_hand_wing_cap_mesh_layer_1_vtx_2[1029];
extern Gfx mario_006_switch_option_right_hand_wing_cap_mesh_layer_1_tri_2[];
extern Vtx mario_006_switch_option_right_hand_wing_cap_mesh_layer_1_vtx_3[1194];
extern Gfx mario_006_switch_option_right_hand_wing_cap_mesh_layer_1_tri_3[];
extern Vtx mario_Left_Thigh_Color_mesh_layer_1_vtx_0[998];
extern Gfx mario_Left_Thigh_Color_mesh_layer_1_tri_0[];
extern Vtx mario_Left_Leg_mesh_layer_1_vtx_0[998];
extern Gfx mario_Left_Leg_mesh_layer_1_tri_0[];
extern Vtx mario_Left_Shoe_mesh_layer_1_vtx_0[955];
extern Gfx mario_Left_Shoe_mesh_layer_1_tri_0[];
extern Vtx mario_Left_Shoe_mesh_layer_1_vtx_1[1024];
extern Gfx mario_Left_Shoe_mesh_layer_1_tri_1[];
extern Vtx mario_Left_Shoe_mesh_layer_1_vtx_2[222];
extern Gfx mario_Left_Shoe_mesh_layer_1_tri_2[];
extern Vtx mario_Right_Thigh_Color_mesh_layer_1_vtx_0[998];
extern Gfx mario_Right_Thigh_Color_mesh_layer_1_tri_0[];
extern Vtx mario_Right_Leg_mesh_layer_1_vtx_0[998];
extern Gfx mario_Right_Leg_mesh_layer_1_tri_0[];
extern Vtx mario_Right_Shoe_mesh_layer_1_vtx_0[958];
extern Gfx mario_Right_Shoe_mesh_layer_1_tri_0[];
extern Vtx mario_Right_Shoe_DL_mesh_layer_1_vtx_0[1010];
extern Gfx mario_Right_Shoe_DL_mesh_layer_1_tri_0[];
extern Vtx mario_Right_Shoe_DL_mesh_layer_1_vtx_1[222];
extern Gfx mario_Right_Shoe_DL_mesh_layer_1_tri_1[];
extern Gfx mat_mario_mario_overalls[];
extern Gfx mat_revert_mario_mario_overalls[];
extern Gfx mat_mario_mario_buttons[];
extern Gfx mat_revert_mario_mario_buttons[];
extern Gfx mat_mario_mario_shirt[];
extern Gfx mat_revert_mario_mario_shirt[];
extern Gfx mat_mario_mario_teeth[];
extern Gfx mat_revert_mario_mario_teeth[];
extern Gfx mat_mario_mario_hair[];
extern Gfx mat_revert_mario_mario_hair[];
extern Gfx mat_mario_mario_mustache[];
extern Gfx mat_revert_mario_mario_mustache[];
extern Gfx mat_mario_mario_eye[];
extern Gfx mat_revert_mario_mario_eye[];
extern Gfx mat_mario_mario_skin[];
extern Gfx mat_revert_mario_mario_skin[];
extern Gfx mat_mario_mario_mouth[];
extern Gfx mat_revert_mario_mario_mouth[];
extern Gfx mat_mario_mario_tongue[];
extern Gfx mat_revert_mario_mario_tongue[];
extern Gfx mat_mario_mario_wings[];
extern Gfx mat_revert_mario_mario_wings[];
extern Gfx mat_mario_mario_gloves[];
extern Gfx mat_revert_mario_mario_gloves[];
extern Gfx mat_mario_mario_cap_inside[];
extern Gfx mat_revert_mario_mario_cap_inside[];
extern Gfx mat_mario_mario_shoes[];
extern Gfx mat_revert_mario_mario_shoes[];
extern Gfx mat_mario_mario_soles[];
extern Gfx mat_revert_mario_mario_soles[];
extern Gfx mat_mario_newmetal[];
extern Gfx mat_revert_mario_newmetal[];
extern Gfx mario_Torso_mesh_layer_1[];
extern Gfx mario_Torso_mesh_layer_1_opt_1[];
extern Gfx mario_Torso_mesh_layer_1_opt_2[];
extern Gfx mario_Torso_mesh_layer_1_opt_3[];
extern Gfx mario_Cap_DL_mesh_layer_1[];
extern Gfx mario_Cap_DL_mesh_layer_1_opt_2[];
extern Gfx mario_002_switch_option_head_hair_mesh_layer_1[];
extern Gfx mario_002_switch_option_head_hair_mesh_layer_1_opt_2[];
extern Gfx mario_Eyes_DL_mesh_layer_1[];
extern Gfx mario_Eyes_DL_mesh_layer_1_opt_2[];
extern Gfx mario_002_switch_option_eyes_half_closed_mesh_layer_1[];
extern Gfx mario_002_switch_option_eyes_half_closed_mesh_layer_1_opt_2[];
extern Gfx mario_002_switch_option_eyes_closed_mesh_layer_1[];
extern Gfx mario_002_switch_option_eyes_closed_mesh_layer_1_opt_2[];
extern Gfx mario_002_switch_option_eyes_half_open_mesh_layer_1[];
extern Gfx mario_002_switch_option_eyes_half_open_mesh_layer_1_opt_2[];
extern Gfx mario_002_switch_option_eyes_angry_mesh_layer_1[];
extern Gfx mario_002_switch_option_eyes_angry_mesh_layer_1_opt_2[];
extern Gfx mario_002_switch_option_eyes_happy_mesh_layer_1[];
extern Gfx mario_002_switch_option_eyes_happy_mesh_layer_1_opt_2[];
extern Gfx mario_002_switch_option_eyes_exhausted_mesh_layer_1[];
extern Gfx mario_002_switch_option_eyes_exhausted_mesh_layer_1_opt_2[];
extern Gfx mario_002_switch_option_eyes_dead_mesh_layer_1[];
extern Gfx mario_002_switch_option_eyes_dead_mesh_layer_1_opt_2[];
extern Gfx mario_002_switch_option_eyes_hurt_mesh_layer_1[];
extern Gfx mario_002_switch_option_eyes_hurt_mesh_layer_1_opt_2[];
extern Gfx mario_Face_DL_mesh_layer_1[];
extern Gfx mario_Face_DL_mesh_layer_1_opt_1[];
extern Gfx mario_Face_DL_mesh_layer_1_opt_2[];
extern Gfx mario_002_switch_option_face_happy_mesh_layer_1[];
extern Gfx mario_002_switch_option_face_happy_mesh_layer_1_opt_2[];
extern Gfx mario_002_switch_option_face_angry_mesh_layer_1[];
extern Gfx mario_002_switch_option_face_angry_mesh_layer_1_opt_2[];
extern Gfx mario_002_switch_option_face_o_mesh_layer_1[];
extern Gfx mario_002_switch_option_face_o_mesh_layer_1_opt_2[];
extern Gfx mario_002_switch_option_face_e_mesh_layer_1[];
extern Gfx mario_002_switch_option_face_e_mesh_layer_1_opt_2[];
extern Gfx mario_Left_Wing_DL_mesh_layer_1[];
extern Gfx mario_Left_Wing_DL_mesh_layer_1_opt_2[];
extern Gfx mario_Right_Wing_DL_mesh_layer_1[];
extern Gfx mario_Right_Wing_DL_mesh_layer_1_opt_2[];
extern Gfx mario_Left_Arm_Color_mesh_layer_1[];
extern Gfx mario_Left_Arm_Color_mesh_layer_1_opt_2[];
extern Gfx mario_Left_Forearm_mesh_layer_1[];
extern Gfx mario_Left_Forearm_mesh_layer_1_opt_2[];
extern Gfx mario_Left_Hand_DL_mesh_layer_1[];
extern Gfx mario_Left_Hand_DL_mesh_layer_1_opt_2[];
extern Gfx mario_002_switch_option_left_hand_open_mesh_layer_1[];
extern Gfx mario_002_switch_option_left_hand_open_mesh_layer_1_opt_2[];
extern Gfx mario_Right_Arm_Color_mesh_layer_1[];
extern Gfx mario_Right_Arm_Color_mesh_layer_1_opt_2[];
extern Gfx mario_Right_Forearm_mesh_layer_1[];
extern Gfx mario_Right_Forearm_mesh_layer_1_opt_2[];
extern Gfx mario_Right_Hand_DL_mesh_layer_1[];
extern Gfx mario_Right_Hand_DL_mesh_layer_1_opt_2[];
extern Gfx mario_002_switch_option_right_hand_open_mesh_layer_1[];
extern Gfx mario_002_switch_option_right_hand_open_mesh_layer_1_opt_2[];
extern Gfx mario_004_switch_option_right_hand_peace_mesh_layer_1[];
extern Gfx mario_004_switch_option_right_hand_peace_mesh_layer_1_opt_2[];
extern Gfx mario_005_switch_option_right_hand_cap_mesh_layer_1[];
extern Gfx mario_005_switch_option_right_hand_cap_mesh_layer_1_opt_2[];
extern Gfx mario_006_switch_option_right_hand_wing_cap_mesh_layer_1[];
extern Gfx mario_006_switch_option_right_hand_wing_cap_mesh_layer_1_opt_2[];
extern Gfx mario_Left_Thigh_Color_mesh_layer_1[];
extern Gfx mario_Left_Thigh_Color_mesh_layer_1_opt_2[];
extern Gfx mario_Left_Leg_mesh_layer_1[];
extern Gfx mario_Left_Leg_mesh_layer_1_opt_2[];
extern Gfx mario_Left_Shoe_mesh_layer_1[];
extern Gfx mario_Left_Shoe_mesh_layer_1_opt_2[];
extern Gfx mario_Right_Thigh_Color_mesh_layer_1[];
extern Gfx mario_Right_Thigh_Color_mesh_layer_1_opt_2[];
extern Gfx mario_Right_Leg_mesh_layer_1[];
extern Gfx mario_Right_Leg_mesh_layer_1_opt_2[];
extern Gfx mario_Right_Shoe_mesh_layer_1[];
extern Gfx mario_Right_Shoe_mesh_layer_1_opt_2[];
extern Gfx mario_Right_Shoe_DL_mesh_layer_1_with_layer_1_revert[];
extern Gfx mario_Right_Shoe_DL_mesh_layer_1_opt_2_with_layer_1_revert[];
extern Gfx mario_Right_Shoe_DL_mesh_layer_1_opt_3_with_layer_1_revert[];
extern Gfx mario_Right_Shoe_DL_mesh_layer_1_with_layer_5_revert[];
