const GeoLayout bowser_left_fist[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bowser_left_hand_switch_opt_left_hand_switch_opt_dl_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_left_hand_switch_opt_left_hand_switch_opt_dl_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bowser_right_fist[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bowser_right_hand_switch_opt_right_hand_switch_opt_dl_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_right_hand_switch_opt_right_hand_switch_opt_dl_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bowser_1_switch_opt1_jump_bowser_left_fist[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_left_hand_switch_opt_left_hand_switch_opt_dl_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_left_hand_switch_opt_left_hand_switch_opt_dl_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bowser_1_switch_opt1_jump_bowser_right_fist[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_right_hand_switch_opt_right_hand_switch_opt_dl_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_right_hand_switch_opt_right_hand_switch_opt_dl_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bowser_1_switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ASM(0, geo_function_bowser_color),
		GEO_SHADOW(0, 128, 400),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_OPAQUE, 16384),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 471, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 297, 235, 0, 0, -90, -180),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_left_thigh_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_left_thigh_mesh_layer_5),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 262, 0, bowser_left_shin_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_left_shin_mesh_layer_5),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 350, 0, 0, 180, -80),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_left_foot_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_left_foot_mesh_layer_5),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -297, 235, 0, 0, 90, 180),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_right_thigh_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_right_thigh_mesh_layer_5),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 262, 0, bowser_right_shin_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_right_shin_mesh_layer_5),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 350, 0, 0, -180, 80),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_right_foot_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_right_foot_mesh_layer_5),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 347, 0, 13, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_spine_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_spine_mesh_layer_5),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 569, 163, 17, 0, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_head_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_head_mesh_layer_5),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 387, -165, -109, 0, 0),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_function_bowser_hair),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_jaw_skinned_mesh_layer_1),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_jaw_skinned_mesh_layer_5),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 95, 127, 96, 0, 0),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_jaw_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_jaw_mesh_layer_5),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_jaw_lower_skinned_mesh_layer_1),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_jaw_lower_skinned_mesh_layer_5),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 143, 0, -7, 0, 0),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_jaw_lower_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_jaw_lower_mesh_layer_5),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 76, 372, 112, -60, 180, 0),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_function_bowser_left_eye),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, 0, 0, 0),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_left_eye_mesh_layer_1),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_left_eye_mesh_layer_5),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 76, 372, 112, -60, 180, 0),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_function_bowser_left_eyelid),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, 0, 0, 0),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_left_eyelid_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_left_eyelid_mesh_layer_5),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -76, 372, 112, -60, -180, 0),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_function_bowser_right_eye),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, 0, 0, 0),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_right_eye_mesh_layer_1),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_right_eye_mesh_layer_5),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -76, 372, 112, -60, 180, 0),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_function_bowser_right_eyelid),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, 0, 0, 0),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_right_eyelid_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_right_eyelid_mesh_layer_5),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 366, 451, 147, 0, -4, -89),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_left_shoulder_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_left_shoulder_mesh_layer_5),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 326, 0, 2, 0, -2),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_left_arm_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_left_arm_mesh_layer_5),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 155, 0, -6, 0, 1),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_SWITCH_CASE(1, geo_function_bowser_left_hand),
														GEO_OPEN_NODE(),
															GEO_NODE_START(),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_left_hand_dl_mesh_layer_1),
																GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_left_hand_dl_mesh_layer_5),
															GEO_CLOSE_NODE(),
															GEO_BRANCH(1, bowser_1_switch_opt1_jump_bowser_left_fist),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -366, 451, 147, 0, 4, 89),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_right_shoulder_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_right_shoulder_mesh_layer_5),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 326, 0, 2, 0, 2),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_right_arm_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_right_arm_mesh_layer_5),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 155, 0, -6, 0, -1),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_SWITCH_CASE(1, geo_function_bowser_right_hand),
														GEO_OPEN_NODE(),
															GEO_NODE_START(),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_right_hand_dl_mesh_layer_1),
																GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_right_hand_dl_mesh_layer_5),
															GEO_CLOSE_NODE(),
															GEO_BRANCH(1, bowser_1_switch_opt1_jump_bowser_right_fist),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 108, -210, -82, 0, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_shell_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_shell_mesh_layer_5),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_tail_dl_skinned_mesh_layer_1),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_tail_dl_skinned_mesh_layer_5),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, -338, -7, -157, 0, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_tail_dl_mesh_layer_1),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_tail_dl_mesh_layer_5),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 820, 1, 143, 0, 0),
										GEO_OPEN_NODE(),
											GEO_ASM(0, geo_update_body_rot_from_parent),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bowser_1_switch_opt2_jump_bowser_left_fist[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_left_hand_switch_opt_left_hand_switch_opt_dl_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_left_hand_switch_opt_left_hand_switch_opt_dl_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bowser_1_switch_opt2_jump_bowser_right_fist[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_right_hand_switch_opt_right_hand_switch_opt_dl_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_right_hand_switch_opt_right_hand_switch_opt_dl_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bowser_1_switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ASM(0, geo_function_bowser_color),
		GEO_SHADOW(0, 128, 400),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_OPAQUE, 16384),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 471, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 297, 235, 0, 0, -90, -180),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_left_thigh_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_left_thigh_mesh_layer_5),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 262, 0, bowser_left_shin_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_left_shin_mesh_layer_5),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 350, 0, 0, 180, -80),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_left_foot_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_left_foot_mesh_layer_5),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -297, 235, 0, 0, 90, 180),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_right_thigh_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_right_thigh_mesh_layer_5),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 262, 0, bowser_right_shin_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_right_shin_mesh_layer_5),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 350, 0, 0, -180, 80),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_right_foot_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_right_foot_mesh_layer_5),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 347, 0, 13, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_spine_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_spine_mesh_layer_5),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 569, 163, 17, 0, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_head_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_head_mesh_layer_5),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 387, -165, -109, 0, 0),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_function_bowser_hair),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_jaw_skinned_mesh_layer_1),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_jaw_skinned_mesh_layer_5),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 95, 127, 96, 0, 0),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_jaw_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_jaw_mesh_layer_5),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_jaw_lower_skinned_mesh_layer_1),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_jaw_lower_skinned_mesh_layer_5),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 143, 0, -7, 0, 0),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_jaw_lower_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_jaw_lower_mesh_layer_5),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 76, 372, 112, -60, 180, 0),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_function_bowser_left_eye),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, 0, 0, 0),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_left_eye_mesh_layer_1),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_left_eye_mesh_layer_5),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 76, 372, 112, -60, 180, 0),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_function_bowser_left_eyelid),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, 0, 0, 0),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_left_eyelid_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_left_eyelid_mesh_layer_5),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -76, 372, 112, -60, -180, 0),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_function_bowser_right_eye),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, 0, 0, 0),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_right_eye_mesh_layer_1),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_right_eye_mesh_layer_5),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -76, 372, 112, -60, 180, 0),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_function_bowser_right_eyelid),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, 0, 0, 0),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_right_eyelid_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_right_eyelid_mesh_layer_5),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 366, 451, 147, 0, -4, -89),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_left_shoulder_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_left_shoulder_mesh_layer_5),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 326, 0, 2, 0, -2),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_left_arm_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_left_arm_mesh_layer_5),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 155, 0, -6, 0, 1),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_SWITCH_CASE(1, geo_function_bowser_left_hand),
														GEO_OPEN_NODE(),
															GEO_NODE_START(),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_left_hand_dl_mesh_layer_1),
																GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_left_hand_dl_mesh_layer_5),
															GEO_CLOSE_NODE(),
															GEO_BRANCH(1, bowser_1_switch_opt2_jump_bowser_left_fist),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -366, 451, 147, 0, 4, 89),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_right_shoulder_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_right_shoulder_mesh_layer_5),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 326, 0, 2, 0, 2),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_right_arm_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_right_arm_mesh_layer_5),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 155, 0, -6, 0, -1),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_SWITCH_CASE(1, geo_function_bowser_right_hand),
														GEO_OPEN_NODE(),
															GEO_NODE_START(),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_right_hand_dl_mesh_layer_1),
																GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_right_hand_dl_mesh_layer_5),
															GEO_CLOSE_NODE(),
															GEO_BRANCH(1, bowser_1_switch_opt2_jump_bowser_right_fist),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 108, -210, -82, 0, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, bowser_shell_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_shell_mesh_layer_5),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_tail_dl_skinned_mesh_layer_1),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_tail_dl_skinned_mesh_layer_5),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, -338, -7, -157, 0, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_tail_dl_mesh_layer_1),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_tail_dl_mesh_layer_5),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 820, 1, 143, 0, 0),
										GEO_OPEN_NODE(),
											GEO_ASM(0, geo_update_body_rot_from_parent),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bowser_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_NODE_START(),
		GEO_OPEN_NODE(),
			GEO_ASM(0, geo_update_layer_transparency),
			GEO_SWITCH_CASE(3, geo_switch_anim_state),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_ASM(0, geo_function_bowser_color),
					GEO_SHADOW(0, 128, 400),
					GEO_OPEN_NODE(),
						GEO_SCALE(LAYER_OPAQUE, 16384),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 471, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 297, 235, 0, 0, -90, -180),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_left_thigh_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_left_thigh_mesh_layer_5),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 262, 0, bowser_left_shin_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_left_shin_mesh_layer_5),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 350, 0, 0, 180, -80),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_left_foot_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_left_foot_mesh_layer_5),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -297, 235, 0, 0, 90, 180),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_right_thigh_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_right_thigh_mesh_layer_5),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 262, 0, bowser_right_shin_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_right_shin_mesh_layer_5),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 350, 0, 0, -180, 80),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_right_foot_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_right_foot_mesh_layer_5),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 347, 0, 13, 0, 0),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_spine_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_spine_mesh_layer_5),
											GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 569, 163, 17, 0, 0),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_head_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_head_mesh_layer_5),
													GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 387, -165, -109, 0, 0),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
														GEO_OPEN_NODE(),
															GEO_ASM(0, geo_function_bowser_hair),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, bowser_jaw_skinned_mesh_layer_1),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_jaw_skinned_mesh_layer_5),
													GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 95, 127, 96, 0, 0),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_jaw_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_jaw_mesh_layer_5),
															GEO_DISPLAY_LIST(LAYER_OPAQUE, bowser_jaw_lower_skinned_mesh_layer_1),
															GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_jaw_lower_skinned_mesh_layer_5),
															GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 143, 0, -7, 0, 0),
															GEO_OPEN_NODE(),
																GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_jaw_lower_mesh_layer_1),
																GEO_OPEN_NODE(),
																	GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_jaw_lower_mesh_layer_5),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
													GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 76, 372, 112, -60, 180, 0),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
														GEO_OPEN_NODE(),
															GEO_ASM(1, geo_function_bowser_left_eye),
															GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, 0, 0, 0),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_OPAQUE, bowser_left_eye_mesh_layer_1),
																GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_left_eye_mesh_layer_5),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
													GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 76, 372, 112, -60, 180, 0),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
														GEO_OPEN_NODE(),
															GEO_ASM(0, geo_function_bowser_left_eyelid),
															GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, 0, 0, 0),
															GEO_OPEN_NODE(),
																GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_left_eyelid_mesh_layer_1),
																GEO_OPEN_NODE(),
																	GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_left_eyelid_mesh_layer_5),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
													GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -76, 372, 112, -60, -180, 0),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
														GEO_OPEN_NODE(),
															GEO_ASM(1, geo_function_bowser_right_eye),
															GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, 0, 0, 0),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_OPAQUE, bowser_right_eye_mesh_layer_1),
																GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_right_eye_mesh_layer_5),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
													GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -76, 372, 112, -60, 180, 0),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
														GEO_OPEN_NODE(),
															GEO_ASM(0, geo_function_bowser_right_eyelid),
															GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, 0, 0, 0),
															GEO_OPEN_NODE(),
																GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_right_eyelid_mesh_layer_1),
																GEO_OPEN_NODE(),
																	GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_right_eyelid_mesh_layer_5),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 366, 451, 147, 0, -4, -89),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_left_shoulder_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_left_shoulder_mesh_layer_5),
													GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 326, 0, 2, 0, -2),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_left_arm_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_left_arm_mesh_layer_5),
															GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 155, 0, -6, 0, 1),
															GEO_OPEN_NODE(),
																GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
																GEO_OPEN_NODE(),
																	GEO_SWITCH_CASE(1, geo_function_bowser_left_hand),
																	GEO_OPEN_NODE(),
																		GEO_NODE_START(),
																		GEO_OPEN_NODE(),
																			GEO_DISPLAY_LIST(LAYER_OPAQUE, bowser_left_hand_dl_mesh_layer_1),
																			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_left_hand_dl_mesh_layer_5),
																		GEO_CLOSE_NODE(),
																		GEO_BRANCH(1, bowser_left_fist),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -366, 451, 147, 0, 4, 89),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_right_shoulder_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_right_shoulder_mesh_layer_5),
													GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 326, 0, 2, 0, 2),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_right_arm_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_right_arm_mesh_layer_5),
															GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 155, 0, -6, 0, -1),
															GEO_OPEN_NODE(),
																GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
																GEO_OPEN_NODE(),
																	GEO_SWITCH_CASE(1, geo_function_bowser_right_hand),
																	GEO_OPEN_NODE(),
																		GEO_NODE_START(),
																		GEO_OPEN_NODE(),
																			GEO_DISPLAY_LIST(LAYER_OPAQUE, bowser_right_hand_dl_mesh_layer_1),
																			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_right_hand_dl_mesh_layer_5),
																		GEO_CLOSE_NODE(),
																		GEO_BRANCH(1, bowser_right_fist),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 108, -210, -82, 0, 0),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bowser_shell_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_shell_mesh_layer_5),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, bowser_tail_dl_skinned_mesh_layer_1),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_tail_dl_skinned_mesh_layer_5),
											GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, -338, -7, -157, 0, 0),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, bowser_tail_dl_mesh_layer_1),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_tail_dl_mesh_layer_5),
													GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 820, 1, 143, 0, 0),
													GEO_OPEN_NODE(),
														GEO_ASM(0, geo_update_body_rot_from_parent),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_BRANCH(1, bowser_1_switch_opt1),
				GEO_BRANCH(1, bowser_1_switch_opt2),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bowser_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_material_revert_render_settings),
	    GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bowser_fix_transparency_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
