const GeoLayout whomp_king_switchcrack_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, whomp_king_000_offset_mesh_layer_1_mat_override_whomp_crack2_0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, whomp_king_000_offset_mesh_layer_5_mat_override_whomp_crack2_0),
			GEO_ANIMATED_PART(LAYER_OPAQUE, -12, 490, -5, NULL),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, whomp_king_000_offset_002_mesh_layer_1_mat_override_whomp_crack2_0),
			GEO_CLOSE_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, -12, -479, -69, NULL),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, whomp_king_000_offset_003_mesh_layer_1_mat_override_whomp_crack2_0),
			GEO_CLOSE_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 947, 612, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, whomp_king_000_offset_004_mesh_layer_1_mat_override_whomp_crack2_0),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT, whomp_king_000_offset_004_mesh_layer_5_mat_override_whomp_crack2_0),
					GEO_ANIMATED_PART(LAYER_ALPHA, 400, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_BILLBOARD_WITH_PARAMS(LAYER_FORCE, 0, 0, 0),
						GEO_OPEN_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 940, -574, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, whomp_king_000_offset_006_mesh_layer_1_mat_override_whomp_crack2_0),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT, whomp_king_000_offset_006_mesh_layer_5_mat_override_whomp_crack2_0),
					GEO_ANIMATED_PART(LAYER_ALPHA, 400, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_BILLBOARD_WITH_PARAMS(LAYER_FORCE, 0, 0, 0),
						GEO_OPEN_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout whomp_king_switchcrack_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, whomp_king_000_offset_mesh_layer_1_mat_override_whomp_crack3_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, whomp_king_000_offset_mesh_layer_5_mat_override_whomp_crack3_1),
			GEO_ANIMATED_PART(LAYER_OPAQUE, -12, 490, -5, NULL),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, whomp_king_000_offset_002_mesh_layer_1_mat_override_whomp_crack3_1),
			GEO_CLOSE_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, -12, -479, -69, NULL),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, whomp_king_000_offset_003_mesh_layer_1_mat_override_whomp_crack3_1),
			GEO_CLOSE_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 947, 612, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, whomp_king_000_offset_004_mesh_layer_1_mat_override_whomp_crack3_1),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT, whomp_king_000_offset_004_mesh_layer_5_mat_override_whomp_crack3_1),
					GEO_ANIMATED_PART(LAYER_ALPHA, 400, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_BILLBOARD_WITH_PARAMS(LAYER_FORCE, 0, 0, 0),
						GEO_OPEN_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 940, -574, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, whomp_king_000_offset_006_mesh_layer_1_mat_override_whomp_crack3_1),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT, whomp_king_000_offset_006_mesh_layer_5_mat_override_whomp_crack3_1),
					GEO_ANIMATED_PART(LAYER_ALPHA, 400, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_BILLBOARD_WITH_PARAMS(LAYER_FORCE, 0, 0, 0),
						GEO_OPEN_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout whomp_king_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(50, 181, 5),
		GEO_OPEN_NODE(),
			GEO_TRANSLATE_NODE(LAYER_FORCE, 0, 0, -50),
			GEO_OPEN_NODE(),
				GEO_SCALE(LAYER_FORCE, 16384),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_SWITCH_CASE(2, geo_switch_state_1),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, whomp_king_000_offset_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, whomp_king_000_offset_mesh_layer_5),
									GEO_ANIMATED_PART(LAYER_OPAQUE, -12, 490, -5, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, whomp_king_000_offset_002_mesh_layer_1),
									GEO_CLOSE_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, -12, -479, -69, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, whomp_king_000_offset_003_mesh_layer_1),
									GEO_CLOSE_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 947, 612, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, whomp_king_000_offset_004_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, whomp_king_000_offset_004_mesh_layer_5),
											GEO_ANIMATED_PART(LAYER_ALPHA, 400, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_BILLBOARD_WITH_PARAMS(LAYER_FORCE, 0, 0, 0),
												GEO_OPEN_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 940, -574, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, whomp_king_000_offset_006_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, whomp_king_000_offset_006_mesh_layer_5),
											GEO_ANIMATED_PART(LAYER_ALPHA, 400, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_BILLBOARD_WITH_PARAMS(LAYER_FORCE, 0, 0, 0),
												GEO_OPEN_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, whomp_king_switchcrack_opt1),
							GEO_BRANCH(1, whomp_king_switchcrack_opt2),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
