extern const GeoLayout bowser_2_area_1_geo[];
extern const GeoLayout bowser_2_area_1[];
extern const Collision bowser_2_area_1_collision[];
extern const MacroObject bowser_2_area_1_macro_objs[];
extern Lights1 bowser_2_dl_arena_walls_lights;
extern Lights1 bowser_2_dl_arena_walls4_lights;
extern Lights1 bowser_2_dl_arena_ball_lights;
extern Lights1 bowser_2_dl_arena_ball_shine_lights;
extern Lights1 bowser_2_dl_arena_lava_lights;
extern u8 bowser_2_dl_arena_walls_rgba32[];
extern u8 bowser_2_dl_arena_walls4_rgba32[];
extern u8 bowser_2_dl_arena_ball_rgba32[];
extern u8 bowser_2_dl_shine_dull_transparent_rgba32[];
extern Vtx bowser_2_dl_bowser_2_environment_mesh_layer_1_vtx_cull[8];
extern Vtx bowser_2_dl_bowser_2_environment_mesh_layer_1_vtx_0[3196];
extern Gfx bowser_2_dl_bowser_2_environment_mesh_layer_1_tri_0[];
extern Vtx bowser_2_dl_bowser_2_environment_mesh_layer_1_vtx_1[959];
extern Gfx bowser_2_dl_bowser_2_environment_mesh_layer_1_tri_1[];
extern Vtx bowser_2_dl_bowser_2_environment_mesh_layer_1_vtx_2[1003];
extern Gfx bowser_2_dl_bowser_2_environment_mesh_layer_1_tri_2[];
extern Vtx bowser_2_dl_bowser_2_environment_mesh_layer_1_vtx_3[4];
extern Gfx bowser_2_dl_bowser_2_environment_mesh_layer_1_tri_3[];
extern Vtx bowser_2_dl_bowser_2_environment_mesh_layer_5_vtx_cull[8];
extern Vtx bowser_2_dl_bowser_2_environment_mesh_layer_5_vtx_0[252];
extern Gfx bowser_2_dl_bowser_2_environment_mesh_layer_5_tri_0[];
extern Gfx mat_bowser_2_dl_arena_walls[];
extern Gfx mat_revert_bowser_2_dl_arena_walls[];
extern Gfx mat_bowser_2_dl_arena_walls4[];
extern Gfx mat_revert_bowser_2_dl_arena_walls4[];
extern Gfx mat_bowser_2_dl_arena_ball[];
extern Gfx mat_revert_bowser_2_dl_arena_ball[];
extern Gfx mat_bowser_2_dl_arena_ball_shine[];
extern Gfx mat_revert_bowser_2_dl_arena_ball_shine[];
extern Gfx mat_bowser_2_dl_arena_lava[];
extern Gfx mat_revert_bowser_2_dl_arena_lava[];
extern Gfx bowser_2_dl_bowser_2_environment_mesh_layer_1[];
extern Gfx bowser_2_dl_bowser_2_environment_mesh_layer_5[];
