extern const GeoLayout mr_i_almost_open[];
extern const GeoLayout mr_i_half_open[];
extern const GeoLayout mr_i_almost_closed[];
extern const GeoLayout mr_i_closed[];
extern const GeoLayout mr_i_geo[];
extern Lights1 mr_i_mr_i_eyeball_white_lights;
extern Lights1 mr_i_mr_i_eyeball_black_lights;
extern Lights1 mr_i_mr_i_eyeball_blue_lights;
extern u8 mr_i_shine_dull_rgba32[];
extern u8 mr_i_shine_shiny_rgba32[];
extern Vtx mr_i_000_displaylist_mesh_layer_4_vtx_0[1196];
extern Gfx mr_i_000_displaylist_mesh_layer_4_tri_0[];
extern Vtx mr_i_000_displaylist_mesh_layer_4_vtx_1[488];
extern Gfx mr_i_000_displaylist_mesh_layer_4_tri_1[];
extern Vtx mr_i_000_displaylist_mesh_layer_1_vtx_0[355];
extern Gfx mr_i_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx mr_i_000_switch_almost_open_mesh_layer_4_vtx_0[1196];
extern Gfx mr_i_000_switch_almost_open_mesh_layer_4_tri_0[];
extern Vtx mr_i_000_switch_almost_open_mesh_layer_4_vtx_1[422];
extern Gfx mr_i_000_switch_almost_open_mesh_layer_4_tri_1[];
extern Vtx mr_i_000_switch_almost_open_mesh_layer_1_vtx_0[382];
extern Gfx mr_i_000_switch_almost_open_mesh_layer_1_tri_0[];
extern Vtx mr_i_000_switch_half_open_mesh_layer_4_vtx_0[688];
extern Gfx mr_i_000_switch_half_open_mesh_layer_4_tri_0[];
extern Vtx mr_i_000_switch_half_open_mesh_layer_4_vtx_1[227];
extern Gfx mr_i_000_switch_half_open_mesh_layer_4_tri_1[];
extern Vtx mr_i_000_switch_half_open_mesh_layer_1_vtx_0[230];
extern Gfx mr_i_000_switch_half_open_mesh_layer_1_tri_0[];
extern Vtx mr_i_000_switch_almost_closed_mesh_layer_4_vtx_0[688];
extern Gfx mr_i_000_switch_almost_closed_mesh_layer_4_tri_0[];
extern Vtx mr_i_000_switch_almost_closed_mesh_layer_4_vtx_1[123];
extern Gfx mr_i_000_switch_almost_closed_mesh_layer_4_tri_1[];
extern Vtx mr_i_000_switch_almost_closed_mesh_layer_1_vtx_0[159];
extern Gfx mr_i_000_switch_almost_closed_mesh_layer_1_tri_0[];
extern Vtx mr_i_000_switch_closed_mesh_layer_4_vtx_0[688];
extern Gfx mr_i_000_switch_closed_mesh_layer_4_tri_0[];
extern Vtx mr_i_000_switch_closed_mesh_layer_4_vtx_1[111];
extern Gfx mr_i_000_switch_closed_mesh_layer_4_tri_1[];
extern Gfx mat_mr_i_mr_i_eyeball_white[];
extern Gfx mat_revert_mr_i_mr_i_eyeball_white[];
extern Gfx mat_mr_i_mr_i_eyeball_black[];
extern Gfx mat_revert_mr_i_mr_i_eyeball_black[];
extern Gfx mat_mr_i_mr_i_eyeball_blue[];
extern Gfx mat_revert_mr_i_mr_i_eyeball_blue[];
extern Gfx mr_i_000_displaylist_mesh_layer_4[];
extern Gfx mr_i_000_displaylist_mesh_layer_1[];
extern Gfx mr_i_000_switch_almost_open_mesh_layer_4[];
extern Gfx mr_i_000_switch_almost_open_mesh_layer_1[];
extern Gfx mr_i_000_switch_half_open_mesh_layer_4[];
extern Gfx mr_i_000_switch_half_open_mesh_layer_1[];
extern Gfx mr_i_000_switch_almost_closed_mesh_layer_4[];
extern Gfx mr_i_000_switch_almost_closed_mesh_layer_1[];
extern Gfx mr_i_000_switch_closed_mesh_layer_4[];
