const GeoLayout boo_booframe1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, boo_001_switchmesh_frame1_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout boo_booframe2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, boo_001_switchmesh_frame2_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout boo_booframe3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, boo_001_switchmesh_frame3_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, boo_001_switchmesh_frame3_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout boo_booframe4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, boo_001_switch_frame4_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, boo_001_switch_frame4_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout boo_001_switch_opt1_jump_boo_booframe1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, boo_001_switchmesh_frame1_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout boo_001_switch_opt1_jump_boo_booframe2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, boo_001_switchmesh_frame2_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout boo_001_switch_opt1_jump_boo_booframe3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, boo_001_switchmesh_frame3_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, boo_001_switchmesh_frame3_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout boo_001_switch_opt1_jump_boo_booframe4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, boo_001_switch_frame4_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, boo_001_switch_frame4_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout boo_001_switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(4, geo_switch_state_2),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, boo_000_displaylist_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, boo_001_switch_opt1_jump_boo_booframe1),
			GEO_BRANCH(1, boo_001_switch_opt1_jump_boo_booframe2),
			GEO_BRANCH(1, boo_001_switch_opt1_jump_boo_booframe3),
			GEO_BRANCH(1, boo_001_switch_opt1_jump_boo_booframe4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout boo_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_RENDER_RANGE(-2048, 4000),
		GEO_OPEN_NODE(),
			GEO_SHADOW(0, 150, 70),
			GEO_OPEN_NODE(),
				GEO_SCALE(LAYER_FORCE, 26214),
				GEO_OPEN_NODE(),
					GEO_SCALE(LAYER_FORCE, 16384),
					GEO_OPEN_NODE(),
						GEO_ASM(0, geo_update_layer_transparency),
						GEO_SWITCH_CASE(2, geo_switch_anim_state),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(4, geo_switch_state_2),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, boo_000_displaylist_mesh_layer_1),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, boo_booframe1),
									GEO_BRANCH(1, boo_booframe2),
									GEO_BRANCH(1, boo_booframe3),
									GEO_BRANCH(1, boo_booframe4),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, boo_001_switch_opt1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_RENDER_RANGE(4000, 32000),
		GEO_OPEN_NODE(),
			GEO_BRANCH(1, boo_low_poly_geo),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mat_revert_boo_boo),
	GEO_CLOSE_NODE(),
	GEO_END(),
};


