extern const GeoLayout boo_booframe1[];
extern const GeoLayout boo_booframe2[];
extern const GeoLayout boo_booframe3[];
extern const GeoLayout boo_booframe4[];
extern const GeoLayout boo_001_switch_opt1_jump_boo_booframe1[];
extern const GeoLayout boo_001_switch_opt1_jump_boo_booframe2[];
extern const GeoLayout boo_001_switch_opt1_jump_boo_booframe3[];
extern const GeoLayout boo_001_switch_opt1_jump_boo_booframe4[];
extern const GeoLayout boo_001_switch_opt1[];
extern const GeoLayout boo_geo[];
extern Lights1 boo_boo_body_lights;
extern Lights1 boo_boo_mouth_lights;
extern Lights1 boo_boo_eyes_lights;
extern Lights1 boo_boo_teeth_lights;
extern Lights1 boo_boo_blush_layer5_lights;
extern Lights1 boo_boo_blush_more_layer5_lights;
extern u8 boo_shine_dull_rgba32[];
extern u8 boo_boo_eye_blush_rgba32[];
extern u8 boo_boo_eye_blush_more_rgba32[];
extern Vtx boo_000_displaylist_mesh_layer_1_vtx_0[2838];
extern Gfx boo_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx boo_000_displaylist_mesh_layer_1_vtx_1[224];
extern Gfx boo_000_displaylist_mesh_layer_1_tri_1[];
extern Vtx boo_000_displaylist_mesh_layer_1_vtx_2[1036];
extern Gfx boo_000_displaylist_mesh_layer_1_tri_2[];
extern Vtx boo_000_displaylist_mesh_layer_1_vtx_3[558];
extern Gfx boo_000_displaylist_mesh_layer_1_tri_3[];
extern Vtx boo_001_switchmesh_frame1_mesh_layer_1_vtx_0[2236];
extern Gfx boo_001_switchmesh_frame1_mesh_layer_1_tri_0[];
extern Vtx boo_001_switchmesh_frame1_mesh_layer_1_vtx_1[224];
extern Gfx boo_001_switchmesh_frame1_mesh_layer_1_tri_1[];
extern Vtx boo_001_switchmesh_frame1_mesh_layer_1_vtx_2[1036];
extern Gfx boo_001_switchmesh_frame1_mesh_layer_1_tri_2[];
extern Vtx boo_001_switchmesh_frame1_mesh_layer_1_vtx_3[558];
extern Gfx boo_001_switchmesh_frame1_mesh_layer_1_tri_3[];
extern Vtx boo_001_switchmesh_frame2_mesh_layer_1_vtx_0[2236];
extern Gfx boo_001_switchmesh_frame2_mesh_layer_1_tri_0[];
extern Vtx boo_001_switchmesh_frame2_mesh_layer_1_vtx_1[224];
extern Gfx boo_001_switchmesh_frame2_mesh_layer_1_tri_1[];
extern Vtx boo_001_switchmesh_frame2_mesh_layer_1_vtx_2[1036];
extern Gfx boo_001_switchmesh_frame2_mesh_layer_1_tri_2[];
extern Vtx boo_001_switchmesh_frame3_mesh_layer_1_vtx_0[2751];
extern Gfx boo_001_switchmesh_frame3_mesh_layer_1_tri_0[];
extern Vtx boo_001_switchmesh_frame3_mesh_layer_1_vtx_1[914];
extern Gfx boo_001_switchmesh_frame3_mesh_layer_1_tri_1[];
extern Vtx boo_001_switchmesh_frame3_mesh_layer_1_vtx_2[68];
extern Gfx boo_001_switchmesh_frame3_mesh_layer_1_tri_2[];
extern Vtx boo_001_switchmesh_frame3_mesh_layer_5_vtx_0[243];
extern Gfx boo_001_switchmesh_frame3_mesh_layer_5_tri_0[];
extern Vtx boo_001_switch_frame4_mesh_layer_1_vtx_0[2750];
extern Gfx boo_001_switch_frame4_mesh_layer_1_tri_0[];
extern Vtx boo_001_switch_frame4_mesh_layer_1_vtx_1[55];
extern Gfx boo_001_switch_frame4_mesh_layer_1_tri_1[];
extern Vtx boo_001_switch_frame4_mesh_layer_1_vtx_2[126];
extern Gfx boo_001_switch_frame4_mesh_layer_1_tri_2[];
extern Vtx boo_001_switch_frame4_mesh_layer_5_vtx_0[243];
extern Gfx boo_001_switch_frame4_mesh_layer_5_tri_0[];
extern Gfx mat_boo_boo_body[];
extern Gfx mat_revert_boo_boo_body[];
extern Gfx mat_boo_boo_mouth[];
extern Gfx mat_revert_boo_boo_mouth[];
extern Gfx mat_boo_boo_eyes[];
extern Gfx mat_revert_boo_boo_eyes[];
extern Gfx mat_boo_boo_teeth[];
extern Gfx mat_revert_boo_boo_teeth[];
extern Gfx mat_boo_boo_blush_layer5[];
extern Gfx mat_revert_boo_boo_blush_layer5[];
extern Gfx mat_boo_boo_blush_more_layer5[];
extern Gfx mat_revert_boo_boo_blush_more_layer5[];
extern Gfx boo_000_displaylist_mesh_layer_1[];
extern Gfx boo_001_switchmesh_frame1_mesh_layer_1[];
extern Gfx boo_001_switchmesh_frame2_mesh_layer_1[];
extern Gfx boo_001_switchmesh_frame3_mesh_layer_1[];
extern Gfx boo_001_switchmesh_frame3_mesh_layer_5[];
extern Gfx boo_001_switch_frame4_mesh_layer_1[];
extern Gfx boo_001_switch_frame4_mesh_layer_5[];
