extern const GeoLayout luigi_head_capless[];
extern const GeoLayout luigi_eyes_half_closed[];
extern const GeoLayout luigi_eyes_closed[];
extern const GeoLayout luigi_eyes_tiptoe[];
extern const GeoLayout luigi_eyes_angry[];
extern const GeoLayout luigi_eyes_happy[];
extern const GeoLayout luigi_eyes_exhausted[];
extern const GeoLayout luigi_eyes_dead[];
extern const GeoLayout luigi_eyes_hurt[];
extern const GeoLayout luigi_face_happy[];
extern const GeoLayout luigi_face_angry[];
extern const GeoLayout luigi_face_O[];
extern const GeoLayout luigi_left_hand_open[];
extern const GeoLayout luigi_right_hand_open[];
extern const GeoLayout luigi_right_hand_peace[];
extern const GeoLayout luigi_right_hand_cap[];
extern const GeoLayout luigi_right_hand_wing_cap[];
extern const GeoLayout luigi_geo_opt_1[];
extern const GeoLayout luigi_geo_opt_2[];
extern const GeoLayout luigi_head_capless_opt_1[];
extern const GeoLayout luigi_eyes_half_closed_opt_1[];
extern const GeoLayout luigi_eyes_closed_opt_1[];
extern const GeoLayout luigi_eyes_tiptoe_opt_1[];
extern const GeoLayout luigi_eyes_angry_opt_1[];
extern const GeoLayout luigi_eyes_happy_opt_1[];
extern const GeoLayout luigi_eyes_exhausted_opt_1[];
extern const GeoLayout luigi_eyes_dead_opt_1[];
extern const GeoLayout luigi_eyes_hurt_opt_1[];
extern const GeoLayout luigi_geo_opt_1_1_opt_1_opt_1[];
extern const GeoLayout luigi_geo_opt_1_1_opt_1_opt_2[];
extern const GeoLayout luigi_face_happy_opt_1[];
extern const GeoLayout luigi_face_angry_opt_1[];
extern const GeoLayout luigi_face_O_opt_1[];
extern const GeoLayout luigi_left_hand_open_opt_1[];
extern const GeoLayout luigi_right_hand_open_opt_1[];
extern const GeoLayout luigi_right_hand_peace_opt_1[];
extern const GeoLayout luigi_right_hand_cap_opt_1[];
extern const GeoLayout luigi_right_hand_wing_cap_opt_1[];
extern const GeoLayout luigi_geo_opt_1_1[];
extern const GeoLayout luigi_head_capless_opt_2[];
extern const GeoLayout luigi_eyes_half_closed_opt_2[];
extern const GeoLayout luigi_eyes_closed_opt_2[];
extern const GeoLayout luigi_eyes_tiptoe_opt_2[];
extern const GeoLayout luigi_eyes_angry_opt_2[];
extern const GeoLayout luigi_eyes_happy_opt_2[];
extern const GeoLayout luigi_eyes_exhausted_opt_2[];
extern const GeoLayout luigi_eyes_dead_opt_2[];
extern const GeoLayout luigi_eyes_hurt_opt_2[];
extern const GeoLayout luigi_geo_opt_2_1_opt_2_opt_1[];
extern const GeoLayout luigi_geo_opt_2_1_opt_2_opt_2[];
extern const GeoLayout luigi_face_happy_opt_2[];
extern const GeoLayout luigi_face_angry_opt_2[];
extern const GeoLayout luigi_face_O_opt_2[];
extern const GeoLayout luigi_left_hand_open_opt_2[];
extern const GeoLayout luigi_right_hand_open_opt_2[];
extern const GeoLayout luigi_right_hand_peace_opt_2[];
extern const GeoLayout luigi_right_hand_cap_opt_2[];
extern const GeoLayout luigi_right_hand_wing_cap_opt_2[];
extern const GeoLayout luigi_geo_opt_2_1[];
extern const GeoLayout luigi_head_capless_opt_3[];
extern const GeoLayout luigi_eyes_half_closed_opt_3[];
extern const GeoLayout luigi_eyes_closed_opt_3[];
extern const GeoLayout luigi_eyes_tiptoe_opt_3[];
extern const GeoLayout luigi_eyes_angry_opt_3[];
extern const GeoLayout luigi_eyes_happy_opt_3[];
extern const GeoLayout luigi_eyes_exhausted_opt_3[];
extern const GeoLayout luigi_eyes_dead_opt_3[];
extern const GeoLayout luigi_eyes_hurt_opt_3[];
extern const GeoLayout luigi_geo_opt_3_opt_3_opt_1[];
extern const GeoLayout luigi_geo_opt_3_opt_3_opt_2[];
extern const GeoLayout luigi_face_happy_opt_3[];
extern const GeoLayout luigi_face_angry_opt_3[];
extern const GeoLayout luigi_face_O_opt_3[];
extern const GeoLayout luigi_left_hand_open_opt_3[];
extern const GeoLayout luigi_right_hand_open_opt_3[];
extern const GeoLayout luigi_right_hand_peace_opt_3[];
extern const GeoLayout luigi_right_hand_cap_opt_3[];
extern const GeoLayout luigi_right_hand_wing_cap_opt_3[];
extern const GeoLayout luigi_geo_opt_3[];
extern const GeoLayout luigi_geo[];
extern Lights1 luigi_luigi_overalls_lights;
extern Lights1 luigi_luigi_buttons_lights;
extern Lights1 luigi_luigi_shirt_lights;
extern Lights1 luigi_luigi_teeth_lights;
extern Lights1 luigi_luigi_hair_lights;
extern Lights1 luigi_luigi_cap_lights;
extern Lights1 luigi_luigi_emblem_lights;
extern Lights1 luigi_luigi_eyes_lights;
extern Lights1 luigi_luigi_mustache_lights;
extern Lights1 luigi_luigi_skin_lights;
extern Lights1 luigi_luigi_mouth_lights;
extern Lights1 luigi_luigi_tongue_lights;
extern Lights1 luigi_luigi_wings_lights;
extern Lights1 luigi_luigi_gloves_lights;
extern Lights1 luigi_luigi_shoes_lights;
extern Lights1 luigi_luigi_soles_lights;
extern Lights1 luigi_newmetal_lights;
extern u8 luigi_shine_dull_rgba32[];
extern u8 luigi_mario_eyes_blue_rgba32[];
extern u8 luigi_mario_metal_shade_rgba32[];
extern u8 luigi_mario_metal_light_rgba32[];
extern Vtx luigi_Butt_mesh_layer_1_vtx_0[1627];
extern Gfx luigi_Butt_mesh_layer_1_tri_0[];
extern Vtx luigi_Torso_mesh_layer_1_vtx_0[2109];
extern Gfx luigi_Torso_mesh_layer_1_tri_0[];
extern Vtx luigi_Torso_mesh_layer_1_vtx_1[223];
extern Gfx luigi_Torso_mesh_layer_1_tri_1[];
extern Vtx luigi_Torso_mesh_layer_1_vtx_2[675];
extern Gfx luigi_Torso_mesh_layer_1_tri_2[];
extern Vtx luigi_Cap_DL_mesh_layer_1_vtx_0[60];
extern Gfx luigi_Cap_DL_mesh_layer_1_tri_0[];
extern Vtx luigi_Cap_DL_mesh_layer_1_vtx_1[405];
extern Gfx luigi_Cap_DL_mesh_layer_1_tri_1[];
extern Vtx luigi_Cap_DL_mesh_layer_1_vtx_2[1046];
extern Gfx luigi_Cap_DL_mesh_layer_1_tri_2[];
extern Vtx luigi_Cap_DL_mesh_layer_1_vtx_3[30];
extern Gfx luigi_Cap_DL_mesh_layer_1_tri_3[];
extern Vtx luigi_002_switch_option_head_hair_mesh_layer_1_vtx_0[1376];
extern Gfx luigi_002_switch_option_head_hair_mesh_layer_1_tri_0[];
extern Vtx luigi_Eyes_DL_mesh_layer_1_vtx_0[234];
extern Gfx luigi_Eyes_DL_mesh_layer_1_tri_0[];
extern Vtx luigi_Eyes_DL_mesh_layer_1_vtx_1[115];
extern Gfx luigi_Eyes_DL_mesh_layer_1_tri_1[];
extern Vtx luigi_002_switch_option_eyes_half_closed_mesh_layer_1_vtx_0[310];
extern Gfx luigi_002_switch_option_eyes_half_closed_mesh_layer_1_tri_0[];
extern Vtx luigi_002_switch_option_eyes_half_closed_mesh_layer_1_vtx_1[115];
extern Gfx luigi_002_switch_option_eyes_half_closed_mesh_layer_1_tri_1[];
extern Vtx luigi_002_switch_option_eyes_half_closed_mesh_layer_1_vtx_2[234];
extern Gfx luigi_002_switch_option_eyes_half_closed_mesh_layer_1_tri_2[];
extern Vtx luigi_002_switch_option_eyes_closed_mesh_layer_1_vtx_0[310];
extern Gfx luigi_002_switch_option_eyes_closed_mesh_layer_1_tri_0[];
extern Vtx luigi_002_switch_option_eyes_closed_mesh_layer_1_vtx_1[115];
extern Gfx luigi_002_switch_option_eyes_closed_mesh_layer_1_tri_1[];
extern Vtx luigi_002_switch_option_eyes_half_open_mesh_layer_1_vtx_0[234];
extern Gfx luigi_002_switch_option_eyes_half_open_mesh_layer_1_tri_0[];
extern Vtx luigi_002_switch_option_eyes_half_open_mesh_layer_1_vtx_1[115];
extern Gfx luigi_002_switch_option_eyes_half_open_mesh_layer_1_tri_1[];
extern Vtx luigi_002_switch_option_eyes_angry_mesh_layer_1_vtx_0[234];
extern Gfx luigi_002_switch_option_eyes_angry_mesh_layer_1_tri_0[];
extern Vtx luigi_002_switch_option_eyes_angry_mesh_layer_1_vtx_1[115];
extern Gfx luigi_002_switch_option_eyes_angry_mesh_layer_1_tri_1[];
extern Vtx luigi_002_switch_option_eyes_happy_mesh_layer_1_vtx_0[234];
extern Gfx luigi_002_switch_option_eyes_happy_mesh_layer_1_tri_0[];
extern Vtx luigi_002_switch_option_eyes_happy_mesh_layer_1_vtx_1[115];
extern Gfx luigi_002_switch_option_eyes_happy_mesh_layer_1_tri_1[];
extern Vtx luigi_002_switch_option_eyes_exhausted_mesh_layer_1_vtx_0[154];
extern Gfx luigi_002_switch_option_eyes_exhausted_mesh_layer_1_tri_0[];
extern Vtx luigi_002_switch_option_eyes_exhausted_mesh_layer_1_vtx_1[234];
extern Gfx luigi_002_switch_option_eyes_exhausted_mesh_layer_1_tri_1[];
extern Vtx luigi_002_switch_option_eyes_exhausted_mesh_layer_1_vtx_2[115];
extern Gfx luigi_002_switch_option_eyes_exhausted_mesh_layer_1_tri_2[];
extern Vtx luigi_002_switch_option_eyes_dead_mesh_layer_1_vtx_0[234];
extern Gfx luigi_002_switch_option_eyes_dead_mesh_layer_1_tri_0[];
extern Vtx luigi_002_switch_option_eyes_dead_mesh_layer_1_vtx_1[115];
extern Gfx luigi_002_switch_option_eyes_dead_mesh_layer_1_tri_1[];
extern Vtx luigi_002_switch_option_eyes_hurt_mesh_layer_1_vtx_0[310];
extern Gfx luigi_002_switch_option_eyes_hurt_mesh_layer_1_tri_0[];
extern Vtx luigi_002_switch_option_eyes_hurt_mesh_layer_1_vtx_1[115];
extern Gfx luigi_002_switch_option_eyes_hurt_mesh_layer_1_tri_1[];
extern Vtx luigi_Face_DL_mesh_layer_1_vtx_0[62];
extern Gfx luigi_Face_DL_mesh_layer_1_tri_0[];
extern Vtx luigi_Face_DL_mesh_layer_1_vtx_1[174];
extern Gfx luigi_Face_DL_mesh_layer_1_tri_1[];
extern Vtx luigi_Face_DL_mesh_layer_1_vtx_2[1846];
extern Gfx luigi_Face_DL_mesh_layer_1_tri_2[];
extern Vtx luigi_002_switch_option_face_happy_mesh_layer_1_vtx_0[1845];
extern Gfx luigi_002_switch_option_face_happy_mesh_layer_1_tri_0[];
extern Vtx luigi_002_switch_option_face_happy_mesh_layer_1_vtx_1[64];
extern Gfx luigi_002_switch_option_face_happy_mesh_layer_1_tri_1[];
extern Vtx luigi_002_switch_option_face_happy_mesh_layer_1_vtx_2[116];
extern Gfx luigi_002_switch_option_face_happy_mesh_layer_1_tri_2[];
extern Vtx luigi_002_switch_option_face_happy_mesh_layer_1_vtx_3[76];
extern Gfx luigi_002_switch_option_face_happy_mesh_layer_1_tri_3[];
extern Vtx luigi_002_switch_option_face_happy_mesh_layer_1_vtx_4[174];
extern Gfx luigi_002_switch_option_face_happy_mesh_layer_1_tri_4[];
extern Vtx luigi_002_switch_option_face_angry_mesh_layer_1_vtx_0[1846];
extern Gfx luigi_002_switch_option_face_angry_mesh_layer_1_tri_0[];
extern Vtx luigi_002_switch_option_face_angry_mesh_layer_1_vtx_1[62];
extern Gfx luigi_002_switch_option_face_angry_mesh_layer_1_tri_1[];
extern Vtx luigi_002_switch_option_face_angry_mesh_layer_1_vtx_2[174];
extern Gfx luigi_002_switch_option_face_angry_mesh_layer_1_tri_2[];
extern Vtx luigi_002_switch_option_face_o_mesh_layer_1_vtx_0[1845];
extern Gfx luigi_002_switch_option_face_o_mesh_layer_1_tri_0[];
extern Vtx luigi_002_switch_option_face_o_mesh_layer_1_vtx_1[64];
extern Gfx luigi_002_switch_option_face_o_mesh_layer_1_tri_1[];
extern Vtx luigi_002_switch_option_face_o_mesh_layer_1_vtx_2[116];
extern Gfx luigi_002_switch_option_face_o_mesh_layer_1_tri_2[];
extern Vtx luigi_002_switch_option_face_o_mesh_layer_1_vtx_3[76];
extern Gfx luigi_002_switch_option_face_o_mesh_layer_1_tri_3[];
extern Vtx luigi_002_switch_option_face_o_mesh_layer_1_vtx_4[174];
extern Gfx luigi_002_switch_option_face_o_mesh_layer_1_tri_4[];
extern Vtx luigi_Left_Wing_DL_mesh_layer_1_vtx_0[457];
extern Gfx luigi_Left_Wing_DL_mesh_layer_1_tri_0[];
extern Vtx luigi_Right_Wing_DL_mesh_layer_1_vtx_0[456];
extern Gfx luigi_Right_Wing_DL_mesh_layer_1_tri_0[];
extern Vtx luigi_Left_Arm_Color_mesh_layer_1_vtx_0[1010];
extern Gfx luigi_Left_Arm_Color_mesh_layer_1_tri_0[];
extern Vtx luigi_Left_Forearm_mesh_layer_1_vtx_0[547];
extern Gfx luigi_Left_Forearm_mesh_layer_1_tri_0[];
extern Vtx luigi_Left_Forearm_mesh_layer_1_vtx_1[508];
extern Gfx luigi_Left_Forearm_mesh_layer_1_tri_1[];
extern Vtx luigi_Left_Hand_DL_mesh_layer_1_vtx_0[1371];
extern Gfx luigi_Left_Hand_DL_mesh_layer_1_tri_0[];
extern Vtx luigi_002_switch_option_left_hand_open_mesh_layer_1_vtx_0[1318];
extern Gfx luigi_002_switch_option_left_hand_open_mesh_layer_1_tri_0[];
extern Vtx luigi_Right_Arm_Color_mesh_layer_1_vtx_0[1010];
extern Gfx luigi_Right_Arm_Color_mesh_layer_1_tri_0[];
extern Vtx luigi_Right_Forearm_mesh_layer_1_vtx_0[547];
extern Gfx luigi_Right_Forearm_mesh_layer_1_tri_0[];
extern Vtx luigi_Right_Forearm_mesh_layer_1_vtx_1[504];
extern Gfx luigi_Right_Forearm_mesh_layer_1_tri_1[];
extern Vtx luigi_Right_Hand_DL_mesh_layer_1_vtx_0[1385];
extern Gfx luigi_Right_Hand_DL_mesh_layer_1_tri_0[];
extern Vtx luigi_002_switch_option_right_hand_open_mesh_layer_1_vtx_0[1305];
extern Gfx luigi_002_switch_option_right_hand_open_mesh_layer_1_tri_0[];
extern Vtx luigi_004_switch_option_right_hand_peace_mesh_layer_1_vtx_0[1329];
extern Gfx luigi_004_switch_option_right_hand_peace_mesh_layer_1_tri_0[];
extern Vtx luigi_005_switch_option_right_hand_cap_mesh_layer_1_vtx_0[1367];
extern Gfx luigi_005_switch_option_right_hand_cap_mesh_layer_1_tri_0[];
extern Vtx luigi_005_switch_option_right_hand_cap_mesh_layer_1_vtx_1[4345];
extern Gfx luigi_005_switch_option_right_hand_cap_mesh_layer_1_tri_1[];
extern Vtx luigi_005_switch_option_right_hand_cap_mesh_layer_1_vtx_2[30];
extern Gfx luigi_005_switch_option_right_hand_cap_mesh_layer_1_tri_2[];
extern Vtx luigi_005_switch_option_right_hand_cap_mesh_layer_1_vtx_3[287];
extern Gfx luigi_005_switch_option_right_hand_cap_mesh_layer_1_tri_3[];
extern Vtx luigi_006_switch_option_right_hand_wing_cap_mesh_layer_1_vtx_0[1367];
extern Gfx luigi_006_switch_option_right_hand_wing_cap_mesh_layer_1_tri_0[];
extern Vtx luigi_006_switch_option_right_hand_wing_cap_mesh_layer_1_vtx_1[4345];
extern Gfx luigi_006_switch_option_right_hand_wing_cap_mesh_layer_1_tri_1[];
extern Vtx luigi_006_switch_option_right_hand_wing_cap_mesh_layer_1_vtx_2[30];
extern Gfx luigi_006_switch_option_right_hand_wing_cap_mesh_layer_1_tri_2[];
extern Vtx luigi_006_switch_option_right_hand_wing_cap_mesh_layer_1_vtx_3[1194];
extern Gfx luigi_006_switch_option_right_hand_wing_cap_mesh_layer_1_tri_3[];
extern Vtx luigi_Left_Thigh_Color_mesh_layer_1_vtx_0[998];
extern Gfx luigi_Left_Thigh_Color_mesh_layer_1_tri_0[];
extern Vtx luigi_Left_Leg_mesh_layer_1_vtx_0[998];
extern Gfx luigi_Left_Leg_mesh_layer_1_tri_0[];
extern Vtx luigi_Left_Shoe_mesh_layer_1_vtx_0[955];
extern Gfx luigi_Left_Shoe_mesh_layer_1_tri_0[];
extern Vtx luigi_Left_Shoe_mesh_layer_1_vtx_1[1024];
extern Gfx luigi_Left_Shoe_mesh_layer_1_tri_1[];
extern Vtx luigi_Left_Shoe_mesh_layer_1_vtx_2[222];
extern Gfx luigi_Left_Shoe_mesh_layer_1_tri_2[];
extern Vtx luigi_Right_Thigh_Color_mesh_layer_1_vtx_0[998];
extern Gfx luigi_Right_Thigh_Color_mesh_layer_1_tri_0[];
extern Vtx luigi_Right_Leg_mesh_layer_1_vtx_0[998];
extern Gfx luigi_Right_Leg_mesh_layer_1_tri_0[];
extern Vtx luigi_Right_Shoe_mesh_layer_1_vtx_0[958];
extern Gfx luigi_Right_Shoe_mesh_layer_1_tri_0[];
extern Vtx luigi_Right_Shoe_DL_mesh_layer_1_vtx_0[1010];
extern Gfx luigi_Right_Shoe_DL_mesh_layer_1_tri_0[];
extern Vtx luigi_Right_Shoe_DL_mesh_layer_1_vtx_1[222];
extern Gfx luigi_Right_Shoe_DL_mesh_layer_1_tri_1[];
extern Gfx mat_luigi_luigi_overalls[];
extern Gfx mat_revert_luigi_luigi_overalls[];
extern Gfx mat_luigi_luigi_buttons[];
extern Gfx mat_revert_luigi_luigi_buttons[];
extern Gfx mat_luigi_luigi_shirt[];
extern Gfx mat_revert_luigi_luigi_shirt[];
extern Gfx mat_luigi_luigi_teeth[];
extern Gfx mat_revert_luigi_luigi_teeth[];
extern Gfx mat_luigi_luigi_hair[];
extern Gfx mat_revert_luigi_luigi_hair[];
extern Gfx mat_luigi_luigi_cap[];
extern Gfx mat_revert_luigi_luigi_cap[];
extern Gfx mat_luigi_luigi_emblem[];
extern Gfx mat_revert_luigi_luigi_emblem[];
extern Gfx mat_luigi_luigi_eyes[];
extern Gfx mat_revert_luigi_luigi_eyes[];
extern Gfx mat_luigi_luigi_mustache[];
extern Gfx mat_revert_luigi_luigi_mustache[];
extern Gfx mat_luigi_luigi_skin[];
extern Gfx mat_revert_luigi_luigi_skin[];
extern Gfx mat_luigi_luigi_mouth[];
extern Gfx mat_revert_luigi_luigi_mouth[];
extern Gfx mat_luigi_luigi_tongue[];
extern Gfx mat_revert_luigi_luigi_tongue[];
extern Gfx mat_luigi_luigi_wings[];
extern Gfx mat_revert_luigi_luigi_wings[];
extern Gfx mat_luigi_luigi_gloves[];
extern Gfx mat_revert_luigi_luigi_gloves[];
extern Gfx mat_luigi_luigi_shoes[];
extern Gfx mat_revert_luigi_luigi_shoes[];
extern Gfx mat_luigi_luigi_soles[];
extern Gfx mat_revert_luigi_luigi_soles[];
extern Gfx mat_luigi_newmetal[];
extern Gfx mat_revert_luigi_newmetal[];
extern Gfx luigi_Butt_mesh_layer_1[];
extern Gfx luigi_Butt_mesh_layer_1_opt_2[];
extern Gfx luigi_Torso_mesh_layer_1[];
extern Gfx luigi_Torso_mesh_layer_1_opt_2[];
extern Gfx luigi_Cap_DL_mesh_layer_1[];
extern Gfx luigi_Cap_DL_mesh_layer_1_opt_2[];
extern Gfx luigi_002_switch_option_head_hair_mesh_layer_1[];
extern Gfx luigi_002_switch_option_head_hair_mesh_layer_1_opt_2[];
extern Gfx luigi_Eyes_DL_mesh_layer_1[];
extern Gfx luigi_Eyes_DL_mesh_layer_1_opt_2[];
extern Gfx luigi_002_switch_option_eyes_half_closed_mesh_layer_1[];
extern Gfx luigi_002_switch_option_eyes_half_closed_mesh_layer_1_opt_2[];
extern Gfx luigi_002_switch_option_eyes_closed_mesh_layer_1[];
extern Gfx luigi_002_switch_option_eyes_closed_mesh_layer_1_opt_2[];
extern Gfx luigi_002_switch_option_eyes_half_open_mesh_layer_1[];
extern Gfx luigi_002_switch_option_eyes_half_open_mesh_layer_1_opt_2[];
extern Gfx luigi_002_switch_option_eyes_angry_mesh_layer_1[];
extern Gfx luigi_002_switch_option_eyes_angry_mesh_layer_1_opt_2[];
extern Gfx luigi_002_switch_option_eyes_happy_mesh_layer_1[];
extern Gfx luigi_002_switch_option_eyes_happy_mesh_layer_1_opt_2[];
extern Gfx luigi_002_switch_option_eyes_exhausted_mesh_layer_1[];
extern Gfx luigi_002_switch_option_eyes_exhausted_mesh_layer_1_opt_2[];
extern Gfx luigi_002_switch_option_eyes_dead_mesh_layer_1[];
extern Gfx luigi_002_switch_option_eyes_dead_mesh_layer_1_opt_2[];
extern Gfx luigi_002_switch_option_eyes_hurt_mesh_layer_1[];
extern Gfx luigi_002_switch_option_eyes_hurt_mesh_layer_1_opt_2[];
extern Gfx luigi_Face_DL_mesh_layer_1[];
extern Gfx luigi_Face_DL_mesh_layer_1_opt_1[];
extern Gfx luigi_Face_DL_mesh_layer_1_opt_2[];
extern Gfx luigi_002_switch_option_face_happy_mesh_layer_1[];
extern Gfx luigi_002_switch_option_face_happy_mesh_layer_1_opt_2[];
extern Gfx luigi_002_switch_option_face_angry_mesh_layer_1[];
extern Gfx luigi_002_switch_option_face_angry_mesh_layer_1_opt_2[];
extern Gfx luigi_002_switch_option_face_o_mesh_layer_1[];
extern Gfx luigi_002_switch_option_face_o_mesh_layer_1_opt_2[];
extern Gfx luigi_Left_Wing_DL_mesh_layer_1[];
extern Gfx luigi_Left_Wing_DL_mesh_layer_1_opt_2[];
extern Gfx luigi_Right_Wing_DL_mesh_layer_1[];
extern Gfx luigi_Right_Wing_DL_mesh_layer_1_opt_2[];
extern Gfx luigi_Left_Arm_Color_mesh_layer_1[];
extern Gfx luigi_Left_Arm_Color_mesh_layer_1_opt_2[];
extern Gfx luigi_Left_Forearm_mesh_layer_1[];
extern Gfx luigi_Left_Forearm_mesh_layer_1_opt_2[];
extern Gfx luigi_Left_Hand_DL_mesh_layer_1[];
extern Gfx luigi_Left_Hand_DL_mesh_layer_1_opt_2[];
extern Gfx luigi_002_switch_option_left_hand_open_mesh_layer_1[];
extern Gfx luigi_002_switch_option_left_hand_open_mesh_layer_1_opt_2[];
extern Gfx luigi_Right_Arm_Color_mesh_layer_1[];
extern Gfx luigi_Right_Arm_Color_mesh_layer_1_opt_2[];
extern Gfx luigi_Right_Forearm_mesh_layer_1[];
extern Gfx luigi_Right_Forearm_mesh_layer_1_opt_2[];
extern Gfx luigi_Right_Hand_DL_mesh_layer_1[];
extern Gfx luigi_Right_Hand_DL_mesh_layer_1_opt_2[];
extern Gfx luigi_002_switch_option_right_hand_open_mesh_layer_1[];
extern Gfx luigi_002_switch_option_right_hand_open_mesh_layer_1_opt_2[];
extern Gfx luigi_004_switch_option_right_hand_peace_mesh_layer_1[];
extern Gfx luigi_004_switch_option_right_hand_peace_mesh_layer_1_opt_2[];
extern Gfx luigi_005_switch_option_right_hand_cap_mesh_layer_1[];
extern Gfx luigi_005_switch_option_right_hand_cap_mesh_layer_1_opt_2[];
extern Gfx luigi_006_switch_option_right_hand_wing_cap_mesh_layer_1[];
extern Gfx luigi_006_switch_option_right_hand_wing_cap_mesh_layer_1_opt_2[];
extern Gfx luigi_Left_Thigh_Color_mesh_layer_1[];
extern Gfx luigi_Left_Thigh_Color_mesh_layer_1_opt_2[];
extern Gfx luigi_Left_Leg_mesh_layer_1[];
extern Gfx luigi_Left_Leg_mesh_layer_1_opt_2[];
extern Gfx luigi_Left_Shoe_mesh_layer_1[];
extern Gfx luigi_Left_Shoe_mesh_layer_1_opt_2[];
extern Gfx luigi_Right_Thigh_Color_mesh_layer_1[];
extern Gfx luigi_Right_Thigh_Color_mesh_layer_1_opt_2[];
extern Gfx luigi_Right_Leg_mesh_layer_1[];
extern Gfx luigi_Right_Leg_mesh_layer_1_opt_2[];
extern Gfx luigi_Right_Shoe_mesh_layer_1[];
extern Gfx luigi_Right_Shoe_mesh_layer_1_opt_2[];
extern Gfx luigi_Right_Shoe_DL_mesh_layer_1_with_layer_1_revert[];
extern Gfx luigi_Right_Shoe_DL_mesh_layer_1_opt_2_with_layer_1_revert[];
extern Gfx luigi_Right_Shoe_DL_mesh_layer_1_with_layer_5_revert[];
