#include "levels/bowser_3/texture_include.inc.c"
#include "levels/bowser_3/area_1/collision.inc.c"
#include "levels/bowser_3/area_1/macro.inc.c"
#include "levels/bowser_3/area_1/spline.inc.c"
#include "levels/bowser_3/model.inc.c"
