extern const GeoLayout red_flame_torch_000_switch_opt1[];
extern const GeoLayout red_flame_torch_000_switch_opt2[];
extern const GeoLayout red_flame_torch_000_switch_opt3[];
extern const GeoLayout red_flame_torch_000_switch_opt4[];
extern const GeoLayout red_flame_torch_000_switch_opt5[];
extern const GeoLayout red_flame_torch_000_switch_opt6[];
extern const GeoLayout red_flame_torch_000_switch_opt7[];
extern const GeoLayout red_flame_torch_geo[];
extern Lights1 red_flame_torch_flame_red_1_lights;
extern Lights1 red_flame_torch_flame_red_2_lights;
extern Lights1 red_flame_torch_flame_red_3_lights;
extern Lights1 red_flame_torch_flame_red_4_lights;
extern Lights1 red_flame_torch_flame_red_5_lights;
extern Lights1 red_flame_torch_flame_red_6_lights;
extern Lights1 red_flame_torch_flame_red_7_lights;
extern Lights1 red_flame_torch_flame_red_8_lights;
extern Lights1 red_flame_torch_hmc_torch_lights;
extern Lights1 red_flame_torch_torch_wick_lights;
extern u8 red_flame_torch_flame_red_1_rgba32[];
extern u8 red_flame_torch_flame_red_2_rgba32[];
extern u8 red_flame_torch_flame_red_3_rgba32[];
extern u8 red_flame_torch_flame_red_4_rgba32[];
extern u8 red_flame_torch_flame_red_5_rgba32[];
extern u8 red_flame_torch_flame_red_6_rgba32[];
extern u8 red_flame_torch_flame_red_7_rgba32[];
extern u8 red_flame_torch_flame_red_8_rgba32[];
extern u8 red_flame_torch_hmc_brick_rgba32[];
extern u8 red_flame_torch_shine_sharp_rgba32[];
extern Vtx red_flame_torch_000_displaylist_mesh_layer_4_vtx_0[4];
extern Gfx red_flame_torch_000_displaylist_mesh_layer_4_tri_0[];
extern Vtx red_flame_torch_torch_base_mesh_layer_1_vtx_0[349];
extern Gfx red_flame_torch_torch_base_mesh_layer_1_tri_0[];
extern Vtx red_flame_torch_torch_base_mesh_layer_1_vtx_1[32];
extern Gfx red_flame_torch_torch_base_mesh_layer_1_tri_1[];
extern Vtx red_flame_torch_torch_base_mesh_layer_5_vtx_0[349];
extern Gfx red_flame_torch_torch_base_mesh_layer_5_tri_0[];
extern Gfx mat_red_flame_torch_flame_red_1[];
extern Gfx mat_revert_red_flame_torch_flame_red_1[];
extern Gfx mat_red_flame_torch_flame_red_2[];
extern Gfx mat_revert_red_flame_torch_flame_red_2[];
extern Gfx mat_red_flame_torch_flame_red_3[];
extern Gfx mat_revert_red_flame_torch_flame_red_3[];
extern Gfx mat_red_flame_torch_flame_red_4[];
extern Gfx mat_revert_red_flame_torch_flame_red_4[];
extern Gfx mat_red_flame_torch_flame_red_5[];
extern Gfx mat_revert_red_flame_torch_flame_red_5[];
extern Gfx mat_red_flame_torch_flame_red_6[];
extern Gfx mat_revert_red_flame_torch_flame_red_6[];
extern Gfx mat_red_flame_torch_flame_red_7[];
extern Gfx mat_revert_red_flame_torch_flame_red_7[];
extern Gfx mat_red_flame_torch_flame_red_8[];
extern Gfx mat_revert_red_flame_torch_flame_red_8[];
extern Gfx mat_red_flame_torch_hmc_torch[];
extern Gfx mat_revert_red_flame_torch_hmc_torch[];
extern Gfx mat_red_flame_torch_torch_wick[];
extern Gfx mat_revert_red_flame_torch_torch_wick[];
extern Gfx mat_red_flame_torch_hmc_torch_shine[];
extern Gfx mat_revert_red_flame_torch_hmc_torch_shine[];
extern Gfx red_flame_torch_000_displaylist_mesh_layer_4[];
extern Gfx red_flame_torch_000_displaylist_mesh_layer_4_mat_override_flame_red_2_0[];
extern Gfx red_flame_torch_000_displaylist_mesh_layer_4_mat_override_flame_red_3_1[];
extern Gfx red_flame_torch_000_displaylist_mesh_layer_4_mat_override_flame_red_4_2[];
extern Gfx red_flame_torch_000_displaylist_mesh_layer_4_mat_override_flame_red_5_3[];
extern Gfx red_flame_torch_000_displaylist_mesh_layer_4_mat_override_flame_red_6_4[];
extern Gfx red_flame_torch_000_displaylist_mesh_layer_4_mat_override_flame_red_7_5[];
extern Gfx red_flame_torch_000_displaylist_mesh_layer_4_mat_override_flame_red_8_6[];
extern Gfx red_flame_torch_torch_base_mesh_layer_1[];
extern Gfx red_flame_torch_torch_base_mesh_layer_5[];
