const GeoLayout dorrie_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_CULLING_RADIUS(1063350),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dorrie_000_offset_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dorrie_000_offset_mesh_layer_5),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, dorrie_000_offset_001_skinned_mesh_layer_1),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dorrie_000_offset_001_skinned_mesh_layer_5),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 1294, 0, 0, dorrie_000_offset_001_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dorrie_000_offset_001_mesh_layer_5),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, dorrie_000_offset_002_skinned_mesh_layer_1),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dorrie_000_offset_002_skinned_mesh_layer_5),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 916, 0, 0, dorrie_000_offset_002_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dorrie_000_offset_002_mesh_layer_5),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, dorrie_000_offset_003_skinned_mesh_layer_1),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dorrie_000_offset_003_skinned_mesh_layer_5),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 874, 0, 0, dorrie_000_offset_003_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dorrie_000_offset_003_mesh_layer_5),
									GEO_DISPLAY_LIST(LAYER_ALPHA, dorrie_000_offset_003_mesh_layer_4),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 30, 444, -6, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, -893, -490, -6, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 1299, 0, 0, NULL),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, -1086, 91, -700, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dorrie_000_offset_007_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dorrie_000_offset_007_mesh_layer_5),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 902, 700, -785, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dorrie_000_offset_008_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dorrie_000_offset_008_mesh_layer_5),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, -1086, 91, 698, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dorrie_000_offset_009_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dorrie_000_offset_009_mesh_layer_5),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 902, 700, 783, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dorrie_000_offset_010_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dorrie_000_offset_010_mesh_layer_5),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
