const struct Animation *const bowser_anims[] = {
	&bowser_anim_get_up_1,
	&bowser_anim_get_up_fast_2,
	&bowser_anim_held_3,
	&bowser_anim_start_held_4,
	&bowser_anim_die_18, //unused
	&bowser_anim_die_18, //unused
	&bowser_anim_fire_breath_long_7,
	&bowser_anim_jump_8,
	&bowser_anim_jump_land_9,
	&bowser_anim_jump_start_10,
	&bowser_anim_scratching_11,
	&bowser_anim_final_fire_12,
	&bowser_anim_idle_13,
	&bowser_anim_walk_14,
	&bowser_anim_walk_end_15,
	&bowser_anim_walk_start_16,
	&bowser_anim_blown_up_17,
	&bowser_anim_die_18,
	&bowser_anim_run_start_19,
	&bowser_anim_run_20,
	&bowser_anim_run_stop_stop_21,
	&bowser_anim_run_stop_start_22,
	&bowser_anim_short_fire_23,
	&bowser_anim_tip_toe_24,
	&bowser_anim_tip_toe_land_25,
	&bowser_anim_blown_up_survived_26,
	&bowser_anim_get_up_explosion_27,
	NULL,
};
