const GeoLayout wiggler_head_wiggler_head_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, wiggler_head_switch_opt1_000_displaylist2_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout wiggler_head_wiggler_head_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, wiggler_head_switch_opt1_000_displaylist3_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout wiggler_head_wiggler_head_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, wiggler_head_switch_opt1_000_displaylist4_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout wiggler_head_wiggler_head_4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, wiggler_head_switch_opt1_000_displaylist5_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout wiggler_head_wiggler_body_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, wiggler_head_switch_angry_000_displaylist1_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout wiggler_head_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 150, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_SCALE(LAYER_FORCE, 16384),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 628, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 0, 0, 0, 0, 0, 0),
								GEO_OPEN_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, -56, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(4, geo_switch_state_1),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, wiggler_head_000_displaylist_002_mesh_layer_1),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, wiggler_head_wiggler_head_1),
										GEO_BRANCH(1, wiggler_head_wiggler_head_2),
										GEO_BRANCH(1, wiggler_head_wiggler_head_3),
										GEO_BRANCH(1, wiggler_head_wiggler_head_4),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, -56, 0, 0, NULL),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 628, 0, 0, NULL),
							GEO_ANIMATED_PART(LAYER_ALPHA, 628, 0, 0, NULL),
							GEO_ANIMATED_PART(LAYER_ALPHA, 628, 0, 0, NULL),
							GEO_ANIMATED_PART(LAYER_OPAQUE, -64, 92, 204, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, wiggler_head_000_offset_004_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 156, 0, 0, wiggler_head_000_offset_005_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 164, 0, 0, wiggler_head_000_offset_006_mesh_layer_1),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, -64, 92, -196, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, wiggler_head_000_offset_007_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 156, 0, 0, wiggler_head_000_offset_008_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 164, 0, 0, wiggler_head_000_offset_009_mesh_layer_1),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_FORCE, 0, 0, 0, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_ASM(0, geo_function_wiggler_rotate),
								GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_wiggler_color),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, wiggler_head_000_displaylist_mesh_layer_1),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, wiggler_head_wiggler_body_1),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
