const GeoLayout mr_blizzard_hidden_hat_switch1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ASM(0, geo_mario_set_player_colors),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mr_blizzard_hidden_hat_opt1_hat_dl_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mr_blizzard_hidden_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SCALE(LAYER_FORCE, 16384),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_FORCE, 0, 0, 0, 0, 0, 0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, mr_blizzard_hidden_000_displaylist_mesh_layer_1),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mr_blizzard_hidden_000_displaylist_mesh_layer_5),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 260, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_FORCE, 0, 0, 0, 0, 0, 0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_ALPHA, mr_blizzard_hidden_000_displaylist_001_mesh_layer_4),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, mr_blizzard_hidden_000_displaylist_001_mesh_layer_1),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mr_blizzard_hidden_000_displaylist_001_mesh_layer_5),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, 260, 0, 0, NULL),
					GEO_ANIMATED_PART(LAYER_ALPHA, 260, 0, 0, NULL),
					GEO_SWITCH_CASE(2, geo_switch_anim_state),
					GEO_OPEN_NODE(),
						GEO_NODE_START(),
						GEO_OPEN_NODE(),
						GEO_CLOSE_NODE(),
						GEO_BRANCH(1, mr_blizzard_hidden_hat_switch1),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, -218, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mr_blizzard_hidden_000_offset_002_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 68, 0, 0, NULL),
							GEO_ASM(0, geo_update_projectile_pos_from_parent),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 260, 0, 0, NULL),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
