extern const GeoLayout warios_wing_cap_001_switch_opt1[];
extern const GeoLayout warios_wing_cap_geo[];
extern Lights1 warios_wing_cap_wario_cap_lights;
extern Lights1 warios_wing_cap_mario_cap_wings_lights;
extern Lights1 warios_wing_cap_wario_emblem_lights;
extern Lights1 warios_wing_cap_mario_cap_black_lights;
extern u8 warios_wing_cap_shine_dull_rgba32[];
extern Vtx warios_wing_cap_000_displaylist_mesh_layer_1_vtx_0[687];
extern Gfx warios_wing_cap_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx warios_wing_cap_000_displaylist_mesh_layer_1_vtx_1[4620];
extern Gfx warios_wing_cap_000_displaylist_mesh_layer_1_tri_1[];
extern Vtx warios_wing_cap_000_displaylist_mesh_layer_1_vtx_2[42];
extern Gfx warios_wing_cap_000_displaylist_mesh_layer_1_tri_2[];
extern Vtx warios_wing_cap_000_displaylist_mesh_layer_1_vtx_3[12];
extern Gfx warios_wing_cap_000_displaylist_mesh_layer_1_tri_3[];
extern Gfx mat_warios_wing_cap_wario_cap[];
extern Gfx mat_revert_warios_wing_cap_wario_cap[];
extern Gfx mat_warios_wing_cap_mario_cap_wings[];
extern Gfx mat_revert_warios_wing_cap_mario_cap_wings[];
extern Gfx mat_warios_wing_cap_wario_emblem[];
extern Gfx mat_revert_warios_wing_cap_wario_emblem[];
extern Gfx mat_warios_wing_cap_mario_cap_black[];
extern Gfx mat_revert_warios_wing_cap_mario_cap_black[];
extern Gfx warios_wing_cap_000_displaylist_mesh_layer_1[];
