extern const GeoLayout wario_head_capless[];
extern const GeoLayout wario_eyes_half_closed[];
extern const GeoLayout wario_eyes_closed[];
extern const GeoLayout wario_eyes_tiptoe[];
extern const GeoLayout wario_eyes_angry[];
extern const GeoLayout wario_eyes_happy[];
extern const GeoLayout wario_eyes_exhausted[];
extern const GeoLayout wario_eyes_dead[];
extern const GeoLayout wario_eyes_hurt[];
extern const GeoLayout wario_face_happy[];
extern const GeoLayout wario_face_angry[];
extern const GeoLayout wario_face_O[];
extern const GeoLayout wario_face_E[];
extern const GeoLayout wario_left_hand_open[];
extern const GeoLayout wario_right_hand_wario_closed[];
extern const GeoLayout wario_right_hand_open[];
extern const GeoLayout wario_right_hand_peace[];
extern const GeoLayout wario_right_hand_cap[];
extern const GeoLayout wario_right_hand_wing_cap[];
extern const GeoLayout wario_geo_opt_1[];
extern const GeoLayout wario_geo_opt_2[];
extern const GeoLayout wario_head_capless_opt_1[];
extern const GeoLayout wario_eyes_half_closed_opt_1[];
extern const GeoLayout wario_eyes_closed_opt_1[];
extern const GeoLayout wario_eyes_tiptoe_opt_1[];
extern const GeoLayout wario_eyes_angry_opt_1[];
extern const GeoLayout wario_eyes_happy_opt_1[];
extern const GeoLayout wario_eyes_exhausted_opt_1[];
extern const GeoLayout wario_eyes_dead_opt_1[];
extern const GeoLayout wario_eyes_hurt_opt_1[];
extern const GeoLayout wario_geo_opt_1_1_opt_1_opt_1[];
extern const GeoLayout wario_geo_opt_1_1_opt_1_opt_2[];
extern const GeoLayout wario_face_happy_opt_1[];
extern const GeoLayout wario_face_angry_opt_1[];
extern const GeoLayout wario_face_O_opt_1[];
extern const GeoLayout wario_face_E_opt_1[];
extern const GeoLayout wario_left_hand_open_opt_1[];
extern const GeoLayout wario_right_hand_wario_closed_opt_1[];
extern const GeoLayout wario_right_hand_open_opt_1[];
extern const GeoLayout wario_right_hand_peace_opt_1[];
extern const GeoLayout wario_right_hand_cap_opt_1[];
extern const GeoLayout wario_right_hand_wing_cap_opt_1[];
extern const GeoLayout wario_geo_opt_1_1[];
extern const GeoLayout wario_head_capless_opt_2[];
extern const GeoLayout wario_eyes_half_closed_opt_2[];
extern const GeoLayout wario_eyes_closed_opt_2[];
extern const GeoLayout wario_eyes_tiptoe_opt_2[];
extern const GeoLayout wario_eyes_angry_opt_2[];
extern const GeoLayout wario_eyes_happy_opt_2[];
extern const GeoLayout wario_eyes_exhausted_opt_2[];
extern const GeoLayout wario_eyes_dead_opt_2[];
extern const GeoLayout wario_eyes_hurt_opt_2[];
extern const GeoLayout wario_geo_opt_2_1_opt_2_opt_1[];
extern const GeoLayout wario_geo_opt_2_1_opt_2_opt_2[];
extern const GeoLayout wario_face_happy_opt_2[];
extern const GeoLayout wario_face_angry_opt_2[];
extern const GeoLayout wario_face_O_opt_2[];
extern const GeoLayout wario_face_E_opt_2[];
extern const GeoLayout wario_left_hand_open_opt_2[];
extern const GeoLayout wario_right_hand_wario_closed_opt_2[];
extern const GeoLayout wario_right_hand_open_opt_2[];
extern const GeoLayout wario_right_hand_peace_opt_2[];
extern const GeoLayout wario_right_hand_cap_opt_2[];
extern const GeoLayout wario_right_hand_wing_cap_opt_2[];
extern const GeoLayout wario_geo_opt_2_1[];
extern const GeoLayout wario_head_capless_opt_3[];
extern const GeoLayout wario_eyes_half_closed_opt_3[];
extern const GeoLayout wario_eyes_closed_opt_3[];
extern const GeoLayout wario_eyes_tiptoe_opt_3[];
extern const GeoLayout wario_eyes_angry_opt_3[];
extern const GeoLayout wario_eyes_happy_opt_3[];
extern const GeoLayout wario_eyes_exhausted_opt_3[];
extern const GeoLayout wario_eyes_dead_opt_3[];
extern const GeoLayout wario_eyes_hurt_opt_3[];
extern const GeoLayout wario_geo_opt_3_opt_3_opt_1[];
extern const GeoLayout wario_geo_opt_3_opt_3_opt_2[];
extern const GeoLayout wario_face_happy_opt_3[];
extern const GeoLayout wario_face_angry_opt_3[];
extern const GeoLayout wario_face_O_opt_3[];
extern const GeoLayout wario_face_E_opt_3[];
extern const GeoLayout wario_left_hand_open_opt_3[];
extern const GeoLayout wario_right_hand_wario_closed_opt_3[];
extern const GeoLayout wario_right_hand_open_opt_3[];
extern const GeoLayout wario_right_hand_peace_opt_3[];
extern const GeoLayout wario_right_hand_cap_opt_3[];
extern const GeoLayout wario_right_hand_wing_cap_opt_3[];
extern const GeoLayout wario_geo_opt_3[];
extern const GeoLayout wario_geo[];
extern Lights1 wario_wario_shirt_lights;
extern Lights1 wario_wario_skin_lights;
extern Lights1 wario_wario_white_lights;
extern Lights1 wario_wario_overalls_lights;
extern Lights1 wario_wario_hair_lights;
extern Lights1 wario_wario_emblem_lights;
extern Lights1 wario_wario_cap_lights;
extern Lights1 wario_wario_mustache_lights;
extern Lights1 wario_wario_mouth_lights;
extern Lights1 wario_wario_nose_lights;
extern Lights1 wario_wario_eyebag_lights;
extern Lights1 wario_wario_tongue_lights;
extern Lights1 wario_wario_wings_lights;
extern Lights1 wario_wario_gloves_lights;
extern Lights1 wario_wario_hat_inner_lights;
extern Lights1 wario_wario_shoes_lights;
extern Lights1 wario_wario_metal_lights;
extern u8 wario_shine_dull_rgba32[];
extern u8 wario_w_logo_gloves_rgba16[];
extern u8 wario_mario_metal_shade_rgba16[];
extern u8 wario_mario_metal_light_rgba16[];
extern Vtx wario_Torso_mesh_layer_1_vtx_0[702];
extern Gfx wario_Torso_mesh_layer_1_tri_0[];
extern Vtx wario_Torso_mesh_layer_1_vtx_1[46];
extern Gfx wario_Torso_mesh_layer_1_tri_1[];
extern Vtx wario_Torso_mesh_layer_1_vtx_2[178];
extern Gfx wario_Torso_mesh_layer_1_tri_2[];
extern Vtx wario_Torso_mesh_layer_1_vtx_3[1597];
extern Gfx wario_Torso_mesh_layer_1_tri_3[];
extern Vtx wario_Cap_DL_mesh_layer_1_vtx_0[298];
extern Gfx wario_Cap_DL_mesh_layer_1_tri_0[];
extern Vtx wario_Cap_DL_mesh_layer_1_vtx_1[2147];
extern Gfx wario_Cap_DL_mesh_layer_1_tri_1[];
extern Vtx wario_Cap_DL_mesh_layer_1_vtx_2[28];
extern Gfx wario_Cap_DL_mesh_layer_1_tri_2[];
extern Vtx wario_Cap_DL_mesh_layer_1_vtx_3[601];
extern Gfx wario_Cap_DL_mesh_layer_1_tri_3[];
extern Vtx wario_002_switch_option_head_hair_mesh_layer_1_vtx_0[2766];
extern Gfx wario_002_switch_option_head_hair_mesh_layer_1_tri_0[];
extern Vtx wario_Eyes_DL_mesh_layer_1_vtx_0[738];
extern Gfx wario_Eyes_DL_mesh_layer_1_tri_0[];
extern Vtx wario_002_switch_option_eyes_half_closed_mesh_layer_1_vtx_0[122];
extern Gfx wario_002_switch_option_eyes_half_closed_mesh_layer_1_tri_0[];
extern Vtx wario_002_switch_option_eyes_half_closed_mesh_layer_1_vtx_1[738];
extern Gfx wario_002_switch_option_eyes_half_closed_mesh_layer_1_tri_1[];
extern Vtx wario_002_switch_option_eyes_closed_mesh_layer_1_vtx_0[184];
extern Gfx wario_002_switch_option_eyes_closed_mesh_layer_1_tri_0[];
extern Vtx wario_002_switch_option_eyes_closed_mesh_layer_1_vtx_1[493];
extern Gfx wario_002_switch_option_eyes_closed_mesh_layer_1_tri_1[];
extern Vtx wario_002_switch_option_eyes_half_open_mesh_layer_1_vtx_0[738];
extern Gfx wario_002_switch_option_eyes_half_open_mesh_layer_1_tri_0[];
extern Vtx wario_002_switch_option_eyes_angry_mesh_layer_1_vtx_0[738];
extern Gfx wario_002_switch_option_eyes_angry_mesh_layer_1_tri_0[];
extern Vtx wario_002_switch_option_eyes_happy_mesh_layer_1_vtx_0[738];
extern Gfx wario_002_switch_option_eyes_happy_mesh_layer_1_tri_0[];
extern Vtx wario_002_switch_option_eyes_exhausted_mesh_layer_1_vtx_0[122];
extern Gfx wario_002_switch_option_eyes_exhausted_mesh_layer_1_tri_0[];
extern Vtx wario_002_switch_option_eyes_exhausted_mesh_layer_1_vtx_1[749];
extern Gfx wario_002_switch_option_eyes_exhausted_mesh_layer_1_tri_1[];
extern Vtx wario_002_switch_option_eyes_dead_mesh_layer_1_vtx_0[184];
extern Gfx wario_002_switch_option_eyes_dead_mesh_layer_1_tri_0[];
extern Vtx wario_002_switch_option_eyes_dead_mesh_layer_1_vtx_1[493];
extern Gfx wario_002_switch_option_eyes_dead_mesh_layer_1_tri_1[];
extern Vtx wario_002_switch_option_eyes_hurt_mesh_layer_1_vtx_0[738];
extern Gfx wario_002_switch_option_eyes_hurt_mesh_layer_1_tri_0[];
extern Vtx wario_Face_DL_mesh_layer_1_vtx_0[2064];
extern Gfx wario_Face_DL_mesh_layer_1_tri_0[];
extern Vtx wario_Face_DL_mesh_layer_1_vtx_1[816];
extern Gfx wario_Face_DL_mesh_layer_1_tri_1[];
extern Vtx wario_Face_DL_mesh_layer_1_vtx_2[102];
extern Gfx wario_Face_DL_mesh_layer_1_tri_2[];
extern Vtx wario_Face_DL_mesh_layer_1_vtx_3[885];
extern Gfx wario_Face_DL_mesh_layer_1_tri_3[];
extern Vtx wario_Face_DL_mesh_layer_1_vtx_4[575];
extern Gfx wario_Face_DL_mesh_layer_1_tri_4[];
extern Vtx wario_Face_DL_mesh_layer_1_vtx_5[60];
extern Gfx wario_Face_DL_mesh_layer_1_tri_5[];
extern Vtx wario_Face_DL_mesh_layer_1_vtx_6[152];
extern Gfx wario_Face_DL_mesh_layer_1_tri_6[];
extern Vtx wario_002_switch_option_face_happy_mesh_layer_1_vtx_0[2064];
extern Gfx wario_002_switch_option_face_happy_mesh_layer_1_tri_0[];
extern Vtx wario_002_switch_option_face_happy_mesh_layer_1_vtx_1[816];
extern Gfx wario_002_switch_option_face_happy_mesh_layer_1_tri_1[];
extern Vtx wario_002_switch_option_face_happy_mesh_layer_1_vtx_2[102];
extern Gfx wario_002_switch_option_face_happy_mesh_layer_1_tri_2[];
extern Vtx wario_002_switch_option_face_happy_mesh_layer_1_vtx_3[885];
extern Gfx wario_002_switch_option_face_happy_mesh_layer_1_tri_3[];
extern Vtx wario_002_switch_option_face_happy_mesh_layer_1_vtx_4[575];
extern Gfx wario_002_switch_option_face_happy_mesh_layer_1_tri_4[];
extern Vtx wario_002_switch_option_face_happy_mesh_layer_1_vtx_5[60];
extern Gfx wario_002_switch_option_face_happy_mesh_layer_1_tri_5[];
extern Vtx wario_002_switch_option_face_happy_mesh_layer_1_vtx_6[152];
extern Gfx wario_002_switch_option_face_happy_mesh_layer_1_tri_6[];
extern Vtx wario_002_switch_option_face_angry_mesh_layer_1_vtx_0[2064];
extern Gfx wario_002_switch_option_face_angry_mesh_layer_1_tri_0[];
extern Vtx wario_002_switch_option_face_angry_mesh_layer_1_vtx_1[816];
extern Gfx wario_002_switch_option_face_angry_mesh_layer_1_tri_1[];
extern Vtx wario_002_switch_option_face_angry_mesh_layer_1_vtx_2[102];
extern Gfx wario_002_switch_option_face_angry_mesh_layer_1_tri_2[];
extern Vtx wario_002_switch_option_face_angry_mesh_layer_1_vtx_3[885];
extern Gfx wario_002_switch_option_face_angry_mesh_layer_1_tri_3[];
extern Vtx wario_002_switch_option_face_angry_mesh_layer_1_vtx_4[575];
extern Gfx wario_002_switch_option_face_angry_mesh_layer_1_tri_4[];
extern Vtx wario_002_switch_option_face_angry_mesh_layer_1_vtx_5[60];
extern Gfx wario_002_switch_option_face_angry_mesh_layer_1_tri_5[];
extern Vtx wario_002_switch_option_face_angry_mesh_layer_1_vtx_6[152];
extern Gfx wario_002_switch_option_face_angry_mesh_layer_1_tri_6[];
extern Vtx wario_002_switch_option_face_o_mesh_layer_1_vtx_0[2064];
extern Gfx wario_002_switch_option_face_o_mesh_layer_1_tri_0[];
extern Vtx wario_002_switch_option_face_o_mesh_layer_1_vtx_1[816];
extern Gfx wario_002_switch_option_face_o_mesh_layer_1_tri_1[];
extern Vtx wario_002_switch_option_face_o_mesh_layer_1_vtx_2[102];
extern Gfx wario_002_switch_option_face_o_mesh_layer_1_tri_2[];
extern Vtx wario_002_switch_option_face_o_mesh_layer_1_vtx_3[885];
extern Gfx wario_002_switch_option_face_o_mesh_layer_1_tri_3[];
extern Vtx wario_002_switch_option_face_o_mesh_layer_1_vtx_4[575];
extern Gfx wario_002_switch_option_face_o_mesh_layer_1_tri_4[];
extern Vtx wario_002_switch_option_face_o_mesh_layer_1_vtx_5[60];
extern Gfx wario_002_switch_option_face_o_mesh_layer_1_tri_5[];
extern Vtx wario_002_switch_option_face_o_mesh_layer_1_vtx_6[152];
extern Gfx wario_002_switch_option_face_o_mesh_layer_1_tri_6[];
extern Vtx wario_002_switch_option_face_e_mesh_layer_1_vtx_0[2064];
extern Gfx wario_002_switch_option_face_e_mesh_layer_1_tri_0[];
extern Vtx wario_002_switch_option_face_e_mesh_layer_1_vtx_1[816];
extern Gfx wario_002_switch_option_face_e_mesh_layer_1_tri_1[];
extern Vtx wario_002_switch_option_face_e_mesh_layer_1_vtx_2[102];
extern Gfx wario_002_switch_option_face_e_mesh_layer_1_tri_2[];
extern Vtx wario_002_switch_option_face_e_mesh_layer_1_vtx_3[885];
extern Gfx wario_002_switch_option_face_e_mesh_layer_1_tri_3[];
extern Vtx wario_002_switch_option_face_e_mesh_layer_1_vtx_4[575];
extern Gfx wario_002_switch_option_face_e_mesh_layer_1_tri_4[];
extern Vtx wario_002_switch_option_face_e_mesh_layer_1_vtx_5[60];
extern Gfx wario_002_switch_option_face_e_mesh_layer_1_tri_5[];
extern Vtx wario_002_switch_option_face_e_mesh_layer_1_vtx_6[152];
extern Gfx wario_002_switch_option_face_e_mesh_layer_1_tri_6[];
extern Vtx wario_Left_Wing_DL_mesh_layer_1_vtx_0[632];
extern Gfx wario_Left_Wing_DL_mesh_layer_1_tri_0[];
extern Vtx wario_Right_Wing_DL_mesh_layer_1_vtx_0[656];
extern Gfx wario_Right_Wing_DL_mesh_layer_1_tri_0[];
extern Vtx wario_Left_Arm_Color_mesh_layer_1_vtx_0[803];
extern Gfx wario_Left_Arm_Color_mesh_layer_1_tri_0[];
extern Vtx wario_Left_Forearm_mesh_layer_1_vtx_0[756];
extern Gfx wario_Left_Forearm_mesh_layer_1_tri_0[];
extern Vtx wario_Left_Forearm_mesh_layer_1_vtx_1[174];
extern Gfx wario_Left_Forearm_mesh_layer_1_tri_1[];
extern Vtx wario_Left_Hand_DL_mesh_layer_1_vtx_0[1305];
extern Gfx wario_Left_Hand_DL_mesh_layer_1_tri_0[];
extern Vtx wario_002_switch_option_left_hand_open_mesh_layer_1_vtx_0[1363];
extern Gfx wario_002_switch_option_left_hand_open_mesh_layer_1_tri_0[];
extern Vtx wario_Right_Arm_Color_mesh_layer_1_vtx_0[801];
extern Gfx wario_Right_Arm_Color_mesh_layer_1_tri_0[];
extern Vtx wario_Right_Forearm_mesh_layer_1_vtx_0[755];
extern Gfx wario_Right_Forearm_mesh_layer_1_tri_0[];
extern Vtx wario_Right_Forearm_mesh_layer_1_vtx_1[175];
extern Gfx wario_Right_Forearm_mesh_layer_1_tri_1[];
extern Vtx wario_Right_Hand_DL_mesh_layer_1_vtx_0[1301];
extern Gfx wario_Right_Hand_DL_mesh_layer_1_tri_0[];
extern Vtx wario_002_switch_option_right_hand_open_mesh_layer_1_vtx_0[1342];
extern Gfx wario_002_switch_option_right_hand_open_mesh_layer_1_tri_0[];
extern Vtx wario_004_switch_option_right_hand_peace_mesh_layer_1_vtx_0[1384];
extern Gfx wario_004_switch_option_right_hand_peace_mesh_layer_1_tri_0[];
extern Vtx wario_005_switch_option_right_hand_cap_mesh_layer_1_vtx_0[1301];
extern Gfx wario_005_switch_option_right_hand_cap_mesh_layer_1_tri_0[];
extern Vtx wario_005_switch_option_right_hand_cap_mesh_layer_1_vtx_1[689];
extern Gfx wario_005_switch_option_right_hand_cap_mesh_layer_1_tri_1[];
extern Vtx wario_005_switch_option_right_hand_cap_mesh_layer_1_vtx_2[344];
extern Gfx wario_005_switch_option_right_hand_cap_mesh_layer_1_tri_2[];
extern Vtx wario_005_switch_option_right_hand_cap_mesh_layer_1_vtx_3[42];
extern Gfx wario_005_switch_option_right_hand_cap_mesh_layer_1_tri_3[];
extern Vtx wario_005_switch_option_right_hand_cap_mesh_layer_1_vtx_4[62];
extern Gfx wario_005_switch_option_right_hand_cap_mesh_layer_1_tri_4[];
extern Vtx wario_006_switch_option_right_hand_wing_cap_mesh_layer_1_vtx_0[1301];
extern Gfx wario_006_switch_option_right_hand_wing_cap_mesh_layer_1_tri_0[];
extern Vtx wario_006_switch_option_right_hand_wing_cap_mesh_layer_1_vtx_1[689];
extern Gfx wario_006_switch_option_right_hand_wing_cap_mesh_layer_1_tri_1[];
extern Vtx wario_006_switch_option_right_hand_wing_cap_mesh_layer_1_vtx_2[894];
extern Gfx wario_006_switch_option_right_hand_wing_cap_mesh_layer_1_tri_2[];
extern Vtx wario_006_switch_option_right_hand_wing_cap_mesh_layer_1_vtx_3[344];
extern Gfx wario_006_switch_option_right_hand_wing_cap_mesh_layer_1_tri_3[];
extern Vtx wario_006_switch_option_right_hand_wing_cap_mesh_layer_1_vtx_4[42];
extern Gfx wario_006_switch_option_right_hand_wing_cap_mesh_layer_1_tri_4[];
extern Vtx wario_006_switch_option_right_hand_wing_cap_mesh_layer_1_vtx_5[62];
extern Gfx wario_006_switch_option_right_hand_wing_cap_mesh_layer_1_tri_5[];
extern Vtx wario_Left_Thigh_Color_mesh_layer_1_vtx_0[748];
extern Gfx wario_Left_Thigh_Color_mesh_layer_1_tri_0[];
extern Vtx wario_Left_Leg_mesh_layer_1_vtx_0[803];
extern Gfx wario_Left_Leg_mesh_layer_1_tri_0[];
extern Vtx wario_Left_Shoe_mesh_layer_1_vtx_0[172];
extern Gfx wario_Left_Shoe_mesh_layer_1_tri_0[];
extern Vtx wario_Right_Thigh_Color_mesh_layer_1_vtx_0[745];
extern Gfx wario_Right_Thigh_Color_mesh_layer_1_tri_0[];
extern Vtx wario_Right_Leg_mesh_layer_1_vtx_0[806];
extern Gfx wario_Right_Leg_mesh_layer_1_tri_0[];
extern Vtx wario_Right_Shoe_mesh_layer_1_vtx_0[169];
extern Gfx wario_Right_Shoe_mesh_layer_1_tri_0[];
extern Gfx mat_wario_wario_shirt[];
extern Gfx mat_revert_wario_wario_shirt[];
extern Gfx mat_wario_wario_skin[];
extern Gfx mat_revert_wario_wario_skin[];
extern Gfx mat_wario_wario_white[];
extern Gfx mat_revert_wario_wario_white[];
extern Gfx mat_wario_wario_overalls[];
extern Gfx mat_revert_wario_wario_overalls[];
extern Gfx mat_wario_wario_hair[];
extern Gfx mat_revert_wario_wario_hair[];
extern Gfx mat_wario_wario_emblem[];
extern Gfx mat_revert_wario_wario_emblem[];
extern Gfx mat_wario_wario_cap[];
extern Gfx mat_revert_wario_wario_cap[];
extern Gfx mat_wario_wario_mustache[];
extern Gfx mat_revert_wario_wario_mustache[];
extern Gfx mat_wario_wario_mouth[];
extern Gfx mat_revert_wario_wario_mouth[];
extern Gfx mat_wario_wario_nose[];
extern Gfx mat_revert_wario_wario_nose[];
extern Gfx mat_wario_wario_eyebag[];
extern Gfx mat_revert_wario_wario_eyebag[];
extern Gfx mat_wario_wario_tongue[];
extern Gfx mat_revert_wario_wario_tongue[];
extern Gfx mat_wario_wario_wings[];
extern Gfx mat_revert_wario_wario_wings[];
extern Gfx mat_wario_wario_gloves[];
extern Gfx mat_revert_wario_wario_gloves[];
extern Gfx mat_wario_wario_hat_inner[];
extern Gfx mat_revert_wario_wario_hat_inner[];
extern Gfx mat_wario_wario_shoes[];
extern Gfx mat_revert_wario_wario_shoes[];
extern Gfx mat_wario_wario_metal[];
extern Gfx mat_revert_wario_wario_metal[];
extern Gfx wario_Torso_mesh_layer_1[];
extern Gfx wario_Torso_mesh_layer_1_opt_2[];
extern Gfx wario_Cap_DL_mesh_layer_1[];
extern Gfx wario_Cap_DL_mesh_layer_1_opt_2[];
extern Gfx wario_002_switch_option_head_hair_mesh_layer_1[];
extern Gfx wario_002_switch_option_head_hair_mesh_layer_1_opt_2[];
extern Gfx wario_Eyes_DL_mesh_layer_1[];
extern Gfx wario_Eyes_DL_mesh_layer_1_opt_2[];
extern Gfx wario_002_switch_option_eyes_half_closed_mesh_layer_1[];
extern Gfx wario_002_switch_option_eyes_half_closed_mesh_layer_1_opt_2[];
extern Gfx wario_002_switch_option_eyes_closed_mesh_layer_1[];
extern Gfx wario_002_switch_option_eyes_closed_mesh_layer_1_opt_2[];
extern Gfx wario_002_switch_option_eyes_half_open_mesh_layer_1[];
extern Gfx wario_002_switch_option_eyes_half_open_mesh_layer_1_opt_2[];
extern Gfx wario_002_switch_option_eyes_angry_mesh_layer_1[];
extern Gfx wario_002_switch_option_eyes_angry_mesh_layer_1_opt_2[];
extern Gfx wario_002_switch_option_eyes_happy_mesh_layer_1[];
extern Gfx wario_002_switch_option_eyes_happy_mesh_layer_1_opt_2[];
extern Gfx wario_002_switch_option_eyes_exhausted_mesh_layer_1[];
extern Gfx wario_002_switch_option_eyes_exhausted_mesh_layer_1_opt_2[];
extern Gfx wario_002_switch_option_eyes_dead_mesh_layer_1[];
extern Gfx wario_002_switch_option_eyes_dead_mesh_layer_1_opt_2[];
extern Gfx wario_002_switch_option_eyes_hurt_mesh_layer_1[];
extern Gfx wario_002_switch_option_eyes_hurt_mesh_layer_1_opt_2[];
extern Gfx wario_Face_DL_mesh_layer_1[];
extern Gfx wario_Face_DL_mesh_layer_1_opt_1[];
extern Gfx wario_Face_DL_mesh_layer_1_opt_2[];
extern Gfx wario_002_switch_option_face_happy_mesh_layer_1[];
extern Gfx wario_002_switch_option_face_happy_mesh_layer_1_opt_2[];
extern Gfx wario_002_switch_option_face_angry_mesh_layer_1[];
extern Gfx wario_002_switch_option_face_angry_mesh_layer_1_opt_2[];
extern Gfx wario_002_switch_option_face_o_mesh_layer_1[];
extern Gfx wario_002_switch_option_face_o_mesh_layer_1_opt_2[];
extern Gfx wario_002_switch_option_face_e_mesh_layer_1[];
extern Gfx wario_002_switch_option_face_e_mesh_layer_1_opt_2[];
extern Gfx wario_Left_Wing_DL_mesh_layer_1[];
extern Gfx wario_Left_Wing_DL_mesh_layer_1_opt_2[];
extern Gfx wario_Right_Wing_DL_mesh_layer_1[];
extern Gfx wario_Right_Wing_DL_mesh_layer_1_opt_2[];
extern Gfx wario_Left_Arm_Color_mesh_layer_1[];
extern Gfx wario_Left_Arm_Color_mesh_layer_1_opt_2[];
extern Gfx wario_Left_Forearm_mesh_layer_1[];
extern Gfx wario_Left_Forearm_mesh_layer_1_opt_2[];
extern Gfx wario_Left_Hand_DL_mesh_layer_1[];
extern Gfx wario_Left_Hand_DL_mesh_layer_1_opt_2[];
extern Gfx wario_002_switch_option_left_hand_open_mesh_layer_1[];
extern Gfx wario_002_switch_option_left_hand_open_mesh_layer_1_opt_2[];
extern Gfx wario_Right_Arm_Color_mesh_layer_1[];
extern Gfx wario_Right_Arm_Color_mesh_layer_1_opt_2[];
extern Gfx wario_Right_Forearm_mesh_layer_1[];
extern Gfx wario_Right_Forearm_mesh_layer_1_opt_2[];
extern Gfx wario_Right_Hand_DL_mesh_layer_1[];
extern Gfx wario_Right_Hand_DL_mesh_layer_1_opt_2[];
extern Gfx wario_002_switch_option_right_hand_open_mesh_layer_1[];
extern Gfx wario_002_switch_option_right_hand_open_mesh_layer_1_opt_2[];
extern Gfx wario_004_switch_option_right_hand_peace_mesh_layer_1[];
extern Gfx wario_004_switch_option_right_hand_peace_mesh_layer_1_opt_2[];
extern Gfx wario_005_switch_option_right_hand_cap_mesh_layer_1[];
extern Gfx wario_005_switch_option_right_hand_cap_mesh_layer_1_opt_2[];
extern Gfx wario_006_switch_option_right_hand_wing_cap_mesh_layer_1[];
extern Gfx wario_006_switch_option_right_hand_wing_cap_mesh_layer_1_opt_2[];
extern Gfx wario_Left_Thigh_Color_mesh_layer_1[];
extern Gfx wario_Left_Thigh_Color_mesh_layer_1_opt_2[];
extern Gfx wario_Left_Leg_mesh_layer_1[];
extern Gfx wario_Left_Leg_mesh_layer_1_opt_2[];
extern Gfx wario_Left_Shoe_mesh_layer_1[];
extern Gfx wario_Left_Shoe_mesh_layer_1_opt_2[];
extern Gfx wario_Right_Thigh_Color_mesh_layer_1[];
extern Gfx wario_Right_Thigh_Color_mesh_layer_1_opt_2[];
extern Gfx wario_Right_Leg_mesh_layer_1[];
extern Gfx wario_Right_Leg_mesh_layer_1_opt_2[];
extern Gfx wario_Right_Shoe_mesh_layer_1_with_layer_1_revert[];
extern Gfx wario_Right_Shoe_mesh_layer_1_opt_2_with_layer_1_revert[];
extern Gfx wario_Right_Shoe_mesh_layer_1_with_layer_5_revert[];
