extern const GeoLayout toad_player_head_capless[];
extern const GeoLayout toad_player_eyes_half_closed[];
extern const GeoLayout toad_player_eyes_closed[];
extern const GeoLayout toad_player_eyes_tiptoe[];
extern const GeoLayout toad_player_eyes_angry[];
extern const GeoLayout toad_player_eyes_happy[];
extern const GeoLayout toad_player_eyes_exhausted[];
extern const GeoLayout toad_player_eyes_dead[];
extern const GeoLayout toad_player_eyes_hurt[];
extern const GeoLayout toad_player_face_happy[];
extern const GeoLayout toad_player_face_angry[];
extern const GeoLayout toad_player_face_O[];
extern const GeoLayout toad_player_left_hand_open[];
extern const GeoLayout toad_player_right_hand_open[];
extern const GeoLayout toad_player_right_hand_peace[];
extern const GeoLayout toad_player_right_hand_cap[];
extern const GeoLayout toad_player_right_hand_wing_cap[];
extern const GeoLayout toad_player_geo_opt_1[];
extern const GeoLayout toad_player_geo_opt_2[];
extern const GeoLayout toad_player_head_capless_opt_1[];
extern const GeoLayout toad_player_eyes_half_closed_opt_1[];
extern const GeoLayout toad_player_eyes_closed_opt_1[];
extern const GeoLayout toad_player_eyes_tiptoe_opt_1[];
extern const GeoLayout toad_player_eyes_angry_opt_1[];
extern const GeoLayout toad_player_eyes_happy_opt_1[];
extern const GeoLayout toad_player_eyes_exhausted_opt_1[];
extern const GeoLayout toad_player_eyes_dead_opt_1[];
extern const GeoLayout toad_player_eyes_hurt_opt_1[];
extern const GeoLayout toad_player_geo_opt_1_1_opt_1_opt_1[];
extern const GeoLayout toad_player_geo_opt_1_1_opt_1_opt_2[];
extern const GeoLayout toad_player_face_happy_opt_1[];
extern const GeoLayout toad_player_face_angry_opt_1[];
extern const GeoLayout toad_player_face_O_opt_1[];
extern const GeoLayout toad_player_left_hand_open_opt_1[];
extern const GeoLayout toad_player_right_hand_open_opt_1[];
extern const GeoLayout toad_player_right_hand_peace_opt_1[];
extern const GeoLayout toad_player_right_hand_cap_opt_1[];
extern const GeoLayout toad_player_right_hand_wing_cap_opt_1[];
extern const GeoLayout toad_player_geo_opt_1_1[];
extern const GeoLayout toad_player_head_capless_opt_2[];
extern const GeoLayout toad_player_eyes_half_closed_opt_2[];
extern const GeoLayout toad_player_eyes_closed_opt_2[];
extern const GeoLayout toad_player_eyes_tiptoe_opt_2[];
extern const GeoLayout toad_player_eyes_angry_opt_2[];
extern const GeoLayout toad_player_eyes_happy_opt_2[];
extern const GeoLayout toad_player_eyes_exhausted_opt_2[];
extern const GeoLayout toad_player_eyes_dead_opt_2[];
extern const GeoLayout toad_player_eyes_hurt_opt_2[];
extern const GeoLayout toad_player_geo_opt_2_1_opt_2_opt_1[];
extern const GeoLayout toad_player_geo_opt_2_1_opt_2_opt_2[];
extern const GeoLayout toad_player_face_happy_opt_2[];
extern const GeoLayout toad_player_face_angry_opt_2[];
extern const GeoLayout toad_player_face_O_opt_2[];
extern const GeoLayout toad_player_left_hand_open_opt_2[];
extern const GeoLayout toad_player_right_hand_open_opt_2[];
extern const GeoLayout toad_player_right_hand_peace_opt_2[];
extern const GeoLayout toad_player_right_hand_cap_opt_2[];
extern const GeoLayout toad_player_right_hand_wing_cap_opt_2[];
extern const GeoLayout toad_player_geo_opt_2_1[];
extern const GeoLayout toad_player_head_capless_opt_3[];
extern const GeoLayout toad_player_eyes_half_closed_opt_3[];
extern const GeoLayout toad_player_eyes_closed_opt_3[];
extern const GeoLayout toad_player_eyes_tiptoe_opt_3[];
extern const GeoLayout toad_player_eyes_angry_opt_3[];
extern const GeoLayout toad_player_eyes_happy_opt_3[];
extern const GeoLayout toad_player_eyes_exhausted_opt_3[];
extern const GeoLayout toad_player_eyes_dead_opt_3[];
extern const GeoLayout toad_player_eyes_hurt_opt_3[];
extern const GeoLayout toad_player_geo_opt_3_opt_3_opt_1[];
extern const GeoLayout toad_player_geo_opt_3_opt_3_opt_2[];
extern const GeoLayout toad_player_face_happy_opt_3[];
extern const GeoLayout toad_player_face_angry_opt_3[];
extern const GeoLayout toad_player_face_O_opt_3[];
extern const GeoLayout toad_player_left_hand_open_opt_3[];
extern const GeoLayout toad_player_right_hand_open_opt_3[];
extern const GeoLayout toad_player_right_hand_peace_opt_3[];
extern const GeoLayout toad_player_right_hand_cap_opt_3[];
extern const GeoLayout toad_player_right_hand_wing_cap_opt_3[];
extern const GeoLayout toad_player_geo_opt_3[];
extern const GeoLayout toad_player_geo[];
extern Lights1 toad_player_toad_skin_lights;
extern Lights1 toad_player_toad_white_lights;
extern Lights1 toad_player_toad_vest_blue_lights;
extern Lights1 toad_player_toad_head_pattern_lights;
extern Lights1 toad_player_toad_eyes_lights;
extern Lights1 toad_player_toad_mouth_lights;
extern Lights1 toad_player_wings_lights;
extern Lights1 toad_player_shadow_lights;
extern Lights1 toad_player_toad_shoes_lights;
extern Lights1 toad_player_toad_soles_lights;
extern Lights1 toad_player_skin_lights;
extern Lights1 toad_player_newmetal_lights;
extern u8 toad_player_shine_dull_rgba32[];
extern u8 toad_player_toad_head_pattern_rgba32[];
extern u8 toad_player_mario_shine_rgba32[];
extern u8 toad_player_mario_metal_new_rgba16[];
extern Vtx toad_player_Torso_mesh_layer_1_vtx_0[276];
extern Gfx toad_player_Torso_mesh_layer_1_tri_0[];
extern Vtx toad_player_Torso_mesh_layer_1_vtx_1[729];
extern Gfx toad_player_Torso_mesh_layer_1_tri_1[];
extern Vtx toad_player_Torso_mesh_layer_1_vtx_2[1579];
extern Gfx toad_player_Torso_mesh_layer_1_tri_2[];
extern Vtx toad_player_Cap_DL_mesh_layer_1_vtx_0[1225];
extern Gfx toad_player_Cap_DL_mesh_layer_1_tri_0[];
extern Vtx toad_player_002_switch_option_head_hair_mesh_layer_1_vtx_0[48];
extern Gfx toad_player_002_switch_option_head_hair_mesh_layer_1_tri_0[];
extern Vtx toad_player_Eyes_DL_mesh_layer_1_vtx_0[614];
extern Gfx toad_player_Eyes_DL_mesh_layer_1_tri_0[];
extern Vtx toad_player_002_switch_option_eyes_half_closed_mesh_layer_1_vtx_0[614];
extern Gfx toad_player_002_switch_option_eyes_half_closed_mesh_layer_1_tri_0[];
extern Vtx toad_player_002_switch_option_eyes_closed_mesh_layer_1_vtx_0[614];
extern Gfx toad_player_002_switch_option_eyes_closed_mesh_layer_1_tri_0[];
extern Vtx toad_player_002_switch_option_eyes_half_open_mesh_layer_1_vtx_0[614];
extern Gfx toad_player_002_switch_option_eyes_half_open_mesh_layer_1_tri_0[];
extern Vtx toad_player_002_switch_option_eyes_angry_mesh_layer_1_vtx_0[362];
extern Gfx toad_player_002_switch_option_eyes_angry_mesh_layer_1_tri_0[];
extern Vtx toad_player_002_switch_option_eyes_happy_mesh_layer_1_vtx_0[614];
extern Gfx toad_player_002_switch_option_eyes_happy_mesh_layer_1_tri_0[];
extern Vtx toad_player_002_switch_option_eyes_exhausted_mesh_layer_1_vtx_0[364];
extern Gfx toad_player_002_switch_option_eyes_exhausted_mesh_layer_1_tri_0[];
extern Vtx toad_player_002_switch_option_eyes_dead_mesh_layer_1_vtx_0[364];
extern Gfx toad_player_002_switch_option_eyes_dead_mesh_layer_1_tri_0[];
extern Vtx toad_player_002_switch_option_eyes_hurt_mesh_layer_1_vtx_0[614];
extern Gfx toad_player_002_switch_option_eyes_hurt_mesh_layer_1_tri_0[];
extern Vtx toad_player_Face_DL_mesh_layer_1_vtx_0[2336];
extern Gfx toad_player_Face_DL_mesh_layer_1_tri_0[];
extern Vtx toad_player_Face_DL_mesh_layer_1_vtx_1[110];
extern Gfx toad_player_Face_DL_mesh_layer_1_tri_1[];
extern Vtx toad_player_002_switch_option_face_happy_mesh_layer_1_vtx_0[2168];
extern Gfx toad_player_002_switch_option_face_happy_mesh_layer_1_tri_0[];
extern Vtx toad_player_002_switch_option_face_happy_mesh_layer_1_vtx_1[83];
extern Gfx toad_player_002_switch_option_face_happy_mesh_layer_1_tri_1[];
extern Vtx toad_player_002_switch_option_face_angry_mesh_layer_1_vtx_0[2229];
extern Gfx toad_player_002_switch_option_face_angry_mesh_layer_1_tri_0[];
extern Vtx toad_player_002_switch_option_face_angry_mesh_layer_1_vtx_1[112];
extern Gfx toad_player_002_switch_option_face_angry_mesh_layer_1_tri_1[];
extern Vtx toad_player_002_switch_option_face_o_mesh_layer_1_vtx_0[2168];
extern Gfx toad_player_002_switch_option_face_o_mesh_layer_1_tri_0[];
extern Vtx toad_player_002_switch_option_face_o_mesh_layer_1_vtx_1[83];
extern Gfx toad_player_002_switch_option_face_o_mesh_layer_1_tri_1[];
extern Vtx toad_player_Left_Wing_DL_mesh_layer_1_vtx_0[2097];
extern Gfx toad_player_Left_Wing_DL_mesh_layer_1_tri_0[];
extern Vtx toad_player_Right_Wing_DL_mesh_layer_1_vtx_0[2142];
extern Gfx toad_player_Right_Wing_DL_mesh_layer_1_tri_0[];
extern Vtx toad_player_Left_Arm_Color_mesh_layer_1_vtx_0[998];
extern Gfx toad_player_Left_Arm_Color_mesh_layer_1_tri_0[];
extern Vtx toad_player_Left_Forearm_mesh_layer_1_vtx_0[998];
extern Gfx toad_player_Left_Forearm_mesh_layer_1_tri_0[];
extern Vtx toad_player_Left_Hand_DL_mesh_layer_1_vtx_0[624];
extern Gfx toad_player_Left_Hand_DL_mesh_layer_1_tri_0[];
extern Vtx toad_player_002_switch_option_left_hand_open_mesh_layer_1_vtx_0[617];
extern Gfx toad_player_002_switch_option_left_hand_open_mesh_layer_1_tri_0[];
extern Vtx toad_player_Right_Arm_Color_mesh_layer_1_vtx_0[1010];
extern Gfx toad_player_Right_Arm_Color_mesh_layer_1_tri_0[];
extern Vtx toad_player_Right_Forearm_mesh_layer_1_vtx_0[1010];
extern Gfx toad_player_Right_Forearm_mesh_layer_1_tri_0[];
extern Vtx toad_player_Right_Hand_DL_mesh_layer_1_vtx_0[655];
extern Gfx toad_player_Right_Hand_DL_mesh_layer_1_tri_0[];
extern Vtx toad_player_002_switch_option_right_hand_open_mesh_layer_1_vtx_0[620];
extern Gfx toad_player_002_switch_option_right_hand_open_mesh_layer_1_tri_0[];
extern Vtx toad_player_004_switch_option_right_hand_peace_mesh_layer_1_vtx_0[648];
extern Gfx toad_player_004_switch_option_right_hand_peace_mesh_layer_1_tri_0[];
extern Vtx toad_player_005_switch_option_right_hand_cap_mesh_layer_1_vtx_0[1222];
extern Gfx toad_player_005_switch_option_right_hand_cap_mesh_layer_1_tri_0[];
extern Vtx toad_player_005_switch_option_right_hand_cap_mesh_layer_1_vtx_1[655];
extern Gfx toad_player_005_switch_option_right_hand_cap_mesh_layer_1_tri_1[];
extern Vtx toad_player_005_switch_option_right_hand_cap_mesh_layer_1_vtx_2[64];
extern Gfx toad_player_005_switch_option_right_hand_cap_mesh_layer_1_tri_2[];
extern Vtx toad_player_006_switch_option_right_hand_wing_cap_mesh_layer_1_vtx_0[4237];
extern Gfx toad_player_006_switch_option_right_hand_wing_cap_mesh_layer_1_tri_0[];
extern Vtx toad_player_006_switch_option_right_hand_wing_cap_mesh_layer_1_vtx_1[1222];
extern Gfx toad_player_006_switch_option_right_hand_wing_cap_mesh_layer_1_tri_1[];
extern Vtx toad_player_006_switch_option_right_hand_wing_cap_mesh_layer_1_vtx_2[655];
extern Gfx toad_player_006_switch_option_right_hand_wing_cap_mesh_layer_1_tri_2[];
extern Vtx toad_player_006_switch_option_right_hand_wing_cap_mesh_layer_1_vtx_3[64];
extern Gfx toad_player_006_switch_option_right_hand_wing_cap_mesh_layer_1_tri_3[];
extern Vtx toad_player_Left_Shoe_mesh_layer_1_vtx_0[351];
extern Gfx toad_player_Left_Shoe_mesh_layer_1_tri_0[];
extern Vtx toad_player_Left_Shoe_mesh_layer_1_vtx_1[87];
extern Gfx toad_player_Left_Shoe_mesh_layer_1_tri_1[];
extern Vtx toad_player_Right_Shoe_DL_mesh_layer_1_vtx_0[349];
extern Gfx toad_player_Right_Shoe_DL_mesh_layer_1_tri_0[];
extern Vtx toad_player_Right_Shoe_DL_mesh_layer_1_vtx_1[86];
extern Gfx toad_player_Right_Shoe_DL_mesh_layer_1_tri_1[];
extern Gfx mat_toad_player_toad_skin[];
extern Gfx mat_revert_toad_player_toad_skin[];
extern Gfx mat_toad_player_toad_white[];
extern Gfx mat_revert_toad_player_toad_white[];
extern Gfx mat_toad_player_toad_vest_blue[];
extern Gfx mat_revert_toad_player_toad_vest_blue[];
extern Gfx mat_toad_player_toad_head_pattern[];
extern Gfx mat_revert_toad_player_toad_head_pattern[];
extern Gfx mat_toad_player_toad_eyes[];
extern Gfx mat_revert_toad_player_toad_eyes[];
extern Gfx mat_toad_player_toad_mouth[];
extern Gfx mat_revert_toad_player_toad_mouth[];
extern Gfx mat_toad_player_wings[];
extern Gfx mat_revert_toad_player_wings[];
extern Gfx mat_toad_player_shadow[];
extern Gfx mat_revert_toad_player_shadow[];
extern Gfx mat_toad_player_toad_shoes[];
extern Gfx mat_revert_toad_player_toad_shoes[];
extern Gfx mat_toad_player_toad_soles[];
extern Gfx mat_revert_toad_player_toad_soles[];
extern Gfx mat_toad_player_skin[];
extern Gfx mat_revert_toad_player_skin[];
extern Gfx mat_toad_player_newmetal[];
extern Gfx mat_revert_toad_player_newmetal[];
extern Gfx toad_player_Torso_mesh_layer_1[];
extern Gfx toad_player_Torso_mesh_layer_1_opt_1[];
extern Gfx toad_player_Torso_mesh_layer_1_opt_2[];
extern Gfx toad_player_Torso_mesh_layer_1_opt_3[];
extern Gfx toad_player_Cap_DL_mesh_layer_1[];
extern Gfx toad_player_Cap_DL_mesh_layer_1_opt_2[];
extern Gfx toad_player_002_switch_option_head_hair_mesh_layer_1[];
extern Gfx toad_player_002_switch_option_head_hair_mesh_layer_1_opt_2[];
extern Gfx toad_player_Eyes_DL_mesh_layer_1[];
extern Gfx toad_player_Eyes_DL_mesh_layer_1_opt_2[];
extern Gfx toad_player_002_switch_option_eyes_half_closed_mesh_layer_1[];
extern Gfx toad_player_002_switch_option_eyes_half_closed_mesh_layer_1_opt_2[];
extern Gfx toad_player_002_switch_option_eyes_closed_mesh_layer_1[];
extern Gfx toad_player_002_switch_option_eyes_closed_mesh_layer_1_opt_2[];
extern Gfx toad_player_002_switch_option_eyes_half_open_mesh_layer_1[];
extern Gfx toad_player_002_switch_option_eyes_half_open_mesh_layer_1_opt_2[];
extern Gfx toad_player_002_switch_option_eyes_angry_mesh_layer_1[];
extern Gfx toad_player_002_switch_option_eyes_angry_mesh_layer_1_opt_2[];
extern Gfx toad_player_002_switch_option_eyes_happy_mesh_layer_1[];
extern Gfx toad_player_002_switch_option_eyes_happy_mesh_layer_1_opt_2[];
extern Gfx toad_player_002_switch_option_eyes_exhausted_mesh_layer_1[];
extern Gfx toad_player_002_switch_option_eyes_exhausted_mesh_layer_1_opt_2[];
extern Gfx toad_player_002_switch_option_eyes_dead_mesh_layer_1[];
extern Gfx toad_player_002_switch_option_eyes_dead_mesh_layer_1_opt_2[];
extern Gfx toad_player_002_switch_option_eyes_hurt_mesh_layer_1[];
extern Gfx toad_player_002_switch_option_eyes_hurt_mesh_layer_1_opt_2[];
extern Gfx toad_player_Face_DL_mesh_layer_1[];
extern Gfx toad_player_Face_DL_mesh_layer_1_opt_2[];
extern Gfx toad_player_002_switch_option_face_happy_mesh_layer_1[];
extern Gfx toad_player_002_switch_option_face_happy_mesh_layer_1_opt_2[];
extern Gfx toad_player_002_switch_option_face_angry_mesh_layer_1[];
extern Gfx toad_player_002_switch_option_face_angry_mesh_layer_1_opt_2[];
extern Gfx toad_player_002_switch_option_face_o_mesh_layer_1[];
extern Gfx toad_player_002_switch_option_face_o_mesh_layer_1_opt_2[];
extern Gfx toad_player_Left_Wing_DL_mesh_layer_1[];
extern Gfx toad_player_Left_Wing_DL_mesh_layer_1_opt_2[];
extern Gfx toad_player_Right_Wing_DL_mesh_layer_1[];
extern Gfx toad_player_Right_Wing_DL_mesh_layer_1_opt_2[];
extern Gfx toad_player_Left_Arm_Color_mesh_layer_1[];
extern Gfx toad_player_Left_Arm_Color_mesh_layer_1_opt_2[];
extern Gfx toad_player_Left_Forearm_mesh_layer_1[];
extern Gfx toad_player_Left_Forearm_mesh_layer_1_opt_2[];
extern Gfx toad_player_Left_Hand_DL_mesh_layer_1[];
extern Gfx toad_player_Left_Hand_DL_mesh_layer_1_opt_2[];
extern Gfx toad_player_002_switch_option_left_hand_open_mesh_layer_1[];
extern Gfx toad_player_002_switch_option_left_hand_open_mesh_layer_1_opt_2[];
extern Gfx toad_player_Right_Arm_Color_mesh_layer_1[];
extern Gfx toad_player_Right_Arm_Color_mesh_layer_1_opt_2[];
extern Gfx toad_player_Right_Forearm_mesh_layer_1[];
extern Gfx toad_player_Right_Forearm_mesh_layer_1_opt_2[];
extern Gfx toad_player_Right_Hand_DL_mesh_layer_1[];
extern Gfx toad_player_Right_Hand_DL_mesh_layer_1_opt_2[];
extern Gfx toad_player_002_switch_option_right_hand_open_mesh_layer_1[];
extern Gfx toad_player_002_switch_option_right_hand_open_mesh_layer_1_opt_2[];
extern Gfx toad_player_004_switch_option_right_hand_peace_mesh_layer_1[];
extern Gfx toad_player_004_switch_option_right_hand_peace_mesh_layer_1_opt_2[];
extern Gfx toad_player_005_switch_option_right_hand_cap_mesh_layer_1[];
extern Gfx toad_player_005_switch_option_right_hand_cap_mesh_layer_1_opt_2[];
extern Gfx toad_player_006_switch_option_right_hand_wing_cap_mesh_layer_1[];
extern Gfx toad_player_006_switch_option_right_hand_wing_cap_mesh_layer_1_opt_2[];
extern Gfx toad_player_Left_Shoe_mesh_layer_1[];
extern Gfx toad_player_Left_Shoe_mesh_layer_1_opt_2[];
extern Gfx toad_player_Right_Shoe_DL_mesh_layer_1_with_layer_1_revert[];
extern Gfx toad_player_Right_Shoe_DL_mesh_layer_1_opt_2_with_layer_1_revert[];
extern Gfx toad_player_Right_Shoe_DL_mesh_layer_1_opt_3_with_layer_1_revert[];
extern Gfx toad_player_Right_Shoe_DL_mesh_layer_1_with_layer_5_revert[];
