extern const GeoLayout boo_low_poly_booframe1_001[];
extern const GeoLayout boo_low_poly_booframe2_001[];
extern const GeoLayout boo_low_poly_booframe3_001[];
extern const GeoLayout boo_low_poly_booframe4_001[];
extern const GeoLayout boo_low_poly_001_switch_opt1_jump_boo_low_poly_booframe1_001[];
extern const GeoLayout boo_low_poly_001_switch_opt1_jump_boo_low_poly_booframe2_001[];
extern const GeoLayout boo_low_poly_001_switch_opt1_jump_boo_low_poly_booframe3_001[];
extern const GeoLayout boo_low_poly_001_switch_opt1_jump_boo_low_poly_booframe4_001[];
extern const GeoLayout boo_low_poly_001_switch_opt1[];
extern const GeoLayout boo_low_poly_geo[];
extern Lights1 boo_low_poly_boo_body_001_lights;
extern Lights1 boo_low_poly_boo_mouth_txt_lights;
extern Lights1 boo_low_poly_boo_eyes_txt_lights;
extern Lights1 boo_low_poly_boo_mouth1_txt_lights;
extern Lights1 boo_low_poly_boo_mouth2_txt_lights;
extern Lights1 boo_low_poly_boo_mouth3_txt_lights;
extern Lights1 boo_low_poly_boo_eyes2_txt_lights;
extern Lights1 boo_low_poly_boo_eyes3_txt_lights;
extern u8 boo_low_poly_Boo_mouth1_rgba16[];
extern u8 boo_low_poly_Boo_eyes1_rgba16[];
extern u8 boo_low_poly_Boo_mouth2_ci8[];
extern u8 boo_low_poly_Boo_mouth2_pal_rgba16[];
extern u8 boo_low_poly_Boo_mouth3_ci4[];
extern u8 boo_low_poly_Boo_mouth3_pal_rgba16[];
extern u8 boo_low_poly_Boo_mouth4_rgba16[];
extern u8 boo_low_poly_Boo_eyes2_ci8[];
extern u8 boo_low_poly_Boo_eyes2_pal_rgba16[];
extern u8 boo_low_poly_Boo_eyes3_rgba16[];
extern Vtx boo_low_poly_000_displaylist_mesh_layer_1_vtx_0[62];
extern Gfx boo_low_poly_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx boo_low_poly_000_displaylist_mesh_layer_1_vtx_1[11];
extern Gfx boo_low_poly_000_displaylist_mesh_layer_1_tri_1[];
extern Vtx boo_low_poly_000_displaylist_mesh_layer_1_vtx_2[9];
extern Gfx boo_low_poly_000_displaylist_mesh_layer_1_tri_2[];
extern Vtx boo_low_poly_001_switchmesh_frame1_mesh_layer_1_vtx_0[64];
extern Gfx boo_low_poly_001_switchmesh_frame1_mesh_layer_1_tri_0[];
extern Vtx boo_low_poly_001_switchmesh_frame1_mesh_layer_1_vtx_1[11];
extern Gfx boo_low_poly_001_switchmesh_frame1_mesh_layer_1_tri_1[];
extern Vtx boo_low_poly_001_switchmesh_frame1_mesh_layer_1_vtx_2[9];
extern Gfx boo_low_poly_001_switchmesh_frame1_mesh_layer_1_tri_2[];
extern Vtx boo_low_poly_001_switchmesh_frame2_mesh_layer_1_vtx_0[64];
extern Gfx boo_low_poly_001_switchmesh_frame2_mesh_layer_1_tri_0[];
extern Vtx boo_low_poly_001_switchmesh_frame2_mesh_layer_1_vtx_1[11];
extern Gfx boo_low_poly_001_switchmesh_frame2_mesh_layer_1_tri_1[];
extern Vtx boo_low_poly_001_switchmesh_frame2_mesh_layer_1_vtx_2[9];
extern Gfx boo_low_poly_001_switchmesh_frame2_mesh_layer_1_tri_2[];
extern Vtx boo_low_poly_001_switchmesh_frame3_mesh_layer_1_vtx_0[64];
extern Gfx boo_low_poly_001_switchmesh_frame3_mesh_layer_1_tri_0[];
extern Vtx boo_low_poly_001_switchmesh_frame3_mesh_layer_1_vtx_1[11];
extern Gfx boo_low_poly_001_switchmesh_frame3_mesh_layer_1_tri_1[];
extern Vtx boo_low_poly_001_switchmesh_frame3_mesh_layer_1_vtx_2[9];
extern Gfx boo_low_poly_001_switchmesh_frame3_mesh_layer_1_tri_2[];
extern Vtx boo_low_poly_001_switch_frame4_mesh_layer_1_vtx_0[64];
extern Gfx boo_low_poly_001_switch_frame4_mesh_layer_1_tri_0[];
extern Vtx boo_low_poly_001_switch_frame4_mesh_layer_1_vtx_1[11];
extern Gfx boo_low_poly_001_switch_frame4_mesh_layer_1_tri_1[];
extern Vtx boo_low_poly_001_switch_frame4_mesh_layer_1_vtx_2[9];
extern Gfx boo_low_poly_001_switch_frame4_mesh_layer_1_tri_2[];
extern Gfx mat_boo_low_poly_boo_body_001[];
extern Gfx mat_revert_boo_low_poly_boo_body_001[];
extern Gfx mat_boo_low_poly_boo_mouth_txt[];
extern Gfx mat_revert_boo_low_poly_boo_mouth_txt[];
extern Gfx mat_boo_low_poly_boo_eyes_txt[];
extern Gfx mat_revert_boo_low_poly_boo_eyes_txt[];
extern Gfx mat_boo_low_poly_boo_mouth1_txt[];
extern Gfx mat_revert_boo_low_poly_boo_mouth1_txt[];
extern Gfx mat_boo_low_poly_boo_mouth2_txt[];
extern Gfx mat_revert_boo_low_poly_boo_mouth2_txt[];
extern Gfx mat_boo_low_poly_boo_mouth3_txt[];
extern Gfx mat_revert_boo_low_poly_boo_mouth3_txt[];
extern Gfx mat_boo_low_poly_boo_eyes2_txt[];
extern Gfx mat_revert_boo_low_poly_boo_eyes2_txt[];
extern Gfx mat_boo_low_poly_boo_eyes3_txt[];
extern Gfx mat_revert_boo_low_poly_boo_eyes3_txt[];
extern Gfx boo_low_poly_000_displaylist_mesh_layer_1[];
extern Gfx boo_low_poly_001_switchmesh_frame1_mesh_layer_1[];
extern Gfx boo_low_poly_001_switchmesh_frame2_mesh_layer_1[];
extern Gfx boo_low_poly_001_switchmesh_frame3_mesh_layer_1[];
extern Gfx boo_low_poly_001_switch_frame4_mesh_layer_1[];
