const GeoLayout goomba_lowpoly_goomba_lowpoly_eyes_closed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, goomba_lowpoly_eyes_closed_switch_eyes_closed_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, goomba_lowpoly_eyes_closed_switch_eyes_closed_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout goomba_lowpoly_goomba_lowpoly_eyes_dazed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, goomba_lowpoly_eyes_dazed_switch_eyes_dazed_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, goomba_lowpoly_eyes_dazed_switch_eyes_dazed_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout goomba_lowpoly_mouth_switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, goomba_lowpoly_mouth_mesh_layer_1_mat_override_MouthOpen_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout goomba_lowpoly_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_RENDER_RANGE(5000, 32767),
		GEO_OPEN_NODE(),
			GEO_SHADOW(0, 150, 100),
			GEO_OPEN_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, 0, 90, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_SCALE(LAYER_OPAQUE, 16384),
						GEO_OPEN_NODE(),
							GEO_SCALE(LAYER_OPAQUE, 16384),
							GEO_OPEN_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 269, 0, 0, -51, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, goomba_lowpoly_body_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 180, -240, 63, -90, 0, 141),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, goomba_lowpoly_foot_L_mesh_layer_1),
										GEO_CLOSE_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -100, -240, -163, -90, 0, 141),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, goomba_lowpoly_foot_R_mesh_layer_1),
										GEO_CLOSE_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 24, 215, -29, -2, 0, -1),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_SWITCH_CASE(3, geo_switch_state_1),
												GEO_OPEN_NODE(),
													GEO_NODE_START(),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_OPAQUE, goomba_lowpoly_eyes_mesh_layer_1),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, goomba_lowpoly_eyes_mesh_layer_5),
													GEO_CLOSE_NODE(),
													GEO_BRANCH(1, goomba_lowpoly_goomba_lowpoly_eyes_closed),
													GEO_BRANCH(1, goomba_lowpoly_goomba_lowpoly_eyes_dazed),
												GEO_CLOSE_NODE(),
												GEO_SWITCH_CASE(2, geo_switch_state_2),
												GEO_OPEN_NODE(),
													GEO_NODE_START(),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_OPAQUE, goomba_lowpoly_mouth_mesh_layer_1),
													GEO_CLOSE_NODE(),
													GEO_BRANCH(1, goomba_lowpoly_mouth_switch_opt1),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
