const GeoLayout ukiki_mario_hat[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ukiki_switch_head_dl1_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ukiki_switch_head_dl1_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout ukiki_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(1, 150, 80),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_OPAQUE, 16384),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 121, 11, ukiki_body_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ukiki_body_mesh_layer_5),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 99, -11, NULL),
						GEO_OPEN_NODE(),
							GEO_SWITCH_CASE(4, geo_switch_anim_state),
							GEO_OPEN_NODE(),
								GEO_NODE_START(),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, ukiki_head_dl_mesh_layer_1),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ukiki_head_dl_mesh_layer_5),
								GEO_CLOSE_NODE(),
								GEO_BRANCH(1, ukiki_mario_hat),
								GEO_BRANCH(1, ukiki_mario_hat),
								GEO_BRANCH(1, ukiki_mario_hat),
								GEO_BRANCH(1, ukiki_mario_hat),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 67, 69, -9, 0, -90, -179),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, ukiki_left_shoulder_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ukiki_left_shoulder_mesh_layer_5),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 88, 0, 0, 0, -1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, ukiki_left_elbow_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ukiki_left_elbow_mesh_layer_5),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 57, 0, ukiki_left_wrist_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ukiki_left_wrist_mesh_layer_5),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -66, 69, -9, 0, 90, 179),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, ukiki_right_shoulder_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ukiki_right_shoulder_mesh_layer_5),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 88, 0, 0, 0, 1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, ukiki_right_elbow_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ukiki_right_elbow_mesh_layer_5),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 57, 0, ukiki_right_wrist_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ukiki_right_wrist_mesh_layer_5),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, -15, -57, -174, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, ukiki_tail_top_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ukiki_tail_top_mesh_layer_5),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, ukiki_tail_middle_skinned_mesh_layer_1),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ukiki_tail_middle_skinned_mesh_layer_5),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 45, -1, -6, 0, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, ukiki_tail_middle_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ukiki_tail_middle_mesh_layer_5),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, ukiki_tail_bottom_skinned_mesh_layer_1),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ukiki_tail_bottom_skinned_mesh_layer_5),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 46, 1, ukiki_tail_bottom_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ukiki_tail_bottom_mesh_layer_5),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 43, 99, 10, 0, -90, -172),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, ukiki_left_thigh_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ukiki_left_thigh_mesh_layer_5),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, ukiki_left_shin_skinned_mesh_layer_1),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ukiki_left_shin_skinned_mesh_layer_5),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 46, 0, 0, 0, -27),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, ukiki_left_shin_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ukiki_left_shin_mesh_layer_5),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 36, 0, 0, 0, 99),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, ukiki_left_foot_mesh_layer_1),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -43, 99, 10, 0, 90, 172),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, ukiki_right_thigh_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ukiki_right_thigh_mesh_layer_5),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, ukiki_right_shin_skinned_mesh_layer_1),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ukiki_right_shin_skinned_mesh_layer_5),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 46, 0, 0, 0, 27),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, ukiki_right_shin_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ukiki_right_shin_mesh_layer_5),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 36, 0, 0, 0, -99),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, ukiki_right_foot_mesh_layer_1),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
