const GeoLayout piranha_plant_fire_frame1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, piranha_plant_fire_000_switch_frame1_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout piranha_plant_fire_frame2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, piranha_plant_fire_000_switch_frame2_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout piranha_plant_fire_frame3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, piranha_plant_fire_000_switch_frame3_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout piranha_plant_fire_frame4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, piranha_plant_fire_000_switch_frame4_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout piranha_plant_fire_frame5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, piranha_plant_fire_000_switch_frame5_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout piranha_plant_fire_frame6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, piranha_plant_fire_000_switch_frame6_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout piranha_plant_fire_frame7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, piranha_plant_fire_000_switch_frame7_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout piranha_plant_fire_frame8[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, piranha_plant_fire_000_switch_frame8_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout piranha_plant_fire_frame9[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, piranha_plant_fire_000_switch_frame9_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout piranha_plant_fire_frame10[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, piranha_plant_fire_000_switch_frame10_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout piranha_plant_fire_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 155, 200),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 16, 4, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, piranha_plant_fire_000_offset_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, piranha_plant_fire_000_offset_001_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 54, 0, 0, piranha_plant_fire_000_offset_001_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, piranha_plant_fire_000_offset_002_skinned_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 181, 0, 0, piranha_plant_fire_000_offset_002_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, piranha_plant_fire_000_offset_003_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 180, 0, 0, piranha_plant_fire_000_offset_003_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, piranha_plant_fire_000_offset_005_skinned_mesh_layer_1),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 277, 49, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, piranha_plant_fire_000_offset_005_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(10, geo_switch_state_2),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, piranha_plant_fire_000_displaylist_mesh_layer_1),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, piranha_plant_fire_frame1),
												GEO_BRANCH(1, piranha_plant_fire_frame2),
												GEO_BRANCH(1, piranha_plant_fire_frame3),
												GEO_BRANCH(1, piranha_plant_fire_frame4),
												GEO_BRANCH(1, piranha_plant_fire_frame5),
												GEO_BRANCH(1, piranha_plant_fire_frame6),
												GEO_BRANCH(1, piranha_plant_fire_frame7),
												GEO_BRANCH(1, piranha_plant_fire_frame8),
												GEO_BRANCH(1, piranha_plant_fire_frame9),
												GEO_BRANCH(1, piranha_plant_fire_frame10),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 255, -2, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
										GEO_OPEN_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 58, 0, -40, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, piranha_plant_fire_000_offset_007_mesh_layer_1),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 58, 0, 43, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, piranha_plant_fire_000_offset_008_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
