const GeoLayout unagi_star[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SCALE(LAYER_OPAQUE, 16384),
		GEO_OPEN_NODE(),
        	GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 2000, 0, 0, 0, 0, 0, unagi_000_switch1_displaylist1_mesh_layer_1),
        	GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_ALPHA, 2000, 0, 0, 0, 0, 0, unagi_000_switch1_displaylist1_mesh_layer_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout unagi_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_CULLING_RADIUS(2000),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, unagi_000_offset_002_skinned_mesh_layer_1),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, unagi_000_offset_002_skinned_mesh_layer_5),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 245, 0, 0, unagi_000_offset_002_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, unagi_000_offset_002_mesh_layer_5),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, unagi_000_offset_003_skinned_mesh_layer_1),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, unagi_000_offset_003_skinned_mesh_layer_5),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 494, 0, 0, unagi_000_offset_003_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, unagi_000_offset_003_mesh_layer_5),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, unagi_000_offset_004_skinned_mesh_layer_1),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, unagi_000_offset_004_skinned_mesh_layer_5),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 475, 0, 0, unagi_000_offset_004_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, unagi_000_offset_004_mesh_layer_5),
									GEO_SWITCH_CASE(2, geo_switch_anim_state),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, unagi_star),
										GEO_BRANCH(1, unagi_star),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, unagi_000_offset_005_skinned_mesh_layer_1),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, unagi_000_offset_005_skinned_mesh_layer_5),
						GEO_ANIMATED_PART(LAYER_OPAQUE, -254, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, unagi_000_offset_005_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, unagi_000_offset_005_mesh_layer_5),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, unagi_000_offset_006_skinned_mesh_layer_1),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, unagi_000_offset_006_skinned_mesh_layer_5),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 527, 0, 0, unagi_000_offset_006_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, unagi_000_offset_006_mesh_layer_5),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 226, 65, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, unagi_000_offset_008_mesh_layer_1),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, unagi_001_offset_mesh_layer_1),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 527, 0, 0, unagi_002_offset_002_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 527, 0, 0, unagi_003_offset_mesh_layer_5),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, unagi_003_offset_mesh_layer_1),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 527, 0, 0, NULL),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
