const GeoLayout exclamation_box_000_switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, exclamation_box_000_displaylist_mesh_layer_1_mat_override_box_green_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout exclamation_box_000_switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, exclamation_box_000_displaylist_mesh_layer_1_mat_override_box_blue_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout exclamation_box_000_switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, exclamation_box_000_displaylist_mesh_layer_1_mat_override_box_yellow_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout exclamation_box_000_switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, exclamation_box_000_displaylist_mesh_layer_1_mat_override_box_green_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout exclamation_box_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_CULLING_RADIUS(255201),
		GEO_OPEN_NODE(),
			GEO_SHADOW(11, 180, 80),
			GEO_OPEN_NODE(),
				GEO_SCALE(LAYER_OPAQUE, 65536),
				GEO_OPEN_NODE(),
					GEO_SCALE(LAYER_OPAQUE, 16384),
					GEO_OPEN_NODE(),
						GEO_SWITCH_CASE(4, geo_switch_anim_state),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, exclamation_box_000_displaylist_mesh_layer_1),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, exclamation_box_000_switch_opt1),
							GEO_BRANCH(1, exclamation_box_000_switch_opt2),
							GEO_BRANCH(1, exclamation_box_000_switch_opt3),
							GEO_BRANCH(1, exclamation_box_000_switch_opt4),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
