extern const GeoLayout exclamation_box_000_switch_opt1[];
extern const GeoLayout exclamation_box_000_switch_opt2[];
extern const GeoLayout exclamation_box_000_switch_opt3[];
extern const GeoLayout exclamation_box_000_switch_opt4[];
extern const GeoLayout exclamation_box_geo[];
extern Lights1 exclamation_box_box_white_lights;
extern Lights1 exclamation_box_box_red_lights;
extern Lights1 exclamation_box_box_black_lights;
extern Lights1 exclamation_box_box_green_lights;
extern Lights1 exclamation_box_box_blue_lights;
extern Lights1 exclamation_box_box_yellow_lights;
extern u8 exclamation_box_shine_dull_rgba32[];
extern Vtx exclamation_box_000_displaylist_mesh_layer_1_vtx_0[1446];
extern Gfx exclamation_box_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx exclamation_box_000_displaylist_mesh_layer_1_vtx_1[360];
extern Gfx exclamation_box_000_displaylist_mesh_layer_1_tri_1[];
extern Vtx exclamation_box_000_displaylist_mesh_layer_1_vtx_2[48];
extern Gfx exclamation_box_000_displaylist_mesh_layer_1_tri_2[];
extern Gfx mat_exclamation_box_box_white[];
extern Gfx mat_revert_exclamation_box_box_white[];
extern Gfx mat_exclamation_box_box_red[];
extern Gfx mat_revert_exclamation_box_box_red[];
extern Gfx mat_exclamation_box_box_black[];
extern Gfx mat_revert_exclamation_box_box_black[];
extern Gfx mat_exclamation_box_box_green[];
extern Gfx mat_revert_exclamation_box_box_green[];
extern Gfx mat_exclamation_box_box_blue[];
extern Gfx mat_revert_exclamation_box_box_blue[];
extern Gfx mat_exclamation_box_box_yellow[];
extern Gfx mat_revert_exclamation_box_box_yellow[];
extern Gfx exclamation_box_000_displaylist_mesh_layer_1[];
extern Gfx exclamation_box_000_displaylist_mesh_layer_1_mat_override_box_green_0[];
extern Gfx exclamation_box_000_displaylist_mesh_layer_1_mat_override_box_blue_1[];
extern Gfx exclamation_box_000_displaylist_mesh_layer_1_mat_override_box_yellow_2[];
