extern const GeoLayout warios_cap_geo_opt_1[];
extern const GeoLayout warios_cap_geo[];
extern Lights1 warios_cap_wario_cap_lights;
extern Lights1 warios_cap_wario_emblem_lights;
extern Lights1 warios_cap_mario_cap_wings_lights;
extern Lights1 warios_cap_wario_cap_inside_lights;
extern u8 warios_cap_shine_dull_rgba32[];
extern Vtx warios_cap_000_displaylist_mesh_layer_1_vtx_0[687];
extern Gfx warios_cap_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx warios_cap_000_displaylist_mesh_layer_1_vtx_1[42];
extern Gfx warios_cap_000_displaylist_mesh_layer_1_tri_1[];
extern Vtx warios_cap_000_displaylist_mesh_layer_1_vtx_2[344];
extern Gfx warios_cap_000_displaylist_mesh_layer_1_tri_2[];
extern Vtx warios_cap_000_displaylist_mesh_layer_1_vtx_3[12];
extern Gfx warios_cap_000_displaylist_mesh_layer_1_tri_3[];
extern Gfx mat_warios_cap_wario_cap[];
extern Gfx mat_revert_warios_cap_wario_cap[];
extern Gfx mat_warios_cap_wario_emblem[];
extern Gfx mat_revert_warios_cap_wario_emblem[];
extern Gfx mat_warios_cap_mario_cap_wings[];
extern Gfx mat_revert_warios_cap_mario_cap_wings[];
extern Gfx mat_warios_cap_wario_cap_inside[];
extern Gfx mat_revert_warios_cap_wario_cap_inside[];
extern Gfx warios_cap_000_displaylist_mesh_layer_1_with_layer_1_revert[];
extern Gfx warios_cap_000_displaylist_mesh_layer_1_with_layer_5_revert[];
