extern const GeoLayout boo_big_booframe1[];
extern const GeoLayout boo_big_booframe2[];
extern const GeoLayout boo_big_booframe3[];
extern const GeoLayout boo_big_booframe4[];
extern const GeoLayout boo_big_001_switch_opt1_jump_boo_big_booframe1[];
extern const GeoLayout boo_big_001_switch_opt1_jump_boo_big_booframe2[];
extern const GeoLayout boo_big_001_switch_opt1_jump_boo_big_booframe3[];
extern const GeoLayout boo_big_001_switch_opt1_jump_boo_big_booframe4[];
extern const GeoLayout boo_big_001_switch_opt1[];
extern const GeoLayout boo_big_geo[];
extern Lights1 boo_big_boo_big_body_lights;
extern Lights1 boo_big_boo_big_mouth_lights;
extern Lights1 boo_big_boo_big_eyebrow_lights;
extern Lights1 boo_big_boo_big_eyes_lights;
extern Lights1 boo_big_boo_big_tounge_lights;
extern Lights1 boo_big_boo_big_teeth_lights;
extern Lights1 boo_big_boo_big_shadow_lights;
extern Lights1 boo_big_boo_blush_layer5_lights;
extern Lights1 boo_big_boo_blush_more_layer5_lights;
extern u8 boo_big_shine_dull_rgba32[];
extern u8 boo_big_shine_shiny_rgba32[];
extern u8 boo_big_boo_eye_shadow_rgba32[];
extern u8 boo_big_boo_big_eye_blush_rgba32[];
extern u8 boo_big_boo_big_eye_blush_more_rgba32[];
extern Vtx boo_big_000_displaylist_mesh_layer_1_vtx_0[2846];
extern Gfx boo_big_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx boo_big_000_displaylist_mesh_layer_1_vtx_1[224];
extern Gfx boo_big_000_displaylist_mesh_layer_1_tri_1[];
extern Vtx boo_big_000_displaylist_mesh_layer_1_vtx_2[788];
extern Gfx boo_big_000_displaylist_mesh_layer_1_tri_2[];
extern Vtx boo_big_000_displaylist_mesh_layer_1_vtx_3[248];
extern Gfx boo_big_000_displaylist_mesh_layer_1_tri_3[];
extern Vtx boo_big_000_displaylist_mesh_layer_1_vtx_4[85];
extern Gfx boo_big_000_displaylist_mesh_layer_1_tri_4[];
extern Vtx boo_big_000_displaylist_mesh_layer_1_vtx_5[558];
extern Gfx boo_big_000_displaylist_mesh_layer_1_tri_5[];
extern Vtx boo_big_000_displaylist_mesh_layer_5_vtx_0[40];
extern Gfx boo_big_000_displaylist_mesh_layer_5_tri_0[];
extern Vtx boo_big_001_switchmesh_frame1_mesh_layer_1_vtx_0[2236];
extern Gfx boo_big_001_switchmesh_frame1_mesh_layer_1_tri_0[];
extern Vtx boo_big_001_switchmesh_frame1_mesh_layer_1_vtx_1[224];
extern Gfx boo_big_001_switchmesh_frame1_mesh_layer_1_tri_1[];
extern Vtx boo_big_001_switchmesh_frame1_mesh_layer_1_vtx_2[788];
extern Gfx boo_big_001_switchmesh_frame1_mesh_layer_1_tri_2[];
extern Vtx boo_big_001_switchmesh_frame1_mesh_layer_1_vtx_3[248];
extern Gfx boo_big_001_switchmesh_frame1_mesh_layer_1_tri_3[];
extern Vtx boo_big_001_switchmesh_frame1_mesh_layer_1_vtx_4[85];
extern Gfx boo_big_001_switchmesh_frame1_mesh_layer_1_tri_4[];
extern Vtx boo_big_001_switchmesh_frame1_mesh_layer_1_vtx_5[558];
extern Gfx boo_big_001_switchmesh_frame1_mesh_layer_1_tri_5[];
extern Vtx boo_big_001_switchmesh_frame1_mesh_layer_5_vtx_0[40];
extern Gfx boo_big_001_switchmesh_frame1_mesh_layer_5_tri_0[];
extern Vtx boo_big_001_switchmesh_frame2_mesh_layer_1_vtx_0[2236];
extern Gfx boo_big_001_switchmesh_frame2_mesh_layer_1_tri_0[];
extern Vtx boo_big_001_switchmesh_frame2_mesh_layer_1_vtx_1[224];
extern Gfx boo_big_001_switchmesh_frame2_mesh_layer_1_tri_1[];
extern Vtx boo_big_001_switchmesh_frame2_mesh_layer_1_vtx_2[788];
extern Gfx boo_big_001_switchmesh_frame2_mesh_layer_1_tri_2[];
extern Vtx boo_big_001_switchmesh_frame2_mesh_layer_1_vtx_3[248];
extern Gfx boo_big_001_switchmesh_frame2_mesh_layer_1_tri_3[];
extern Vtx boo_big_001_switchmesh_frame2_mesh_layer_5_vtx_0[40];
extern Gfx boo_big_001_switchmesh_frame2_mesh_layer_5_tri_0[];
extern Vtx boo_big_001_switchmesh_frame3_mesh_layer_1_vtx_0[2740];
extern Gfx boo_big_001_switchmesh_frame3_mesh_layer_1_tri_0[];
extern Vtx boo_big_001_switchmesh_frame3_mesh_layer_1_vtx_1[914];
extern Gfx boo_big_001_switchmesh_frame3_mesh_layer_1_tri_1[];
extern Vtx boo_big_001_switchmesh_frame3_mesh_layer_1_vtx_2[94];
extern Gfx boo_big_001_switchmesh_frame3_mesh_layer_1_tri_2[];
extern Vtx boo_big_001_switchmesh_frame3_mesh_layer_5_vtx_0[243];
extern Gfx boo_big_001_switchmesh_frame3_mesh_layer_5_tri_0[];
extern Vtx boo_big_001_switch_frame4_mesh_layer_1_vtx_0[2746];
extern Gfx boo_big_001_switch_frame4_mesh_layer_1_tri_0[];
extern Vtx boo_big_001_switch_frame4_mesh_layer_1_vtx_1[126];
extern Gfx boo_big_001_switch_frame4_mesh_layer_1_tri_1[];
extern Vtx boo_big_001_switch_frame4_mesh_layer_1_vtx_2[107];
extern Gfx boo_big_001_switch_frame4_mesh_layer_1_tri_2[];
extern Vtx boo_big_001_switch_frame4_mesh_layer_5_vtx_0[243];
extern Gfx boo_big_001_switch_frame4_mesh_layer_5_tri_0[];
extern Gfx mat_boo_big_boo_big[];
extern Gfx mat_boo_big_boo_big_body[];
extern Gfx mat_revert_boo_big_boo_big_body[];
extern Gfx mat_boo_big_boo_big_mouth[];
extern Gfx mat_revert_boo_big_boo_big_mouth[];
extern Gfx mat_boo_big_boo_big_eyebrow[];
extern Gfx mat_revert_boo_big_boo_big_eyebrow[];
extern Gfx mat_boo_big_boo_big_eyes[];
extern Gfx mat_revert_boo_big_boo_big_eyes[];
extern Gfx mat_boo_big_boo_big_tounge[];
extern Gfx mat_revert_boo_big_boo_big_tounge[];
extern Gfx mat_boo_big_boo_big_teeth[];
extern Gfx mat_revert_boo_big_boo_big_teeth[];
extern Gfx mat_boo_big_boo_big_shadow[];
extern Gfx mat_revert_boo_big_boo_big_shadow[];
extern Gfx mat_boo_big_boo_blush_layer5[];
extern Gfx mat_revert_boo_big_boo_blush_layer5[];
extern Gfx mat_boo_big_boo_blush_more_layer5[];
extern Gfx mat_revert_boo_big_boo_blush_more_layer5[];
extern Gfx boo_big_000_displaylist_mesh_layer_1[];
extern Gfx boo_big_000_displaylist_mesh_layer_5[];
extern Gfx boo_big_001_switchmesh_frame1_mesh_layer_1[];
extern Gfx boo_big_001_switchmesh_frame1_mesh_layer_5[];
extern Gfx boo_big_001_switchmesh_frame2_mesh_layer_1[];
extern Gfx boo_big_001_switchmesh_frame2_mesh_layer_5[];
extern Gfx boo_big_001_switchmesh_frame3_mesh_layer_1[];
extern Gfx boo_big_001_switchmesh_frame3_mesh_layer_5[];
extern Gfx boo_big_001_switch_frame4_mesh_layer_1[];
extern Gfx boo_big_001_switch_frame4_mesh_layer_5[];
