extern const GeoLayout marios_cap_geo_opt_1[];
extern const GeoLayout marios_cap_geo[];
extern Lights1 marios_cap_mario_cap_lights;
extern Lights1 marios_cap_mario_cap_wings_lights;
extern Lights1 marios_cap_mario_cap_inside_lights;
extern u8 marios_cap_shine_dull_rgba32[];
extern Vtx marios_cap_000_displaylist_mesh_layer_1_vtx_0[1009];
extern Gfx marios_cap_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx marios_cap_000_displaylist_mesh_layer_1_vtx_1[50];
extern Gfx marios_cap_000_displaylist_mesh_layer_1_tri_1[];
extern Vtx marios_cap_000_displaylist_mesh_layer_1_vtx_2[12];
extern Gfx marios_cap_000_displaylist_mesh_layer_1_tri_2[];
extern Gfx mat_marios_cap_mario_cap[];
extern Gfx mat_revert_marios_cap_mario_cap[];
extern Gfx mat_marios_cap_mario_cap_wings[];
extern Gfx mat_revert_marios_cap_mario_cap_wings[];
extern Gfx mat_marios_cap_mario_cap_inside[];
extern Gfx mat_revert_marios_cap_mario_cap_inside[];
extern Gfx marios_cap_000_displaylist_mesh_layer_1_with_layer_1_revert[];
extern Gfx marios_cap_000_displaylist_mesh_layer_1_with_layer_5_revert[];
