extern const GeoLayout cap_switch_001_switch_opt1[];
extern const GeoLayout cap_switch_001_switch_opt2[];
extern const GeoLayout cap_switch_001_switch_opt3[];
extern const GeoLayout cap_switch_geo[];
extern Lights1 cap_switch_cap_switch_red_lights;
extern Lights1 cap_switch_cap_switch_white_lights;
extern Lights1 cap_switch_cap_switch_green_lights;
extern Lights1 cap_switch_cap_switch_blue_lights;
extern u8 cap_switch_shine_dull_rgba32[];
extern Vtx cap_switch_000_displaylist_001_mesh_layer_1_vtx_0[448];
extern Gfx cap_switch_000_displaylist_001_mesh_layer_1_tri_0[];
extern Vtx cap_switch_000_displaylist_001_mesh_layer_1_vtx_1[303];
extern Gfx cap_switch_000_displaylist_001_mesh_layer_1_tri_1[];
extern Gfx mat_cap_switch_cap_switch_red[];
extern Gfx mat_revert_cap_switch_cap_switch_red[];
extern Gfx mat_cap_switch_cap_switch_white[];
extern Gfx mat_revert_cap_switch_cap_switch_white[];
extern Gfx mat_cap_switch_cap_switch_green[];
extern Gfx mat_revert_cap_switch_cap_switch_green[];
extern Gfx mat_cap_switch_cap_switch_blue[];
extern Gfx mat_revert_cap_switch_cap_switch_blue[];
extern Gfx cap_switch_000_displaylist_001_mesh_layer_1[];
extern Gfx cap_switch_000_displaylist_001_mesh_layer_1_mat_override_cap_switch_green_0[];
extern Gfx cap_switch_000_displaylist_001_mesh_layer_1_mat_override_cap_switch_blue_1[];
