extern const GeoLayout marios_wing_cap_001_switch_opt1[];
extern const GeoLayout marios_wing_cap_geo[];
extern Lights1 marios_wing_cap_mario_cap_wings_lights;
extern Lights1 marios_wing_cap_mario_cap_lights;
extern Lights1 marios_wing_cap_mario_cap_black_lights;
extern u8 marios_wing_cap_shine_dull_rgba32[];
extern Vtx marios_wing_cap_000_displaylist_mesh_layer_1_vtx_0[4300];
extern Gfx marios_wing_cap_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx marios_wing_cap_000_displaylist_mesh_layer_1_vtx_1[1009];
extern Gfx marios_wing_cap_000_displaylist_mesh_layer_1_tri_1[];
extern Vtx marios_wing_cap_000_displaylist_mesh_layer_1_vtx_2[12];
extern Gfx marios_wing_cap_000_displaylist_mesh_layer_1_tri_2[];
extern Gfx mat_marios_wing_cap_mario_cap_wings[];
extern Gfx mat_revert_marios_wing_cap_mario_cap_wings[];
extern Gfx mat_marios_wing_cap_mario_cap[];
extern Gfx mat_revert_marios_wing_cap_mario_cap[];
extern Gfx mat_marios_wing_cap_mario_cap_black[];
extern Gfx mat_revert_marios_wing_cap_mario_cap_black[];
extern Gfx marios_wing_cap_000_displaylist_mesh_layer_1[];
