const GeoLayout toad_geo_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 504, -148, 0, toad_000_offset_002_mesh_layer_1_opt_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout toad_geo_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 504, -148, 0, toad_000_offset_002_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout toad_geo_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 504, -148, 0, toad_000_offset_002_mesh_layer_1_opt_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout toad_geo_opt_4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 504, -148, 0, toad_000_offset_002_mesh_layer_1_opt_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout toad_geo_opt_1_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 230, 32, 0, toad_003_offset_mesh_layer_1_opt_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout toad_geo_opt_2_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 230, 32, 0, toad_003_offset_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout toad_geo_opt_3_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 230, 32, 0, toad_003_offset_mesh_layer_1_opt_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout toad_geo_opt_4_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 230, 32, 0, toad_003_offset_mesh_layer_1_opt_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout toad_geo_opt_1_2_opt_1_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 504, -148, 0, toad_000_offset_002_mesh_layer_1_opt_1_transparent),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout toad_geo_opt_1_2_opt_1_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 504, -148, 0, toad_000_offset_002_mesh_layer_1_opt_2_transparent),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout toad_geo_opt_1_2_opt_1_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 504, -148, 0, toad_000_offset_002_mesh_layer_1_opt_3_transparent),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout toad_geo_opt_1_2_opt_1_opt_4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 504, -148, 0, toad_000_offset_002_mesh_layer_1_opt_4_transparent),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout toad_geo_opt_1_2_opt_1_opt_1_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 230, 32, 0, toad_003_offset_mesh_layer_1_opt_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout toad_geo_opt_1_2_opt_1_opt_2_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 230, 32, 0, toad_003_offset_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout toad_geo_opt_1_2_opt_1_opt_3_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 230, 32, 0, toad_003_offset_mesh_layer_1_opt_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout toad_geo_opt_1_2_opt_1_opt_4_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 230, 32, 0, toad_003_offset_mesh_layer_1_opt_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout toad_geo_opt_1_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_NODE_START(),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, -23, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_SCALE(LAYER_TRANSPARENT, 16384),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 457, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_SWITCH_CASE(4, geo_switch_state_1),
							GEO_OPEN_NODE(),
								GEO_NODE_START(),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 504, -148, 0, toad_000_offset_002_mesh_layer_1_transparent),
								GEO_CLOSE_NODE(),
								GEO_BRANCH(1, toad_geo_opt_1_2_opt_1_opt_1),
								GEO_BRANCH(1, toad_geo_opt_1_2_opt_1_opt_2),
								GEO_BRANCH(1, toad_geo_opt_1_2_opt_1_opt_3),
								GEO_BRANCH(1, toad_geo_opt_1_2_opt_1_opt_4),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_SWITCH_CASE(4, geo_switch_state_2),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 230, 32, 0, toad_003_offset_mesh_layer_1),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, toad_geo_opt_1_2_opt_1_opt_1_1),
							GEO_BRANCH(1, toad_geo_opt_1_2_opt_1_opt_2_1),
							GEO_BRANCH(1, toad_geo_opt_1_2_opt_1_opt_3_1),
							GEO_BRANCH(1, toad_geo_opt_1_2_opt_1_opt_4_1),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 100, 32, 0, NULL),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 16, -58, 152, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 148, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 36, -100, 12, toad_000_offset_005_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 16, -58, -152, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 148, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 36, -100, -12, toad_000_offset_008_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 373, 25, 208, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 68, 0, 16, toad_000_offset_010_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 373, 25, -208, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 68, 0, -16, toad_000_offset_012_mesh_layer_1_with_layer_5_revert),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout toad_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_CULLING_RADIUS(850680),
		GEO_OPEN_NODE(),
			GEO_SHADOW(0, 150, 100),
			GEO_OPEN_NODE(),
				GEO_SCALE(LAYER_FORCE, 16384),
				GEO_OPEN_NODE(),
					GEO_ASM(10, geo_update_layer_transparency),
					GEO_SWITCH_CASE(2, geo_switch_anim_state),
					GEO_OPEN_NODE(),
						GEO_NODE_START(),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -23, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_SCALE(LAYER_FORCE, 16384),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 457, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_SWITCH_CASE(4, geo_switch_state_1),
												GEO_OPEN_NODE(),
													GEO_NODE_START(),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 504, -148, 0, toad_000_offset_002_mesh_layer_1),
													GEO_CLOSE_NODE(),
													GEO_BRANCH(1, toad_geo_opt_1),
													GEO_BRANCH(1, toad_geo_opt_2),
													GEO_BRANCH(1, toad_geo_opt_3),
													GEO_BRANCH(1, toad_geo_opt_4),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_SWITCH_CASE(4, geo_switch_state_2),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 230, 32, 0, toad_003_offset_mesh_layer_1),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, toad_geo_opt_1_1),
												GEO_BRANCH(1, toad_geo_opt_2_1),
												GEO_BRANCH(1, toad_geo_opt_3_1),
												GEO_BRANCH(1, toad_geo_opt_4_1),
											GEO_CLOSE_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 100, 32, 0, NULL),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 16, -58, 152, NULL),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 148, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 36, -100, 12, toad_000_offset_005_mesh_layer_1),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 16, -58, -152, NULL),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 148, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 36, -100, -12, toad_000_offset_008_mesh_layer_1),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 373, 25, 208, NULL),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 68, 0, 16, toad_000_offset_010_mesh_layer_1),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 373, 25, -208, NULL),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 68, 0, -16, toad_000_offset_012_mesh_layer_1_with_layer_1_revert),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_BRANCH(1, toad_geo_opt_1_2),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
