extern const GeoLayout toad_geo_opt_1[];
extern const GeoLayout toad_geo_opt_2[];
extern const GeoLayout toad_geo_opt_3[];
extern const GeoLayout toad_geo_opt_4[];
extern const GeoLayout toad_geo_opt_1_1[];
extern const GeoLayout toad_geo_opt_2_1[];
extern const GeoLayout toad_geo_opt_3_1[];
extern const GeoLayout toad_geo_opt_4_1[];
extern const GeoLayout toad_geo_opt_1_2_opt_1_opt_1[];
extern const GeoLayout toad_geo_opt_1_2_opt_1_opt_2[];
extern const GeoLayout toad_geo_opt_1_2_opt_1_opt_3[];
extern const GeoLayout toad_geo_opt_1_2_opt_1_opt_4[];
extern const GeoLayout toad_geo_opt_1_2_opt_1_opt_1_1[];
extern const GeoLayout toad_geo_opt_1_2_opt_1_opt_2_1[];
extern const GeoLayout toad_geo_opt_1_2_opt_1_opt_3_1[];
extern const GeoLayout toad_geo_opt_1_2_opt_1_opt_4_1[];
extern const GeoLayout toad_geo_opt_1_2[];
extern const GeoLayout toad_geo[];
extern Lights1 toad_toad_skin_lights;
extern Lights1 toad_toad_eyes_lights;
extern Lights1 toad_toad_mouth_lights;
extern Lights1 toad_toad_head_pattern_lights;
extern Lights1 toad_toad_vest_blue_lights;
extern Lights1 toad_toad_white_lights;
extern Lights1 toad_toad_shoes_lights;
extern Lights1 toad_toad_soles_lights;
extern Lights1 toad_toad_head_pattern_blue_lights;
extern Lights1 toad_toad_head_pattern_green_lights;
extern Lights1 toad_toad_head_pattern_purple_lights;
extern Lights1 toad_toad_head_pattern_yellow_lights;
extern Lights1 toad_toad_vest_green_lights;
extern Lights1 toad_toad_vest_purple_lights;
extern Lights1 toad_toad_vest_red_lights;
extern Lights1 toad_toad_vest_yellow_lights;
extern u8 toad_shine_dull_rgba32[];
extern u8 toad_toad_head_pattern_rgba32[];
extern u8 toad_toad_blue_rgba32[];
extern u8 toad_toad_green_rgba32[];
extern u8 toad_toad_purple_rgba32[];
extern u8 toad_toad_yellow_rgba32[];
extern Vtx toad_000_offset_002_mesh_layer_1_vtx_0[1932];
extern Gfx toad_000_offset_002_mesh_layer_1_tri_0[];
extern Vtx toad_000_offset_002_mesh_layer_1_vtx_1[614];
extern Gfx toad_000_offset_002_mesh_layer_1_tri_1[];
extern Vtx toad_000_offset_002_mesh_layer_1_vtx_2[110];
extern Gfx toad_000_offset_002_mesh_layer_1_tri_2[];
extern Vtx toad_000_offset_002_mesh_layer_1_vtx_3[1225];
extern Gfx toad_000_offset_002_mesh_layer_1_tri_3[];
extern Vtx toad_003_offset_mesh_layer_1_vtx_0[276];
extern Gfx toad_003_offset_mesh_layer_1_tri_0[];
extern Vtx toad_003_offset_mesh_layer_1_vtx_1[1623];
extern Gfx toad_003_offset_mesh_layer_1_tri_1[];
extern Vtx toad_003_offset_mesh_layer_1_vtx_2[729];
extern Gfx toad_003_offset_mesh_layer_1_tri_2[];
extern Vtx toad_000_offset_005_mesh_layer_1_vtx_0[349];
extern Gfx toad_000_offset_005_mesh_layer_1_tri_0[];
extern Vtx toad_000_offset_005_mesh_layer_1_vtx_1[86];
extern Gfx toad_000_offset_005_mesh_layer_1_tri_1[];
extern Vtx toad_000_offset_008_mesh_layer_1_vtx_0[349];
extern Gfx toad_000_offset_008_mesh_layer_1_tri_0[];
extern Vtx toad_000_offset_008_mesh_layer_1_vtx_1[86];
extern Gfx toad_000_offset_008_mesh_layer_1_tri_1[];
extern Vtx toad_000_offset_010_mesh_layer_1_vtx_0[2006];
extern Gfx toad_000_offset_010_mesh_layer_1_tri_0[];
extern Vtx toad_000_offset_012_mesh_layer_1_vtx_0[1952];
extern Gfx toad_000_offset_012_mesh_layer_1_tri_0[];
extern Gfx mat_toad_toad_skin[];
extern Gfx mat_revert_toad_toad_skin[];
extern Gfx mat_toad_toad_eyes[];
extern Gfx mat_revert_toad_toad_eyes[];
extern Gfx mat_toad_toad_mouth[];
extern Gfx mat_revert_toad_toad_mouth[];
extern Gfx mat_toad_toad_head_pattern[];
extern Gfx mat_revert_toad_toad_head_pattern[];
extern Gfx mat_toad_toad_vest_blue[];
extern Gfx mat_revert_toad_toad_vest_blue[];
extern Gfx mat_toad_toad_white[];
extern Gfx mat_revert_toad_toad_white[];
extern Gfx mat_toad_toad_shoes[];
extern Gfx mat_revert_toad_toad_shoes[];
extern Gfx mat_toad_toad_soles[];
extern Gfx mat_revert_toad_toad_soles[];
extern Gfx mat_toad_toad_head_pattern_blue[];
extern Gfx mat_revert_toad_toad_head_pattern_blue[];
extern Gfx mat_toad_toad_head_pattern_green[];
extern Gfx mat_revert_toad_toad_head_pattern_green[];
extern Gfx mat_toad_toad_head_pattern_purple[];
extern Gfx mat_revert_toad_toad_head_pattern_purple[];
extern Gfx mat_toad_toad_head_pattern_yellow[];
extern Gfx mat_revert_toad_toad_head_pattern_yellow[];
extern Gfx mat_toad_toad_vest_green[];
extern Gfx mat_revert_toad_toad_vest_green[];
extern Gfx mat_toad_toad_vest_purple[];
extern Gfx mat_revert_toad_toad_vest_purple[];
extern Gfx mat_toad_toad_vest_red[];
extern Gfx mat_revert_toad_toad_vest_red[];
extern Gfx mat_toad_toad_vest_yellow[];
extern Gfx mat_revert_toad_toad_vest_yellow[];
extern Gfx toad_000_offset_002_mesh_layer_1[];
extern Gfx toad_000_offset_002_mesh_layer_1_transparent[];
extern Gfx toad_000_offset_002_mesh_layer_1_opt_1[];
extern Gfx toad_000_offset_002_mesh_layer_1_opt_1_transparent[];
extern Gfx toad_000_offset_002_mesh_layer_1_opt_2[];
extern Gfx toad_000_offset_002_mesh_layer_1_opt_2_transparent[];
extern Gfx toad_000_offset_002_mesh_layer_1_opt_3[];
extern Gfx toad_000_offset_002_mesh_layer_1_opt_3_transparent[];
extern Gfx toad_000_offset_002_mesh_layer_1_opt_4[];
extern Gfx toad_000_offset_002_mesh_layer_1_opt_4_transparent[];
extern Gfx toad_003_offset_mesh_layer_1[];
extern Gfx toad_003_offset_mesh_layer_1_opt_1[];
extern Gfx toad_003_offset_mesh_layer_1_opt_2[];
extern Gfx toad_003_offset_mesh_layer_1_opt_3[];
extern Gfx toad_003_offset_mesh_layer_1_opt_4[];
extern Gfx toad_000_offset_005_mesh_layer_1[];
extern Gfx toad_000_offset_008_mesh_layer_1[];
extern Gfx toad_000_offset_010_mesh_layer_1[];
extern Gfx toad_000_offset_012_mesh_layer_1_with_layer_1_revert[];
extern Gfx toad_000_offset_012_mesh_layer_1_with_layer_5_revert[];
