const GeoLayout red_coin_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_RENDER_RANGE(-2048, 5000),
		GEO_OPEN_NODE(),
			GEO_SHADOW(0, 180, 50),
			GEO_OPEN_NODE(),
				GEO_SCALE(LAYER_OPAQUE, 16384),
				GEO_OPEN_NODE(),
					GEO_ASM(1, geo_rotate_coin),
					GEO_ROTATION_NODE(LAYER_OPAQUE, 0, 0, 0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, red_coin_000_displaylist_mesh_layer_1),
						GEO_DISPLAY_LIST(LAYER_ALPHA, red_coin_000_displaylist_mesh_layer_4),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_RENDER_RANGE(5000, 32000),
		GEO_OPEN_NODE(),
			GEO_BRANCH(1, red_coin_low_poly_geo),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
