extern const GeoLayout inner_workings_area_1_geo[];
extern const GeoLayout inner_workings_area_1[];
extern const Collision inner_workings_area_1_collision[];
extern const MacroObject inner_workings_area_1_macro_objs[];
extern Lights1 inner_workings_dl_Brick_Wall_lights;
extern Lights1 inner_workings_dl_Grate_Outline_lights;
extern Lights1 inner_workings_dl_Grate_lights;
extern Vtx inner_workings_dl_Level_mesh_layer_1_vtx_cull[8];
extern Vtx inner_workings_dl_Level_mesh_layer_1_vtx_0[356];
extern Gfx inner_workings_dl_Level_mesh_layer_1_tri_0[];
extern Vtx inner_workings_dl_Level_mesh_layer_1_vtx_1[100];
extern Gfx inner_workings_dl_Level_mesh_layer_1_tri_1[];
extern Vtx inner_workings_dl_Level_mesh_layer_1_vtx_2[30];
extern Gfx inner_workings_dl_Level_mesh_layer_1_tri_2[];
extern Gfx mat_inner_workings_dl_Brick_Wall[];
extern Gfx mat_revert_inner_workings_dl_Brick_Wall[];
extern Gfx mat_inner_workings_dl_Grate_Outline[];
extern Gfx mat_revert_inner_workings_dl_Grate_Outline[];
extern Gfx mat_inner_workings_dl_Grate[];
extern Gfx mat_revert_inner_workings_dl_Grate[];
extern Gfx inner_workings_dl_Level_mesh_layer_1[];
extern Gfx inner_workings_dl_material_revert_render_settings[];
