const GeoLayout luigi_head_capless[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_002_switch_option_head_hair_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_eyes_half_closed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_002_switch_option_eyes_half_closed_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_eyes_closed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_002_switch_option_eyes_closed_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_eyes_tiptoe[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_002_switch_option_eyes_half_open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_eyes_angry[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_002_switch_option_eyes_angry_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_eyes_happy[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_002_switch_option_eyes_happy_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_eyes_exhausted[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_002_switch_option_eyes_exhausted_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_eyes_dead[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_002_switch_option_eyes_dead_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_eyes_hurt[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_002_switch_option_eyes_hurt_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_face_happy[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_002_switch_option_face_happy_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_face_angry[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_002_switch_option_face_angry_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_face_O[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_002_switch_option_face_o_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_left_hand_open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 320, 0, 0, luigi_002_switch_option_left_hand_open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_right_hand_open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 320, 0, 0, luigi_002_switch_option_right_hand_open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 262144),
			GEO_OPEN_NODE(),
				GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_right_hand_peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 320, 0, 0, luigi_004_switch_option_right_hand_peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_right_hand_cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 320, 0, 0, luigi_005_switch_option_right_hand_cap_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_right_hand_wing_cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 320, 0, 0, luigi_006_switch_option_right_hand_wing_cap_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_geo_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_Face_DL_mesh_layer_1_opt_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_geo_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_Face_DL_mesh_layer_1_opt_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_head_capless_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_002_switch_option_head_hair_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_eyes_half_closed_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_002_switch_option_eyes_half_closed_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_eyes_closed_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_002_switch_option_eyes_closed_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_eyes_tiptoe_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_002_switch_option_eyes_half_open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_eyes_angry_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_002_switch_option_eyes_angry_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_eyes_happy_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_002_switch_option_eyes_happy_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_eyes_exhausted_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_002_switch_option_eyes_exhausted_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_eyes_dead_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_002_switch_option_eyes_dead_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_eyes_hurt_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_002_switch_option_eyes_hurt_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_geo_opt_1_1_opt_1_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_Face_DL_mesh_layer_1_opt_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_geo_opt_1_1_opt_1_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_Face_DL_mesh_layer_1_opt_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_face_happy_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_002_switch_option_face_happy_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_face_angry_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_002_switch_option_face_angry_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_face_O_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_002_switch_option_face_o_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_left_hand_open_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 320, 0, 0, luigi_002_switch_option_left_hand_open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_right_hand_open_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 320, 0, 0, luigi_002_switch_option_right_hand_open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_TRANSPARENT, 262144),
			GEO_OPEN_NODE(),
				GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_right_hand_peace_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 320, 0, 0, luigi_004_switch_option_right_hand_peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_right_hand_cap_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 320, 0, 0, luigi_005_switch_option_right_hand_cap_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_right_hand_wing_cap_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 320, 0, 0, luigi_006_switch_option_right_hand_wing_cap_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_geo_opt_1_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_TRANSPARENT, 16384),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_TRANSPARENT, 168, 32, 0, 0, 0, 0),
					GEO_OPEN_NODE(),
						GEO_ASM(0, geo_move_mario_part_from_parent),
						GEO_ASM(0, geo_mario_tilt_torso),
						GEO_ROTATION_NODE(LAYER_TRANSPARENT, 0, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, luigi_Torso_mesh_layer_1_opt_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 552, -32, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_head_rotation),
									GEO_ROTATION_NODE(LAYER_TRANSPARENT, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_Cap_DL_mesh_layer_1),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, luigi_head_capless_opt_1),
										GEO_CLOSE_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eye_custom),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_Eyes_DL_mesh_layer_1),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, luigi_eyes_half_closed_opt_1),
											GEO_BRANCH(1, luigi_eyes_closed_opt_1),
											GEO_BRANCH(1, luigi_eyes_tiptoe_opt_1),
											GEO_BRANCH(1, luigi_eyes_angry_opt_1),
											GEO_BRANCH(1, luigi_eyes_happy_opt_1),
											GEO_BRANCH(1, luigi_eyes_exhausted_opt_1),
											GEO_BRANCH(1, luigi_eyes_dead_opt_1),
											GEO_BRANCH(1, luigi_eyes_hurt_opt_1),
										GEO_CLOSE_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_face),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_Face_DL_mesh_layer_1),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, luigi_geo_opt_1_1_opt_1_opt_1),
											GEO_BRANCH(1, luigi_geo_opt_1_1_opt_1_opt_2),
											GEO_BRANCH(1, luigi_face_happy_opt_1),
											GEO_BRANCH(1, luigi_face_angry_opt_1),
											GEO_BRANCH(1, luigi_face_O_opt_1),
										GEO_CLOSE_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_TRANSPARENT, 597, -168, 211, -15, 33, -133),
										GEO_OPEN_NODE(),
											GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
											GEO_ROTATION_NODE(LAYER_TRANSPARENT, 0, 0, 0),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_Left_Wing_DL_mesh_layer_1),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_TRANSPARENT, 597, -168, -211, 14, -32, -133),
										GEO_OPEN_NODE(),
											GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
											GEO_ROTATION_NODE(LAYER_TRANSPARENT, 0, 0, 0),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_Right_Wing_DL_mesh_layer_1),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 376, -72, 232, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, luigi_Left_Arm_Color_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_TRANSPARENT, 240, 0, 0, luigi_Left_Forearm_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(1, geo_switch_mario_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_TRANSPARENT, 300, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(1, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_TRANSPARENT, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_Left_Hand_DL_mesh_layer_1),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, luigi_left_hand_open_opt_1),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 376, -72, -232, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, luigi_Right_Arm_Color_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_TRANSPARENT, 240, 0, 0, luigi_Right_Forearm_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(0, geo_switch_mario_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_TRANSPARENT, 300, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(0, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_TRANSPARENT, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_Right_Hand_DL_mesh_layer_1),
														GEO_CLOSE_NODE(),
														GEO_SCALE(LAYER_TRANSPARENT, 243719),
														GEO_OPEN_NODE(),
															GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, luigi_right_hand_open_opt_1),
												GEO_BRANCH(1, luigi_right_hand_peace_opt_1),
												GEO_BRANCH(1, luigi_right_hand_cap_opt_1),
												GEO_BRANCH(1, luigi_right_hand_wing_cap_opt_1),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 92, -32, 152, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, luigi_Left_Thigh_Color_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 396, 0, 0, luigi_Left_Leg_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 268, 0, 0, luigi_Left_Shoe_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 92, -32, -152, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, luigi_Right_Thigh_Color_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 396, 0, 0, luigi_Right_Leg_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 268, 0, 0, luigi_Right_Shoe_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ASM(2, geo_mario_hand_foot_scaler),
									GEO_SCALE(LAYER_TRANSPARENT, 65536),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_Right_Shoe_DL_mesh_layer_1_with_layer_5_revert),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_head_capless_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_002_switch_option_head_hair_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_eyes_half_closed_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_002_switch_option_eyes_half_closed_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_eyes_closed_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_002_switch_option_eyes_closed_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_eyes_tiptoe_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_002_switch_option_eyes_half_open_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_eyes_angry_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_002_switch_option_eyes_angry_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_eyes_happy_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_002_switch_option_eyes_happy_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_eyes_exhausted_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_002_switch_option_eyes_exhausted_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_eyes_dead_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_002_switch_option_eyes_dead_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_eyes_hurt_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_002_switch_option_eyes_hurt_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_geo_opt_2_1_opt_2_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_Face_DL_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_geo_opt_2_1_opt_2_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_Face_DL_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_face_happy_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_002_switch_option_face_happy_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_face_angry_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_002_switch_option_face_angry_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_face_O_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_002_switch_option_face_o_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_left_hand_open_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 320, 0, 0, luigi_002_switch_option_left_hand_open_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_right_hand_open_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 320, 0, 0, luigi_002_switch_option_right_hand_open_mesh_layer_1_opt_2),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 262144),
			GEO_OPEN_NODE(),
				GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_right_hand_peace_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 320, 0, 0, luigi_004_switch_option_right_hand_peace_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_right_hand_cap_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 320, 0, 0, luigi_005_switch_option_right_hand_cap_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_right_hand_wing_cap_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 320, 0, 0, luigi_006_switch_option_right_hand_wing_cap_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_geo_opt_2_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_FORCE, 168, 32, 0, 0, 0, 0),
					GEO_OPEN_NODE(),
						GEO_ASM(0, geo_move_mario_part_from_parent),
						GEO_ASM(0, geo_mario_tilt_torso),
						GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, luigi_Torso_mesh_layer_1_opt_2),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 552, -32, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_head_rotation),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_Cap_DL_mesh_layer_1_opt_2),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, luigi_head_capless_opt_2),
										GEO_CLOSE_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eye_custom),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_Eyes_DL_mesh_layer_1_opt_2),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, luigi_eyes_half_closed_opt_2),
											GEO_BRANCH(1, luigi_eyes_closed_opt_2),
											GEO_BRANCH(1, luigi_eyes_tiptoe_opt_2),
											GEO_BRANCH(1, luigi_eyes_angry_opt_2),
											GEO_BRANCH(1, luigi_eyes_happy_opt_2),
											GEO_BRANCH(1, luigi_eyes_exhausted_opt_2),
											GEO_BRANCH(1, luigi_eyes_dead_opt_2),
											GEO_BRANCH(1, luigi_eyes_hurt_opt_2),
										GEO_CLOSE_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_face),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_Face_DL_mesh_layer_1_opt_2),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, luigi_geo_opt_2_1_opt_2_opt_1),
											GEO_BRANCH(1, luigi_geo_opt_2_1_opt_2_opt_2),
											GEO_BRANCH(1, luigi_face_happy_opt_2),
											GEO_BRANCH(1, luigi_face_angry_opt_2),
											GEO_BRANCH(1, luigi_face_O_opt_2),
										GEO_CLOSE_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_FORCE, 597, -168, 211, -15, 33, -133),
										GEO_OPEN_NODE(),
											GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
											GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_Left_Wing_DL_mesh_layer_1_opt_2),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_FORCE, 597, -168, -211, 14, -32, -133),
										GEO_OPEN_NODE(),
											GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
											GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_Right_Wing_DL_mesh_layer_1_opt_2),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 376, -72, 232, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, luigi_Left_Arm_Color_mesh_layer_1_opt_2),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 240, 0, 0, luigi_Left_Forearm_mesh_layer_1_opt_2),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(1, geo_switch_mario_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 300, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(1, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_Left_Hand_DL_mesh_layer_1_opt_2),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, luigi_left_hand_open_opt_2),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 376, -72, -232, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, luigi_Right_Arm_Color_mesh_layer_1_opt_2),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 240, 0, 0, luigi_Right_Forearm_mesh_layer_1_opt_2),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(0, geo_switch_mario_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 300, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(0, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_Right_Hand_DL_mesh_layer_1_opt_2),
														GEO_CLOSE_NODE(),
														GEO_SCALE(LAYER_FORCE, 243719),
														GEO_OPEN_NODE(),
															GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, luigi_right_hand_open_opt_2),
												GEO_BRANCH(1, luigi_right_hand_peace_opt_2),
												GEO_BRANCH(1, luigi_right_hand_cap_opt_2),
												GEO_BRANCH(1, luigi_right_hand_wing_cap_opt_2),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 92, -32, 152, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, luigi_Left_Thigh_Color_mesh_layer_1_opt_2),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 396, 0, 0, luigi_Left_Leg_mesh_layer_1_opt_2),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 268, 0, 0, luigi_Left_Shoe_mesh_layer_1_opt_2),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 92, -32, -152, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, luigi_Right_Thigh_Color_mesh_layer_1_opt_2),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 396, 0, 0, luigi_Right_Leg_mesh_layer_1_opt_2),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 268, 0, 0, luigi_Right_Shoe_mesh_layer_1_opt_2),
								GEO_OPEN_NODE(),
									GEO_ASM(2, geo_mario_hand_foot_scaler),
									GEO_SCALE(LAYER_FORCE, 65536),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_Right_Shoe_DL_mesh_layer_1_opt_2_with_layer_1_revert),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_head_capless_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_002_switch_option_head_hair_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_eyes_half_closed_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_002_switch_option_eyes_half_closed_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_eyes_closed_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_002_switch_option_eyes_closed_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_eyes_tiptoe_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_002_switch_option_eyes_half_open_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_eyes_angry_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_002_switch_option_eyes_angry_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_eyes_happy_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_002_switch_option_eyes_happy_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_eyes_exhausted_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_002_switch_option_eyes_exhausted_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_eyes_dead_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_002_switch_option_eyes_dead_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_eyes_hurt_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_002_switch_option_eyes_hurt_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_geo_opt_3_opt_3_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_Face_DL_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_geo_opt_3_opt_3_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_Face_DL_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_face_happy_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_002_switch_option_face_happy_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_face_angry_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_002_switch_option_face_angry_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_face_O_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_002_switch_option_face_o_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_left_hand_open_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 320, 0, 0, luigi_002_switch_option_left_hand_open_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_right_hand_open_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 320, 0, 0, luigi_002_switch_option_right_hand_open_mesh_layer_1_opt_2),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_TRANSPARENT, 262144),
			GEO_OPEN_NODE(),
				GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_right_hand_peace_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 320, 0, 0, luigi_004_switch_option_right_hand_peace_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_right_hand_cap_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 320, 0, 0, luigi_005_switch_option_right_hand_cap_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_right_hand_wing_cap_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 320, 0, 0, luigi_006_switch_option_right_hand_wing_cap_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_geo_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_TRANSPARENT, 16384),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_TRANSPARENT, 168, 32, 0, 0, 0, 0),
					GEO_OPEN_NODE(),
						GEO_ASM(0, geo_move_mario_part_from_parent),
						GEO_ASM(0, geo_mario_tilt_torso),
						GEO_ROTATION_NODE(LAYER_TRANSPARENT, 0, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, luigi_Torso_mesh_layer_1_opt_3),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 552, -32, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_head_rotation),
									GEO_ROTATION_NODE(LAYER_TRANSPARENT, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_Cap_DL_mesh_layer_1_opt_2),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, luigi_head_capless_opt_3),
										GEO_CLOSE_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eye_custom),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_Eyes_DL_mesh_layer_1_opt_2),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, luigi_eyes_half_closed_opt_3),
											GEO_BRANCH(1, luigi_eyes_closed_opt_3),
											GEO_BRANCH(1, luigi_eyes_tiptoe_opt_3),
											GEO_BRANCH(1, luigi_eyes_angry_opt_3),
											GEO_BRANCH(1, luigi_eyes_happy_opt_3),
											GEO_BRANCH(1, luigi_eyes_exhausted_opt_3),
											GEO_BRANCH(1, luigi_eyes_dead_opt_3),
											GEO_BRANCH(1, luigi_eyes_hurt_opt_3),
										GEO_CLOSE_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_face),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_Face_DL_mesh_layer_1_opt_2),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, luigi_geo_opt_3_opt_3_opt_1),
											GEO_BRANCH(1, luigi_geo_opt_3_opt_3_opt_2),
											GEO_BRANCH(1, luigi_face_happy_opt_3),
											GEO_BRANCH(1, luigi_face_angry_opt_3),
											GEO_BRANCH(1, luigi_face_O_opt_3),
										GEO_CLOSE_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_TRANSPARENT, 597, -168, 211, -15, 33, -133),
										GEO_OPEN_NODE(),
											GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
											GEO_ROTATION_NODE(LAYER_TRANSPARENT, 0, 0, 0),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_Left_Wing_DL_mesh_layer_1_opt_2),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_TRANSPARENT, 597, -168, -211, 14, -32, -133),
										GEO_OPEN_NODE(),
											GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
											GEO_ROTATION_NODE(LAYER_TRANSPARENT, 0, 0, 0),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_Right_Wing_DL_mesh_layer_1_opt_2),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 376, -72, 232, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, luigi_Left_Arm_Color_mesh_layer_1_opt_2),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_TRANSPARENT, 240, 0, 0, luigi_Left_Forearm_mesh_layer_1_opt_2),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(1, geo_switch_mario_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_TRANSPARENT, 300, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(1, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_TRANSPARENT, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_Left_Hand_DL_mesh_layer_1_opt_2),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, luigi_left_hand_open_opt_3),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 376, -72, -232, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, luigi_Right_Arm_Color_mesh_layer_1_opt_2),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_TRANSPARENT, 240, 0, 0, luigi_Right_Forearm_mesh_layer_1_opt_2),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(0, geo_switch_mario_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_TRANSPARENT, 300, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(0, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_TRANSPARENT, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_Right_Hand_DL_mesh_layer_1_opt_2),
														GEO_CLOSE_NODE(),
														GEO_SCALE(LAYER_TRANSPARENT, 243719),
														GEO_OPEN_NODE(),
															GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, luigi_right_hand_open_opt_3),
												GEO_BRANCH(1, luigi_right_hand_peace_opt_3),
												GEO_BRANCH(1, luigi_right_hand_cap_opt_3),
												GEO_BRANCH(1, luigi_right_hand_wing_cap_opt_3),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 92, -32, 152, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, luigi_Left_Thigh_Color_mesh_layer_1_opt_2),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 396, 0, 0, luigi_Left_Leg_mesh_layer_1_opt_2),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 268, 0, 0, luigi_Left_Shoe_mesh_layer_1_opt_2),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 92, -32, -152, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, luigi_Right_Thigh_Color_mesh_layer_1_opt_2),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 396, 0, 0, luigi_Right_Leg_mesh_layer_1_opt_2),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 268, 0, 0, luigi_Right_Shoe_mesh_layer_1_opt_2),
								GEO_OPEN_NODE(),
									GEO_ASM(2, geo_mario_hand_foot_scaler),
									GEO_SCALE(LAYER_TRANSPARENT, 65536),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_Right_Shoe_DL_mesh_layer_1_opt_3_with_layer_1_revert),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(99, 180, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 17623),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_mirror_mario_backface_culling),
				GEO_ASM(0, geo_mirror_mario_set_alpha),
				GEO_SWITCH_CASE(0, geo_switch_mario_cap_effect),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_SCALE(LAYER_FORCE, 16384),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_FORCE, 168, 32, 0, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_ASM(0, geo_move_mario_part_from_parent),
										GEO_ASM(0, geo_mario_tilt_torso),
										GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, luigi_Torso_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 552, -32, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_mario_head_rotation),
													GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
													GEO_OPEN_NODE(),
														GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
														GEO_OPEN_NODE(),
															GEO_NODE_START(),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_Cap_DL_mesh_layer_1),
															GEO_CLOSE_NODE(),
															GEO_BRANCH(1, luigi_head_capless),
														GEO_CLOSE_NODE(),
														GEO_SWITCH_CASE(0, geo_switch_mario_eye_custom),
														GEO_OPEN_NODE(),
															GEO_NODE_START(),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_Eyes_DL_mesh_layer_1),
															GEO_CLOSE_NODE(),
															GEO_BRANCH(1, luigi_eyes_half_closed),
															GEO_BRANCH(1, luigi_eyes_closed),
															GEO_BRANCH(1, luigi_eyes_tiptoe),
															GEO_BRANCH(1, luigi_eyes_angry),
															GEO_BRANCH(1, luigi_eyes_happy),
															GEO_BRANCH(1, luigi_eyes_exhausted),
															GEO_BRANCH(1, luigi_eyes_dead),
															GEO_BRANCH(1, luigi_eyes_hurt),
														GEO_CLOSE_NODE(),
														GEO_SWITCH_CASE(0, geo_switch_mario_face),
														GEO_OPEN_NODE(),
															GEO_NODE_START(),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_Face_DL_mesh_layer_1),
															GEO_CLOSE_NODE(),
															GEO_BRANCH(1, luigi_geo_opt_1),
															GEO_BRANCH(1, luigi_geo_opt_2),
															GEO_BRANCH(1, luigi_face_happy),
															GEO_BRANCH(1, luigi_face_angry),
															GEO_BRANCH(1, luigi_face_O),
														GEO_CLOSE_NODE(),
														GEO_TRANSLATE_ROTATE(LAYER_FORCE, 597, -168, 211, -15, 33, -133),
														GEO_OPEN_NODE(),
															GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
															GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_Left_Wing_DL_mesh_layer_1),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
														GEO_TRANSLATE_ROTATE(LAYER_FORCE, 597, -168, -211, 14, -32, -133),
														GEO_OPEN_NODE(),
															GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
															GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_Right_Wing_DL_mesh_layer_1),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 376, -72, 232, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, luigi_Left_Arm_Color_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 240, 0, 0, luigi_Left_Forearm_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_SWITCH_CASE(1, geo_switch_mario_hand),
															GEO_OPEN_NODE(),
																GEO_NODE_START(),
																GEO_OPEN_NODE(),
																	GEO_ANIMATED_PART(LAYER_OPAQUE, 300, 0, 0, NULL),
																	GEO_OPEN_NODE(),
																		GEO_ASM(1, geo_mario_hand_foot_scaler),
																		GEO_SCALE(LAYER_FORCE, 65536),
																		GEO_OPEN_NODE(),
																			GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_Left_Hand_DL_mesh_layer_1),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
																GEO_BRANCH(1, luigi_left_hand_open),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 376, -72, -232, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, luigi_Right_Arm_Color_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 240, 0, 0, luigi_Right_Forearm_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_SWITCH_CASE(0, geo_switch_mario_hand),
															GEO_OPEN_NODE(),
																GEO_NODE_START(),
																GEO_OPEN_NODE(),
																	GEO_ANIMATED_PART(LAYER_OPAQUE, 300, 0, 0, NULL),
																	GEO_OPEN_NODE(),
																		GEO_ASM(0, geo_mario_hand_foot_scaler),
																		GEO_SCALE(LAYER_FORCE, 65536),
																		GEO_OPEN_NODE(),
																			GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_Right_Hand_DL_mesh_layer_1),
																		GEO_CLOSE_NODE(),
																		GEO_SCALE(LAYER_FORCE, 243719),
																		GEO_OPEN_NODE(),
																			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
																GEO_BRANCH(1, luigi_right_hand_open),
																GEO_BRANCH(1, luigi_right_hand_peace),
																GEO_BRANCH(1, luigi_right_hand_cap),
																GEO_BRANCH(1, luigi_right_hand_wing_cap),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 92, -32, 152, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, luigi_Left_Thigh_Color_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 396, 0, 0, luigi_Left_Leg_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 268, 0, 0, luigi_Left_Shoe_mesh_layer_1),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 92, -32, -152, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, luigi_Right_Thigh_Color_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 396, 0, 0, luigi_Right_Leg_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 268, 0, 0, luigi_Right_Shoe_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_ASM(2, geo_mario_hand_foot_scaler),
													GEO_SCALE(LAYER_FORCE, 65536),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_Right_Shoe_DL_mesh_layer_1_with_layer_1_revert),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_BRANCH(1, luigi_geo_opt_1_1),
					GEO_BRANCH(1, luigi_geo_opt_2_1),
					GEO_BRANCH(1, luigi_geo_opt_3),
				GEO_CLOSE_NODE(),
				GEO_ASM(1, geo_mirror_mario_backface_culling),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
