extern const GeoLayout luigis_cap_geo_opt_1[];
extern const GeoLayout luigis_cap_geo[];
extern Lights1 luigis_cap_luigi_cap_lights;
extern Lights1 luigis_cap_mario_cap_wings_lights;
extern Lights1 luigis_cap_luigi_cap_inside_lights;
extern u8 luigis_cap_shine_dull_rgba32[];
extern Vtx luigis_cap_000_displaylist_mesh_layer_1_vtx_0[1150];
extern Gfx luigis_cap_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx luigis_cap_000_displaylist_mesh_layer_1_vtx_1[50];
extern Gfx luigis_cap_000_displaylist_mesh_layer_1_tri_1[];
extern Vtx luigis_cap_000_displaylist_mesh_layer_1_vtx_2[12];
extern Gfx luigis_cap_000_displaylist_mesh_layer_1_tri_2[];
extern Gfx mat_luigis_cap_luigi_cap[];
extern Gfx mat_revert_luigis_cap_luigi_cap[];
extern Gfx mat_luigis_cap_mario_cap_wings[];
extern Gfx mat_revert_luigis_cap_mario_cap_wings[];
extern Gfx mat_luigis_cap_luigi_cap_inside[];
extern Gfx mat_revert_luigis_cap_luigi_cap_inside[];
extern Gfx luigis_cap_000_displaylist_mesh_layer_1_with_layer_1_revert[];
extern Gfx luigis_cap_000_displaylist_mesh_layer_1_with_layer_5_revert[];
