extern const GeoLayout luigis_wing_cap_001_switch_opt1[];
extern const GeoLayout luigis_wing_cap_geo[];
extern Lights1 luigis_wing_cap_mario_cap_wings_lights;
extern Lights1 luigis_wing_cap_luigi_cap_lights;
extern Lights1 luigis_wing_cap_mario_cap_black_lights;
extern u8 luigis_wing_cap_shine_dull_rgba32[];
extern Vtx luigis_wing_cap_000_displaylist_mesh_layer_1_vtx_0[4300];
extern Gfx luigis_wing_cap_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx luigis_wing_cap_000_displaylist_mesh_layer_1_vtx_1[1150];
extern Gfx luigis_wing_cap_000_displaylist_mesh_layer_1_tri_1[];
extern Vtx luigis_wing_cap_000_displaylist_mesh_layer_1_vtx_2[12];
extern Gfx luigis_wing_cap_000_displaylist_mesh_layer_1_tri_2[];
extern Gfx mat_luigis_wing_cap_mario_cap_wings[];
extern Gfx mat_revert_luigis_wing_cap_mario_cap_wings[];
extern Gfx mat_luigis_wing_cap_luigi_cap[];
extern Gfx mat_revert_luigis_wing_cap_luigi_cap[];
extern Gfx mat_luigis_wing_cap_mario_cap_black[];
extern Gfx mat_revert_luigis_wing_cap_mario_cap_black[];
extern Gfx luigis_wing_cap_000_displaylist_mesh_layer_1[];
